FATALPRA: FATAL::Functor::periodic_test< Dist_Info1 > Class Template Reference
FATAL::Functor::periodic_test< Dist_Info1 > Class Template Reference
#include <PeriodicTest.hpp>
Public Member Functions
periodic_test ()=delete
periodic_test (const std::vector< double > &param1, const double &time, const double &ti)
virtual ~periodic_test ()
double previous ()
double operator() ()
double mean ()
double median ()
double _5th ()
double _95th ()
double operator() (double time)
double mean (double time)
double median (double time)
double _5th (double time)
double _95th (double time)
Public Member Functions inherited from FATAL::Functor::BE_FUNCTOR_BASE
virtual bool is_corr ()
virtual int order ()
virtual bool is_mc_type ()
virtual ~BE_FUNCTOR_BASE ()
virtual FATAL::FATAL_FAILURE_TYPE get_type ()
virtual void set (const int &_index, const int &_unit_number)
virtual bool get_state (const int &trial)
BE_FUNCTOR_BASE ()
BE_FUNCTOR_BASE (const FATAL::FATAL_FAILURE_TYPE &i_type)
template<class T >
boost::shared_ptr< T > upcast ()
double prob (const int &i_int)
Detailed Description
template<class Dist_Info1>
class FATAL::Functor::periodic_test< Dist_Info1 >
a class which is a base class for basic event computation
Template Parameters
Dist_Info1 a template parameter of a distribution type
Definition at line 39 of file PeriodicTest.hpp.
Constructor & Destructor Documentation
periodic_test() [1/2]
template<class Dist_Info1 > FATAL::Functor::periodic_test< Dist_Info1 >::periodic_test () delete
default constructor deleted
periodic_test() [2/2]
template<class Dist_Info1 > FATAL::Functor::periodic_test< Dist_Info1 >::periodic_test (const std::vector< double > & param1, const double & time, const double & ti)
Definition at line 112 of file PeriodicTest.hpp.
References FATAL::PERIODIC_TESTING.
~periodic_test()
template<class Dist_Info1 > virtual FATAL::Functor::periodic_test< Dist_Info1 >::~periodic_test () inline virtual
default destructor
Definition at line 82 of file PeriodicTest.hpp.
Member Function Documentation
_5th() [1/2]
template<class Dist_Info1 > double FATAL::Functor::periodic_test< Dist_Info1 >::_5th () virtual
a function to obtain 5th percentile from distribution
Returns
a 5th percentile of failure
Implements FATAL::Functor::BE_FUNCTOR_BASE.
Definition at line 154 of file PeriodicTest.hpp.
Referenced by FATAL::Functor::periodic_test< Dist_Info1 >::previous().
_5th() [2/2]
template<class Dist_Info1 > double FATAL::Functor::periodic_test< Dist_Info1 >::_5th (double time) virtual
a function to obtain 5th percentile from distribution at given time
Parameters
time time passed
Returns
a 5th percentile of failure
Implements FATAL::Functor::BE_FUNCTOR_BASE.
Definition at line 211 of file PeriodicTest.hpp.
_95th() [1/2]
template<class Dist_Info1 > double FATAL::Functor::periodic_test< Dist_Info1 >::_95th () virtual
a function to obtain 95th percentile from distribution
Returns
a 95th percentile of failure
Implements FATAL::Functor::BE_FUNCTOR_BASE.
Definition at line 164 of file PeriodicTest.hpp.
Referenced by FATAL::Functor::periodic_test< Dist_Info1 >::previous().
_95th() [2/2]
template<class Dist_Info1 > double FATAL::Functor::periodic_test< Dist_Info1 >::_95th (double time) virtual
a function to obtain random probability from distribution at given time
Parameters
time time passed
Returns
a 95th percentile of failure
Implements FATAL::Functor::BE_FUNCTOR_BASE.
Definition at line 223 of file PeriodicTest.hpp.
mean() [1/2]
template<class Dist_Info1 > double FATAL::Functor::periodic_test< Dist_Info1 >::mean () virtual
a function to obtain mean value from distribution
Returns
a mean probability of failure
Implements FATAL::Functor::BE_FUNCTOR_BASE.
Definition at line 134 of file PeriodicTest.hpp.
Referenced by FATAL::Functor::periodic_test< Dist_Info1 >::previous().
mean() [2/2]
template<class Dist_Info1 > double FATAL::Functor::periodic_test< Dist_Info1 >::mean (double time) virtual
a function to obtain mean probability from distribution at given time
Parameters
time time passed
Returns
mean probability at given time
Implements FATAL::Functor::BE_FUNCTOR_BASE.
Definition at line 186 of file PeriodicTest.hpp.
median() [1/2]
template<class Dist_Info1 > double FATAL::Functor::periodic_test< Dist_Info1 >::median () virtual
a function to obtain median value from distribution
Returns
a median probability of failure
Implements FATAL::Functor::BE_FUNCTOR_BASE.
Definition at line 144 of file PeriodicTest.hpp.
Referenced by FATAL::Functor::periodic_test< Dist_Info1 >::previous().
median() [2/2]
template<class Dist_Info1 > double FATAL::Functor::periodic_test< Dist_Info1 >::median (double time) virtual
a function to obtain median probability from distribution at given time
Parameters
time time passed
Returns
a median probability of failure
Implements FATAL::Functor::BE_FUNCTOR_BASE.
Definition at line 199 of file PeriodicTest.hpp.
operator()() [1/2]
template<class Dist_Info1 > double FATAL::Functor::periodic_test< Dist_Info1 >::operator() () virtual
a function to obtain random value from distribution
Returns
a random probability of failure
Reimplemented from FATAL::Functor::BE_FUNCTOR_BASE.
Definition at line 124 of file PeriodicTest.hpp.
Referenced by FATAL::Functor::periodic_test< Dist_Info1 >::previous().
operator()() [2/2]
template<class Dist_Info1 > double FATAL::Functor::periodic_test< Dist_Info1 >::operator() (double time) virtual
a function to obtain random probability from distribution at given time
Parameters
time time passed
Returns
a random probability from distribution at given time
Reimplemented from FATAL::Functor::BE_FUNCTOR_BASE.
Definition at line 174 of file PeriodicTest.hpp.
previous()
template<class Dist_Info1 > double FATAL::Functor::periodic_test< Dist_Info1 >::previous () inline virtual
obtan a probability of previos calculation
Returns
a probability of previous state
Implements FATAL::Functor::BE_FUNCTOR_BASE.
Definition at line 86 of file PeriodicTest.hpp.
References FATAL::Functor::periodic_test< Dist_Info1 >::_5th(), FATAL::Functor::periodic_test< Dist_Info1 >::_95th(), FATAL::Functor::periodic_test< Dist_Info1 >::mean(), FATAL::Functor::periodic_test< Dist_Info1 >::median(), and FATAL::Functor::periodic_test< Dist_Info1 >::operator()().
The documentation for this class was generated from the following file:
PeriodicTest.hpp
[ FATALPRA Home Page(Not Ready Yet!) ] © 2014–2015, FATALPRA Developer Team.