FATALPRA: FATAL::FT::BE_DB Class Reference
FATAL::FT::BE_DB Class Reference
list of Basic Events and their data
#include <BE_DB.hpp>
Public Member Functions
bool is_mc_type (const boost::shared_ptr< BE > &i_BE)
void update_fragility (const int &i)
std::pair< double, double > access_random (const int &i)
void add_fragility_data (const boost::shared_ptr< Functor::BE_FUNCTOR_BASE > &i_BE_TYPE, const boost::shared_ptr< BE > &i_BE)
void set_corr_dim_fragility (const unsigned int &i)
void add_fragility_correlation (const boost::shared_ptr< BE > &A, const boost::shared_ptr< BE > &B, const double &r_rho, const double &c_rho=0)
std::pair< double, double > get_fragility_correlation (const boost::shared_ptr< BE > &A, const boost::shared_ptr< BE > &B)
void update_random ()
std::pair< Eigen::MatrixXd, Eigen::MatrixXd > initialize_matrix ()
boost::unordered_map< boost::shared_ptr< FT::BE >, int > get_map () const
double prob (const MCS &i_MCS) const
void construct_map ()
int be2int (const boost::shared_ptr< FT::FT_BASE > &i_BE)
boost::shared_ptr< FT::BE > int2be (const int &i) const
void update (const dist_param &i_type)
void check (const boost::shared_ptr< BE > &i_BE)
void add_non_sokc (const boost::shared_ptr< Functor::BE_FUNCTOR_BASE > &i_BE_TYPE, const boost::shared_ptr< BE > &i_BE)
void add_sokc (const std::string &comp_type, const boost::shared_ptr< Functor::BE_FUNCTOR_BASE > &i_BE_TYPE, const boost::shared_ptr< BE > &i_BE)
void clear ()
~BE_DB ()
BE_DB ()
BE_DB (const std::map< std::string, boost::shared_ptr< FATAL::FT::BE >> &i_List, const std::map< std::string, boost::shared_ptr< NBE >> &i_NList)
void AddBE (const boost::shared_ptr< FATAL::FT::FT_BASE > &new_BE, bool do_construct_map=false)
void AddBE (const std::string &BE_Name, const double &prob, bool do_construct_map=false)
template<typename... Args>
void AddBE (const boost::shared_ptr< FATAL::FT::FT_BASE > &new_BE, Args... args)
void AddBEs (const std::vector< boost::shared_ptr< FATAL::FT::FT_BASE >> &BEs, bool do_construct_map=false)
void AddFT (const boost::shared_ptr< FATAL::FT::FT_BASE > &i_FT, bool do_construct_map=false)
boost::shared_ptr< FATAL::FT::BE > get_BE (std::string BE_Name)
boost::shared_ptr< FATAL::FT::NBE > get_NBE (std::string BE_Name)
boost::shared_ptr< BE_DB > copy ()
bool exists (std::string i_string)
boost::shared_ptr< FATAL::FT::NBE > get_NBE (boost::shared_ptr< FATAL::FT::FT_BASE > &i_BE)
double getProb (std::string BE_Name)
unsigned int size ()
boost::shared_ptr< FATAL::FT::BE > find (const std::string &i_name)
boost::shared_ptr< FATAL::FT::FT_BASE > find_and_check (const std::string &i_name, bool negated=false)
std::vector< boost::shared_ptr< FATAL::FT::BE > > find_and_check_partial (const std::string &i_name)
std::map< std::string, boost::shared_ptr< FATAL::FT::BE > >::iterator begin ()
std::map< std::string, boost::shared_ptr< FATAL::FT::BE > >::iterator end ()
void print ()
bool check_mc (const std::string &comp_type, const boost::shared_ptr< Functor::BE_FUNCTOR_BASE > &i_BE_TYPE, const boost::shared_ptr< BE > &i_BE)
Detailed Description
list of Basic Events and their data
Definition at line 48 of file BE_DB.hpp.
Constructor & Destructor Documentation
~BE_DB()
FATAL::FT::BE_DB::~BE_DB ()
default destructor
Definition at line 839 of file BE_DB.hpp.
Referenced by get_map().
BE_DB() [1/2]
FATAL::FT::BE_DB::BE_DB () inline
default constructor
Definition at line 292 of file BE_DB.hpp.
References AddBE(), AddBEs(), AddFT(), begin(), check_mc(), copy(), end(), exists(), find(), find_and_check(), find_and_check_partial(), get_BE(), get_NBE(), getProb(), print(), and size().
Referenced by copy(), and exists().
BE_DB() [2/2]
FATAL::FT::BE_DB::BE_DB (const std::map< std::string, boost::shared_ptr< FATAL::FT::BE >> & i_List, const std::map< std::string, boost::shared_ptr< NBE >> & i_NList)
constructor
Member Function Documentation
access_random()
std::pair<double, double> FATAL::FT::BE_DB::access_random (const int & i) inline
Definition at line 169 of file BE_DB.hpp.
References add_fragility_correlation(), add_fragility_data(), get_fragility_correlation(), initialize_matrix(), set_corr_dim_fragility(), and update_random().
add_fragility_correlation()
void FATAL::FT::BE_DB::add_fragility_correlation (const boost::shared_ptr< BE > & A, const boost::shared_ptr< BE > & B, const double & r_rho, const double & c_rho = 0)
Definition at line 1020 of file BE_DB.hpp.
References FATAL::FT::fragility_pack::update().
Referenced by access_random().
add_fragility_data()
void FATAL::FT::BE_DB::add_fragility_data (const boost::shared_ptr< Functor::BE_FUNCTOR_BASE > & i_BE_TYPE, const boost::shared_ptr< BE > & i_BE)
register fragility failure type into database.
Definition at line 886 of file BE_DB.hpp.
References FATAL::FT::fragility_pack::update().
Referenced by access_random(), add_non_sokc(), and add_sokc().
add_non_sokc()
void FATAL::FT::BE_DB::add_non_sokc (const boost::shared_ptr< Functor::BE_FUNCTOR_BASE > & i_BE_TYPE, const boost::shared_ptr< BE > & i_BE)
a function to add a basic event into non-sokc database
Parameters
i_BE_TYPE a failure type of a basic event
i_BE a basic event to be added into a non-sokc DB
Definition at line 796 of file BE_DB.hpp.
References add_fragility_data(), FATAL::FT::nonSOKC::add_non_sokc(), and check().
Referenced by get_map().
add_sokc()
void FATAL::FT::BE_DB::add_sokc (const std::string & comp_type, const boost::shared_ptr< Functor::BE_FUNCTOR_BASE > & i_BE_TYPE, const boost::shared_ptr< BE > & i_BE)
a function to add a basic event into non-sokc database
Parameters
comp_type a tag of sokc components. for seiscmically correlated fragility type, use mc_fragility
i_BE_TYPE a failure type of a basic event
i_BE a basic event to be added into a non-sokc DB
Returns
void
Definition at line 812 of file BE_DB.hpp.
References add_fragility_data(), FATAL::FT::SOKC::add_sokc(), check(), and check_mc().
Referenced by get_map().
AddBE() [1/3]
void FATAL::FT::BE_DB::AddBE (const boost::shared_ptr< FATAL::FT::FT_BASE > & new_BE, bool do_construct_map = false)
add a basic event to database
Parameters
new_BE a basic event to be added into BE_DB
do_construct_map if true, then it construct a 1-by-1 relation for minimal cut set computation.
Returns
void
Definition at line 607 of file BE_DB.hpp.
References construct_map(), and FATAL::FT::NBE::get_ptr().
Referenced by AddBE(), AddBEs(), AddFT(), and BE_DB().
AddBE() [2/3]
void FATAL::FT::BE_DB::AddBE (const std::string & BE_Name, const double & prob, bool do_construct_map = false)
add a basic event to database based on a probability and basic event name
Parameters
new_BE a basic event to be added into BE_DB
do_construct_map if true, then it construct a 1-by-1 relation for minimal cut set computation.
Returns
void
Definition at line 577 of file BE_DB.hpp.
References construct_map().
AddBE() [3/3]
template<typename... Args> void FATAL::FT::BE_DB::AddBE (const boost::shared_ptr< FATAL::FT::FT_BASE > & new_BE, Args... args)
variadic AddBe implementation.
Note: this implementation does not construct a map for minimal cut set. Please call construct_map() explicitly.
Template Parameters
Args variadic argument
Parameters
new_BE new_BE a basic event to be added into BE_DB
args a variadic argument. This is expected to be a shared pointer to a basic event
Definition at line 600 of file BE_DB.hpp.
References AddBE().
AddBEs()
void FATAL::FT::BE_DB::AddBEs (const std::vector< boost::shared_ptr< FATAL::FT::FT_BASE >> & BEs, bool do_construct_map = false)
easy way to add basic events using std::vector
Parameters
BEs a vector of shared pointers of basic events
do_construct_map if true, then it construct a 1-by-1 relation for minimal cut set computation.
Definition at line 454 of file BE_DB.hpp.
References AddBE(), and construct_map().
Referenced by BE_DB().
AddFT()
void FATAL::FT::BE_DB::AddFT (const boost::shared_ptr< FATAL::FT::FT_BASE > & i_FT, bool do_construct_map = false)
construct a BE_DB using a fault tree.
Parameters
i_FT a shared pointer of a fault tree class
do_construct_map if true, then it construct a 1-by-1 relation for minimal cut set computation.
Returns
void
Definition at line 859 of file BE_DB.hpp.
References AddBE(), CHECKNULL, construct_map(), and end().
Referenced by BE_DB().
be2int()
int FATAL::FT::BE_DB::be2int (const boost::shared_ptr< FT::FT_BASE > & i_BE)
convert a shared pointer of a basic event into an index of minimal cut set.
Parameters
i_BE an input basic event
Returns
an index of minimal cut set
Definition at line 751 of file BE_DB.hpp.
Referenced by get_map().
begin()
std::map< std::string, boost::shared_ptr< BE > >::iterator FATAL::FT::BE_DB::begin ()
Definition at line 549 of file BE_DB.hpp.
Referenced by BE_DB().
check()
void FATAL::FT::BE_DB::check (const boost::shared_ptr< BE > & i_BE)
a function to check if a basic event exists in sokc or non-sokc list.
Parameters
i_BE a shared pointer of an input basic event
Returns
void
Definition at line 781 of file BE_DB.hpp.
Referenced by add_non_sokc(), add_sokc(), and get_map().
check_mc()
bool FATAL::FT::BE_DB::check_mc (const std::string & comp_type, const boost::shared_ptr< Functor::BE_FUNCTOR_BASE > & i_BE_TYPE, const boost::shared_ptr< BE > & i_BE)
Definition at line 997 of file BE_DB.hpp.
References FATAL::to_lower().
Referenced by add_sokc(), and BE_DB().
clear()
void FATAL::FT::BE_DB::clear ()
a function to clear database
Definition at line 829 of file BE_DB.hpp.
Referenced by get_map().
construct_map()
void FATAL::FT::BE_DB::construct_map ()
a function to construct a map for minimal cut set
Definition at line 672 of file BE_DB.hpp.
References end(), and is_mc_type().
Referenced by AddBE(), AddBEs(), AddFT(), and get_map().
copy()
boost::shared_ptr< BE_DB > FATAL::FT::BE_DB::copy ()
copy database. Note that the inside are soft link.
Returns
a copy of boost::shared_ptr<BE_DB>
Definition at line 741 of file BE_DB.hpp.
References BE_DB().
Referenced by BE_DB().
end()
std::map< std::string, boost::shared_ptr< BE > >::iterator FATAL::FT::BE_DB::end ()
Definition at line 554 of file BE_DB.hpp.
Referenced by AddFT(), BE_DB(), construct_map(), and print().
exists()
bool FATAL::FT::BE_DB::exists (std::string i_string)
check if a basic name with i_string exists in database
Parameters
i_string a name of a basic event
Returns
true if a basic event is found, otherwise false
Definition at line 559 of file BE_DB.hpp.
References BE_DB().
Referenced by BE_DB().
find()
boost::shared_ptr< FATAL::FT::BE > FATAL::FT::BE_DB::find (const std::string & i_name)
Deprecated:
use get_BE instead.
Parameters
i_name a name of a basic event
Returns
a shared pointer of a basic event find a BE
find a BE
Todo:
throw an error here
Definition at line 474 of file BE_DB.hpp.
Referenced by BE_DB().
find_and_check()
boost::shared_ptr< FATAL::FT::FT_BASE > FATAL::FT::BE_DB::find_and_check (const std::string & i_name, bool negated = false)
find a BE or return nullptr
Parameters
i_name a name of a basic event
negated if true, then return a negated basic event
Returns
a shared pointer of a basic event if found. Otherwise, nullptr.
Definition at line 493 of file BE_DB.hpp.
Referenced by BE_DB().
find_and_check_partial()
std::vector< boost::shared_ptr< FATAL::FT::BE > > FATAL::FT::BE_DB::find_and_check_partial (const std::string & i_name)
Definition at line 525 of file BE_DB.hpp.
Referenced by BE_DB().
get_BE()
boost::shared_ptr< FATAL::FT::BE > FATAL::FT::BE_DB::get_BE (std::string BE_Name)
get a shared_ptr from a database from a basic event name
Parameters
BE_Name a name of basic event
Returns
a shared pointer of a basic event found
Exceptions
FATAL::Exception::NoBE a basic event is not found
Definition at line 712 of file BE_DB.hpp.
Referenced by BE_DB().
get_fragility_correlation()
std::pair< double, double > FATAL::FT::BE_DB::get_fragility_correlation (const boost::shared_ptr< BE > & A, const boost::shared_ptr< BE > & B)
Definition at line 1031 of file BE_DB.hpp.
References FATAL::FT::fragility_pack::get().
Referenced by access_random().
get_map()
boost::unordered_map< boost::shared_ptr< FT::BE >, int > FATAL::FT::BE_DB::get_map () const inline
get basic event to int map
Returns
unordered_map from BE to int
Definition at line 204 of file BE_DB.hpp.
References add_non_sokc(), add_sokc(), be2int(), check(), clear(), construct_map(), int2be(), prob(), update(), and ~BE_DB().
get_NBE() [1/2]
boost::shared_ptr< FATAL::FT::NBE > FATAL::FT::BE_DB::get_NBE (std::string BE_Name)
get a shared_ptr of negated basic event from a database
Parameters
BE_Name a name of basic event
Returns
a shared pointer of a basic event found
Exceptions
FATAL::Exception::NoBE a basic event is not found
Definition at line 726 of file BE_DB.hpp.
Referenced by BE_DB(), and get_NBE().
get_NBE() [2/2]
boost::shared_ptr< FATAL::FT::NBE > FATAL::FT::BE_DB::get_NBE (boost::shared_ptr< FATAL::FT::FT_BASE > & i_BE)
get a shared_ptr from a database.
Note: this function does not negate a basic event, but it returns a negated basic event.
Parameters
i_BE a shared pointer of a basic event
Returns
a negated basic event
Definition at line 845 of file BE_DB.hpp.
References get_NBE().
getProb()
double FATAL::FT::BE_DB::getProb (std::string BE_Name)
Parameters
BE_Name a name of basic event
Returns
a probability of a basic event
Exceptions
FATAL::Exception::NoBE a basic event is not found. get a probabily of basic event
Definition at line 698 of file BE_DB.hpp.
Referenced by BE_DB().
initialize_matrix()
std::pair< Eigen::MatrixXd, Eigen::MatrixXd > FATAL::FT::BE_DB::initialize_matrix ()
Definition at line 914 of file BE_DB.hpp.
References FATAL::FT::fragility_pack::construct_matrix(), FATAL::FT::fragility_pack::get_order(), FATAL::Matrix::transform< pdf >::size(), and FATAL::FT::fragility_pack::size().
Referenced by access_random().
int2be()
boost::shared_ptr< FT::BE > FATAL::FT::BE_DB::int2be (const int & i) const
convert a index of minimal cut set into a shared pointer of a basic event.
Parameters
i an index of minimal cut set
Returns
a shared pointer of a basic event
Definition at line 756 of file BE_DB.hpp.
Referenced by get_map().
is_mc_type()
bool FATAL::FT::BE_DB::is_mc_type (const boost::shared_ptr< BE > & i_BE) inline
Definition at line 142 of file BE_DB.hpp.
Referenced by construct_map().
print()
void FATAL::FT::BE_DB::print ()
print() print all basic events in database
Definition at line 541 of file BE_DB.hpp.
References end().
Referenced by BE_DB().
prob()
double FATAL::FT::BE_DB::prob (const MCS & i_MCS) const
convert MCS into probabilty
Parameters
i_MCS an input a minimal cut set
Returns
probability of a minimal cut set
Definition at line 591 of file MCS.hpp.
References FATAL::MCS::_MCS.
Referenced by get_map().
set_corr_dim_fragility()
void FATAL::FT::BE_DB::set_corr_dim_fragility (const unsigned int & i)
Definition at line 1015 of file BE_DB.hpp.
References FATAL::FT::fragility_pack::resize().
Referenced by access_random().
size()
unsigned int FATAL::FT::BE_DB::size ()
Returns
size of database
Definition at line 572 of file BE_DB.hpp.
Referenced by BE_DB().
update()
void FATAL::FT::BE_DB::update (const dist_param & i_type)
a function to update the sokc and nonsokc basic events
Parameters
i_type an enum class which defines a target quantile or mean.
Warning
this method does not update mc_fragility type!
Definition at line 772 of file BE_DB.hpp.
References FATAL::FT::nonSOKC::update(), and FATAL::FT::SOKC::update().
Referenced by get_map().
update_fragility()
void FATAL::FT::BE_DB::update_fragility (const int & i) inline
Definition at line 153 of file BE_DB.hpp.
References update_random().
update_random()
void FATAL::FT::BE_DB::update_random ()
a function update the basic events based on probabilty distributions provided
Warning
different from void update(const dist_param & i_type), this method update fragility type, too.
Definition at line 1045 of file BE_DB.hpp.
Referenced by access_random(), and update_fragility().
The documentation for this class was generated from the following files:
BE_DB.hpp
MCS.hpp
[ FATALPRA Home Page(Not Ready Yet!) ] © 2014–2015, FATALPRA Developer Team.