FATALPRA: FATAL::FT::nonSOKC Class Reference
FATAL::FT::nonSOKC Class Reference
data structure to handle State of knowledge correlation
#include <nonSOKC.hpp>
Public Member Functions
nonSOKC ()
void add_non_sokc (const boost::shared_ptr< FATAL::FT::BE > &i_BE, const boost::shared_ptr< Functor::BE_FUNCTOR_BASE > &param)
void update (const dist_param &i_type)
Detailed Description
data structure to handle State of knowledge correlation
Definition at line 48 of file nonSOKC.hpp.
Constructor & Destructor Documentation
nonSOKC()
FATAL::FT::nonSOKC::nonSOKC () inline
default constructor
Definition at line 59 of file nonSOKC.hpp.
References add_non_sokc(), and update().
Member Function Documentation
add_non_sokc()
void FATAL::FT::nonSOKC::add_non_sokc (const boost::shared_ptr< FATAL::FT::BE > & i_BE, const boost::shared_ptr< Functor::BE_FUNCTOR_BASE > & param)
a function to add a basic event into nonSOKC database
Parameters
i_BE a shared pointer to a basic event
param a shared pointer to BE_FUNCTOR_BASE, which defines a distribution of a basic event
Definition at line 78 of file nonSOKC.hpp.
Referenced by FATAL::FT::BE_DB::add_non_sokc(), and nonSOKC().
update()
void FATAL::FT::nonSOKC::update (const dist_param & i_type)
Definition at line 94 of file nonSOKC.hpp.
Referenced by nonSOKC(), and FATAL::FT::BE_DB::update().
The documentation for this class was generated from the following file:
nonSOKC.hpp
[ FATALPRA Home Page(Not Ready Yet!) ] © 2014–2015, FATALPRA Developer Team.