FATALPRA: FATAL::io Namespace Reference
FATAL::io Namespace Reference
Classes
class ET_READ
class FT_READ
class ftd
class ifstream
class ofstream
Functions
template<typename T >
ofstream & operator<< (ofstream &os, const T &data)
ofstream & operator<< (ofstream &os, std::ostream &(*f)(std::ostream &))
std::vector< std::string > token (std::string &i_str, const std::string &sep_str)
Function Documentation
operator<<() [1/2]
template<typename T > ofstream& FATAL::io::operator<< (ofstream & os, const T & data)
Definition at line 144 of file proxy_io.hpp.
References FATAL::io::ofstream::write().
operator<<() [2/2]
ofstream& FATAL::io::operator<< (ofstream & os, std::ostream &(*)(std::ostream &) f)
Definition at line 151 of file proxy_io.hpp.
References FATAL::io::ofstream::get_stream().
token()
std::vector<std::string> FATAL::io::token (std::string & i_str, const std::string & sep_str)
Definition at line 31 of file token.hpp.
Referenced by FATAL::io::ifstream::ifstream().
[ FATALPRA Home Page(Not Ready Yet!) ] © 2014–2015, FATALPRA Developer Team.