FATALPRA: FATAL::FT::ITE Class Reference
FATAL::FT::ITE Class Reference
ITE implements if-then-else operation for logic gate.
#include <ITE.hpp>
Public Member Functions
virtual ~ITE ()
ITE ()
ITE (const std::string &i_name)
template<class return_type >
return_type GateOp ()
template<class return_type , class mgr >
return_type GateOp (mgr &i_mgr)
template<class return_type , class class1 , class class2 >
return_type GateOp (class1 &i_class1, class2 &i_class2)
template<class return_type , class class1 , class class2 , class class3 >
return_type GateOp (class1 &i_class1, class2 &i_class2, class3 &i_class3)
boost::shared_ptr< FT_BASE > get_same_type () const
void ite (const boost::shared_ptr< FT_BASE > &a, const boost::shared_ptr< FT_BASE > &b, const boost::shared_ptr< FT_BASE > &c)
void validate (const boost::shared_ptr< FT_BASE > &i_FT)
boost::shared_ptr< FT_BASE > transform ()
template<>
cacBDD::BDD GateOp (boost::shared_ptr< FATAL::DD::dd_mgr< cacBDD::XBDDManager, cacBDD::BDD >> &i_mgr)
template<>
BDD GateOp (boost::shared_ptr< FATAL::DD::dd_mgr< Cudd, BDD >> &i_mgr)
template<>
double GateOp ()
template<>
bool GateOp ()
template<>
std::unordered_set< MCS > GateOp (boost::shared_ptr< BE_DB > &i_DB, double &i_cut_point, int &i_max_num)
Public Member Functions inherited from FATAL::FT::FT_BASE
template<class return_type >
return_type GateOp ()
template<class return_type , class mgr >
return_type GateOp (mgr &i_mgr)
template<class return_type , class class1 , class class2 >
return_type GateOp (class1 &i_class1, class2 &i_class2)
template<class return_type , class class1 , class class2 , class class3 >
return_type GateOp (class1 &i_class1, class2 &i_class2, class3 &i_class3)
virtual ~FT_BASE ()
FT_BASE ()
template<class T >
boost::shared_ptr< T > cast () const
boost::shared_ptr< FT_BASE > get (const int &i) const
FT_BASE (const std::string &i_name)
FT_BASE (const FT_TYPE &i_type)
FT_BASE (const std::string &i_name, const FT_TYPE &i_type)
const unsigned int size () const
std::vector< boost::shared_ptr< FT_BASE > > & getFTs ()
virtual void clear ()
std::vector< boost::shared_ptr< FT_BASE > >::iterator begin ()
std::vector< boost::shared_ptr< FT_BASE > >::iterator end ()
boost::shared_ptr< FT_BASE > & operator[] (const int &i)
bool put (const std::vector< boost::shared_ptr< FT_BASE >> &i_FTs)
bool put (const boost::shared_ptr< FT_BASE > &i_base)
template<typename... Args>
bool put (const boost::shared_ptr< FT_BASE > &i_base, Args... args)
boost::shared_ptr< FT_BASE > get_elem (const std::string &gate_name)
virtual boost::shared_ptr< FT_BASE > h_copy_cyclic (std::vector< boost::shared_ptr< FT_BASE >> paths)
virtual boost::shared_ptr< FT_BASE > h_copy_non_cyclic ()
virtual boost::shared_ptr< FT_BASE > h_copy ()
bool find (const std::string &i_string) const
virtual bool verify ()
virtual int depth (bool initial=true)
virtual boost::shared_ptr< FT_BASE > coalesce (bool second_call=false)
void swap (const boost::shared_ptr< FT_BASE > &from, const boost::shared_ptr< FT_BASE > &to)
bool is_cyclic ()
bool is_cyclic (const std::vector< boost::shared_ptr< FATAL::FT::FT_BASE > > &targets)
template<typename... Args>
bool put (const boost::shared_ptr< FATAL::FT::FT_BASE > &i_base, Args... args)
Public Member Functions inherited from FATAL::FT::BASE
virtual ~BASE ()
BASE ()
BASE (const std::string &i_name)
BASE (const FT_TYPE &i_type)
BASE (const std::string &i_name, const FT_TYPE &i_type)
virtual const FT_TYPE & identify () const
virtual const std::string & get_name () const
void set_name (const std::string &i_name)
Public Member Functions inherited from FATAL::FT::FT_PROPERTY
virtual bool is_coalescible () const
virtual bool isBE () const
virtual bool isNBE () const
virtual bool is_cyclic (const std::vector< boost::shared_ptr< FATAL::FT::FT_BASE >> &targets)
virtual bool is_negated () const
virtual bool is_cond () const
Additional Inherited Members
Protected Attributes inherited from FATAL::FT::FT_BASE
std::vector< boost::shared_ptr< FT_BASE > > FTs
boost::shared_ptr< FT_BASE > _equiv_ft
Protected Attributes inherited from FATAL::FT::BASE
std::string name
FT_TYPE my_type
Detailed Description
ITE implements if-then-else operation for logic gate.
Definition at line 37 of file ITE.hpp.
Constructor & Destructor Documentation
~ITE()
virtual FATAL::FT::ITE::~ITE () inline virtual
destructor
Definition at line 44 of file ITE.hpp.
ITE() [1/2]
FATAL::FT::ITE::ITE () inline
constructor
Definition at line 46 of file ITE.hpp.
ITE() [2/2]
FATAL::FT::ITE::ITE (const std::string & i_name) inline
constructor
Definition at line 49 of file ITE.hpp.
References GateOp().
Member Function Documentation
GateOp() [1/9]
template<class return_type > return_type FATAL::FT::ITE::GateOp ()
Operation defined by gate type. This will be implemented using technique shown in http://d.hatena.ne.jp/kazuhooku/20090727/1248690940 To use this class, template specialization is required.
Template Parameters
return_type template parameter of return type
Returns
return value is specificied by template specialization
Definition at line 607 of file GATEOP.hpp.
Referenced by ITE().
GateOp() [2/9]
template<class return_type , class mgr > return_type FATAL::FT::ITE::GateOp (mgr & i_mgr)
Operation defined by Gate Type. This will be implemented using technique shown in http://d.hatena.ne.jp/kazuhooku/20090727/1248690940 To use this class, template specialization is required.
Template Parameters
return_type template parameter of return type
mgr template paramter for input
Parameters
i_mgr input variable with template type mgr
Returns
return value is specificied by template specialization
Definition at line 615 of file GATEOP.hpp.
GateOp() [3/9]
template<class return_type , class class1 , class class2 > return_type FATAL::FT::ITE::GateOp (class1 & i_class1, class2 & i_class2)
Operation defined by Gate Type. This will be implemented using technique shown in http://d.hatena.ne.jp/kazuhooku/20090727/1248690940 To use this class, template specialization is required.
Template Parameters
return_type template parameter of return type
class1 template parameter for input
class2 template parameter for input
Parameters
i_class1 input variable with template type class1
i_class2 input variable with template type class2
Returns
return value is specificied by template specialization
Definition at line 625 of file GATEOP.hpp.
GateOp() [4/9]
template<class return_type , class class1 , class class2 , class class3 > return_type FATAL::FT::ITE::GateOp (class1 & i_class1, class2 & i_class2, class3 & i_class3)
Operation defined by Gate Type. This will be implemented using technique shown in http://d.hatena.ne.jp/kazuhooku/20090727/1248690940 To use this class, template specialization is required.
Parameters
return_type template parameter of return type
Template Parameters
class1 template parameter for input
class2 template parameter for input
class3 template parameter for input
Parameters
i_class1 input variable with template type class1
i_class2 input variable with template type class2
i_class3 input variable with template type class2
Returns
return value is specificied by template specialization
Definition at line 634 of file GATEOP.hpp.
GateOp() [5/9]
template<> double FATAL::FT::ITE::GateOp ()
Definition at line 133 of file HMC_GATE_OP.hpp.
References CHECK_GT, and FATAL::FT::FT_BASE::FTs.
GateOp() [6/9]
template<> bool FATAL::FT::ITE::GateOp ()
Definition at line 148 of file MC_GATE_OP.hpp.
References FATAL::FT::FT_BASE::FTs.
GateOp() [7/9]
template<> cacBDD::BDD FATAL::FT::ITE::GateOp (boost::shared_ptr< FATAL::DD::dd_mgr< cacBDD::XBDDManager, cacBDD::BDD >> & i_mgr)
Definition at line 261 of file CacBDD_GATEOP.hpp.
References FATAL::FT::FT_BASE::FTs.
GateOp() [8/9]
template<> template<> std::unordered_set< MCS > FATAL::FT::ITE::GateOp (boost::shared_ptr< BE_DB > & i_DB, double & i_cut_point, int & i_max_num)
a template specialization for Four parameter GateOp with minimal cut set
Parameters
i_DB input database
i_cut_point probability cut off
i_max_num maximum number of minimal cut set
Warning
this gate is not supported in minimal cut set.
Exceptions
Exception::LogicError always returned.
Returns
a set of minimal cut set
Definition at line 264 of file MCS_GATEOP.hpp.
GateOp() [9/9]
template<> BDD FATAL::FT::ITE::GateOp (boost::shared_ptr< FATAL::DD::dd_mgr< Cudd, BDD >> & i_mgr)
Definition at line 271 of file CUDD_GATEOP.hpp.
References FATAL::FT::FT_BASE::FTs, and FATAL::FT::BE::GateOp().
get_same_type()
boost::shared_ptr< FT_BASE > FATAL::FT::ITE::get_same_type () const inline virtual
a function to construct a shared_ptr of the same type.
Returns
a shared pointer of FT::GT
Reimplemented from FATAL::FT::FT_BASE.
Definition at line 112 of file ITE.hpp.
References ite(), transform(), and validate().
ite()
void FATAL::FT::ITE::ite (const boost::shared_ptr< FT_BASE > & a, const boost::shared_ptr< FT_BASE > & b, const boost::shared_ptr< FT_BASE > & c)
assign fault trees to perform a ? b : c on a logic gate.
Parameters
a a shared pointer to a fault tree
b a shared pointer to a fault tree
c a shared pointer to a fault tree
Definition at line 140 of file ITE.hpp.
References FATAL::FT::FT_BASE::FTs.
Referenced by get_same_type().
transform()
boost::shared_ptr< FT_BASE > FATAL::FT::ITE::transform () virtual
a function to obtain equivalent gate structure.
Reimplemented from FATAL::FT::FT_BASE.
Definition at line 234 of file GATE/GATE.hpp.
References FATAL::FT::FT_BASE::_equiv_ft, and FATAL::FT::FT_BASE::FTs.
Referenced by get_same_type().
validate()
void FATAL::FT::ITE::validate (const boost::shared_ptr< FT_BASE > & i_FT) virtual
validate ITE gate
Exceptions
throw FATAL::Exception::GateException a number of elements mismatches
Reimplemented from FATAL::FT::FT_BASE.
Definition at line 175 of file ITE.hpp.
References CHECKSUM, and FATAL::FT::FT_BASE::FTs.
Referenced by get_same_type().
The documentation for this class was generated from the following files:
ITE.hpp
GATE/GATE.hpp
GATEOP.hpp
CacBDD_GATEOP.hpp
CUDD_GATEOP.hpp
HMC_GATE_OP.hpp
MC_GATE_OP.hpp
MCS_GATEOP.hpp
[ FATALPRA Home Page(Not Ready Yet!) ] © 2014–2015, FATALPRA Developer Team.