FATALPRA: FATAL::CCF::Datum Class Reference
FATAL::CCF::Datum Class Reference
a class to hold each historical CCF event
#include <impactVector.hpp>
Public Member Functions
Datum ()=delete
Datum (const Type &type, const std::vector< double > &P)
Datum (const Type &type, const std::vector< double > &P, const double &c, const double p)
std::vector< double > _F () const
double coef (const unsigned int &n, const unsigned int &m, const unsigned int &s, const unsigned int &k) const
std::vector< double > MapUp (const std::vector< double > &F, const unsigned int &new_CCCG, const double rho) const
double probability_lower (const int &n, const int &j) const
double probability_same (const int &n, const int &j) const
std::vector< double > MapDown (const std::vector< double > &F, const unsigned int &new_CCCG) const
std::vector< double > Map (const unsigned int &CCCG, const double &rho=-1) const
std::vector< double > Map (const unsigned int &CCCG, std::function< const double(const std::vector< double >)> functor=nullptr) const
Detailed Description
a class to hold each historical CCF event
Definition at line 44 of file impactVector.hpp.
Constructor & Destructor Documentation
Datum() [1/3]
FATAL::CCF::Datum::Datum () delete
Datum() [2/3]
FATAL::CCF::Datum::Datum (const Type & type, const std::vector< double > & P) inline
Definition at line 61 of file impactVector.hpp.
Datum() [3/3]
FATAL::CCF::Datum::Datum (const Type & type, const std::vector< double > & P, const double & c, const double p) inline
Definition at line 63 of file impactVector.hpp.
Member Function Documentation
_F()
std::vector<double> FATAL::CCF::Datum::_F () const inline
Definition at line 65 of file impactVector.hpp.
References FATAL::combinations(), FATAL::CCF::func1, FATAL::CCF::func2, and FATAL::CCF::init.
coef()
double FATAL::CCF::Datum::coef (const unsigned int & n, const unsigned int & m, const unsigned int & s, const unsigned int & k) const inline
Definition at line 145 of file impactVector.hpp.
References FATAL::combination().
Map() [1/2]
std::vector<double> FATAL::CCF::Datum::Map (const unsigned int & CCCG, const double & rho = -1) const inline
Definition at line 249 of file impactVector.hpp.
References FATAL::CCF::CCF, and FATAL::CCF::IND.
Map() [2/2]
std::vector<double> FATAL::CCF::Datum::Map (const unsigned int & CCCG, std::function< const double(const std::vector< double >)> functor = nullptr) const inline
Definition at line 297 of file impactVector.hpp.
References FATAL::CCF::CCF, and FATAL::CCF::IND.
MapDown()
std::vector<double> FATAL::CCF::Datum::MapDown (const std::vector< double > & F, const unsigned int & new_CCCG) const inline
Definition at line 219 of file impactVector.hpp.
References FATAL::CCF::IND.
MapUp()
std::vector<double> FATAL::CCF::Datum::MapUp (const std::vector< double > & F, const unsigned int & new_CCCG, const double rho) const inline
Definition at line 161 of file impactVector.hpp.
References FATAL::combination(), and FATAL::CCF::IND.
probability_lower()
double FATAL::CCF::Datum::probability_lower (const int & n, const int & j) const inline
Definition at line 209 of file impactVector.hpp.
References FATAL::combination().
probability_same()
double FATAL::CCF::Datum::probability_same (const int & n, const int & j) const inline
Definition at line 214 of file impactVector.hpp.
References FATAL::combination().
The documentation for this class was generated from the following file:
impactVector.hpp
[ FATALPRA Home Page(Not Ready Yet!) ] © 2014–2015, FATALPRA Developer Team.