FATALPRA: FATAL::ET::SEQ Class Reference
FATAL::ET::SEQ Class Reference
a sequence class in an event tree. this class is derived from ET_BASE. a number of instances is counted via counter<SEQ>.
#include <SEQ.hpp>
Public Member Functions
void print ()
CD_SEQ GET_CD_SEQ ()
size_t size ()
void prep (bool is_IE=false)
void prep (std::vector< boost::shared_ptr< FT::FT_BASE >> FTs, std::vector< bool > branch_info)
SEQ ()
SEQ (int i)
SEQ (CD_SEQ _ID)
SEQ (const std::vector< boost::shared_ptr< FT::FT_BASE >> &i_FTs, const std::vector< bool > &i_branch_info)
CD_SEQ getCD ()
FATAL::ET_TYPE GET_ET_TYPE ()
std::string id2str ()
bool is_cyclic ()
bool is_cyclic (std::vector< boost::shared_ptr< ET_BASE >> &targets)
std::pair< boost::shared_ptr< FT::FT_BASE >, bool > & operator[] (const int &i)
std::vector< std::pair< boost::shared_ptr< FT::FT_BASE >, bool > >::iterator begin ()
std::vector< std::pair< boost::shared_ptr< FT::FT_BASE >, bool > >::iterator end ()
boost::shared_ptr< FATAL::FT::FT_BASE > get_Equiv_FT ()
virtual ~SEQ ()
bool validate ()
void assign_type (CD_SEQ _ID)
std::vector< boost::shared_ptr< ET_BASE > > get_seq (bool is_IE=false, bool validate=false)
void null2seq (bool is_IE=false)
Public Member Functions inherited from FATAL::ET::ET_BASE
template<class T >
boost::shared_ptr< T > cast ()
bool is_branch_null (bool state)
ET_BASE ()
ET_BASE (const boost::shared_ptr< ET_BASE > &i_success, const boost::shared_ptr< ET_BASE > &i_fail, const boost::shared_ptr< FATAL::FT::FT_BASE > &i_FT)
ET_BASE (const std::string &i_name)
boost::shared_ptr< FT::FT_BASE > & getFT ()
void assign (const boost::shared_ptr< ET_BASE > i_success, const boost::shared_ptr< ET_BASE > i_fail, bool force=false)
void assign (const boost::shared_ptr< FT::FT_BASE > &i_FT)
void assign (bool path, const boost::shared_ptr< ET_BASE > i_ET)
boost::shared_ptr< ET_BASE > getET (bool status)
void clear ()
void assign_FT (const boost::shared_ptr< FT::FT_BASE > &i_FT)
virtual ~ET_BASE ()
virtual void auto_replace (std::vector< boost::shared_ptr< ET_BASE >> &sequences)
virtual bool is_replacible (bool state)
Public Member Functions inherited from FATAL::ET::ET_PROPERTY
ET_PROPERTY ()
ET_PROPERTY (std::string i_evt)
void set_evt (const std::string &i_name)
std::string get_evt ()
Additional Inherited Members
Protected Attributes inherited from FATAL::ET::ET_BASE
boost::shared_ptr< FT::FT_BASE > FT
boost::shared_ptr< ET_BASE > success
boost::shared_ptr< ET_BASE > fail
Detailed Description
a sequence class in an event tree. this class is derived from ET_BASE. a number of instances is counted via counter<SEQ>.
Definition at line 40 of file SEQ.hpp.
Constructor & Destructor Documentation
SEQ() [1/4]
FATAL::ET::SEQ::SEQ () inline
default constructor
Definition at line 90 of file SEQ.hpp.
References FATAL::OK.
Referenced by SEQ().
SEQ() [2/4]
FATAL::ET::SEQ::SEQ (int i)
constructor
Definition at line 371 of file SEQ.hpp.
References assign_type(), and FATAL::END.
SEQ() [3/4]
FATAL::ET::SEQ::SEQ (CD_SEQ _ID) inline
constructor
Definition at line 97 of file SEQ.hpp.
References SEQ().
SEQ() [4/4]
FATAL::ET::SEQ::SEQ (const std::vector< boost::shared_ptr< FT::FT_BASE >> & i_FTs, const std::vector< bool > & i_branch_info)
constructor
Parameters
i_FTs a vector of fault trees in sequence
i_branch_info a vector of branch information
Definition at line 345 of file SEQ.hpp.
References prep().
~SEQ()
virtual FATAL::ET::SEQ::~SEQ () inline virtual
virtual destructor
Definition at line 166 of file SEQ.hpp.
References assign_type(), get_seq(), null2seq(), and validate().
Member Function Documentation
assign_type()
void FATAL::ET::SEQ::assign_type (CD_SEQ _ID) virtual
assign a CD_SEQ type
Parameters
_ID core damage sequence ID
Reimplemented from FATAL::ET::ET_BASE.
Definition at line 382 of file SEQ.hpp.
References FATAL::END.
Referenced by SEQ(), and ~SEQ().
begin()
std::vector<std::pair<boost::shared_ptr<FT::FT_BASE>, bool> >::iterator FATAL::ET::SEQ::begin () inline
Definition at line 153 of file SEQ.hpp.
end()
std::vector<std::pair<boost::shared_ptr<FT::FT_BASE>, bool> >::iterator FATAL::ET::SEQ::end () inline
Definition at line 160 of file SEQ.hpp.
References get_Equiv_FT().
GET_CD_SEQ()
CD_SEQ FATAL::ET::SEQ::GET_CD_SEQ () inline
Definition at line 61 of file SEQ.hpp.
get_Equiv_FT()
boost::shared_ptr< FATAL::FT::FT_BASE > FATAL::ET::SEQ::get_Equiv_FT () virtual
convert a sequence into equivalent FT
Reimplemented from FATAL::ET::ET_BASE.
Definition at line 301 of file SEQ.hpp.
Referenced by end().
GET_ET_TYPE()
FATAL::ET_TYPE FATAL::ET::SEQ::GET_ET_TYPE () inline virtual
get a ET_TYPE
Parameters
ET_TYPE::SEQ
Reimplemented from FATAL::ET::ET_BASE.
Definition at line 118 of file SEQ.hpp.
References FATAL::SEQ.
get_seq()
std::vector< boost::shared_ptr< ET_BASE > > FATAL::ET::SEQ::get_seq (bool is_IE = false, bool validate = false) virtual
Reimplemented from FATAL::ET::ET_BASE.
Definition at line 232 of file SEQ.hpp.
Referenced by ~SEQ().
getCD()
CD_SEQ FATAL::ET::SEQ::getCD () inline
get a CD sequence ID
Returns
CD_SEQ
Definition at line 111 of file SEQ.hpp.
id2str()
std::string FATAL::ET::SEQ::id2str () inline
return a sequence type in std::string
Returns
std::string of a sequence type
Definition at line 125 of file SEQ.hpp.
References FATAL::id2str().
Referenced by print().
is_cyclic() [1/2]
bool FATAL::ET::SEQ::is_cyclic () inline virtual
check if cyclic
Returns
always false
Implements FATAL::ET::ET_BASE.
Definition at line 132 of file SEQ.hpp.
is_cyclic() [2/2]
bool FATAL::ET::SEQ::is_cyclic (std::vector< boost::shared_ptr< ET_BASE >> & targets) inline virtual
check if cyclic
Returns
always false
Implements FATAL::ET::ET_BASE.
Definition at line 139 of file SEQ.hpp.
References operator[]().
null2seq()
void FATAL::ET::SEQ::null2seq (bool isIE = false) virtual
replace all nullptr to sequences
Warning
this function replaces all nullptr with shared pointers of ET::SEQ class.
Reimplemented from FATAL::ET::ET_BASE.
Definition at line 266 of file SEQ.hpp.
Referenced by ~SEQ().
operator[]()
std::pair< boost::shared_ptr< FT::FT_BASE >, bool > & FATAL::ET::SEQ::operator[] (const int & i)
access a FT
Returns
a set of fault tree and its branching information
Definition at line 271 of file SEQ.hpp.
Referenced by is_cyclic().
prep() [1/2]
void FATAL::ET::SEQ::prep (bool is_IE = false) virtual
prepare sequence class for analysis
Warning
this member function should not be called. This always returns an exception.
Reimplemented from FATAL::ET::ET_BASE.
Definition at line 295 of file SEQ.hpp.
Referenced by SEQ(), and size().
prep() [2/2]
void FATAL::ET::SEQ::prep (std::vector< boost::shared_ptr< FT::FT_BASE >> FTs, std::vector< bool > branch_info) virtual
prepare sequence for BDD, MC, etc...
Parameters
FTs a vector of fault trees in sequence path
branch_info branch information
Reimplemented from FATAL::ET::ET_BASE.
Definition at line 282 of file SEQ.hpp.
print()
void FATAL::ET::SEQ::print () inline virtual
Reimplemented from FATAL::ET::ET_BASE.
Definition at line 56 of file SEQ.hpp.
References id2str().
size()
size_t FATAL::ET::SEQ::size () inline
return a size of sequence info.
Definition at line 70 of file SEQ.hpp.
References prep().
validate()
bool FATAL::ET::SEQ::validate ()
validate a sequence
Definition at line 356 of file SEQ.hpp.
Referenced by ~SEQ().
The documentation for this class was generated from the following file:
SEQ.hpp
[ FATALPRA Home Page(Not Ready Yet!) ] © 2014–2015, FATALPRA Developer Team.