FATALPRA: FATAL::FT::NBE Class Reference
FATAL::FT::NBE Class Reference
#include <NBE.hpp>
Public Member Functions
NBE ()
NBE (const boost::shared_ptr< BE > &BE_in)
boost::shared_ptr< FT_BASE > get_same_type () const
NBE (const boost::shared_ptr< FT_BASE > &BE_in)
int depth (bool initial=true)
boost::shared_ptr< FT_BASE > get_ptr ()
double get_prob ()
bool is_cyclic ()
bool is_cyclic (const std::vector< boost::shared_ptr< FT_BASE >> &targets)
const std::string & get_name () const
bool isBE () const
bool isNBE () const
bool is_negated () const
template<class return_type >
return_type GateOp ()
template<class return_type , class mgr >
return_type GateOp (mgr &i_mgr)
template<class return_type , class class1 , class class2 >
return_type GateOp (class1 &i_class1, class2 &i_class2)
template<class return_type , class class1 , class class2 , class class3 >
return_type GateOp (class1 &i_class1, class2 &i_class2, class3 &i_class3)
bool get_state ()
virtual ~NBE ()
void dice ()
void init ()
void init (unsigned int seed)
void assign_prob (double new_prob)
bool is_negated ()
boost::shared_ptr< FT_BASE > transform ()
template<>
cacBDD::BDD GateOp (boost::shared_ptr< FATAL::DD::dd_mgr< cacBDD::XBDDManager, cacBDD::BDD >> &i_mgr)
template<>
BDD GateOp (boost::shared_ptr< FATAL::DD::dd_mgr< Cudd, BDD >> &i_mgr)
template<>
bool GateOp ()
template<>
std::unordered_set< MCS > GateOp (boost::shared_ptr< BE_DB > &i_DB, double &i_cut_point, int &i_max_num)
Public Member Functions inherited from FATAL::FT::FT_BASE
template<class return_type >
return_type GateOp ()
template<class return_type , class mgr >
return_type GateOp (mgr &i_mgr)
template<class return_type , class class1 , class class2 >
return_type GateOp (class1 &i_class1, class2 &i_class2)
template<class return_type , class class1 , class class2 , class class3 >
return_type GateOp (class1 &i_class1, class2 &i_class2, class3 &i_class3)
virtual ~FT_BASE ()
FT_BASE ()
template<class T >
boost::shared_ptr< T > cast () const
boost::shared_ptr< FT_BASE > get (const int &i) const
FT_BASE (const std::string &i_name)
FT_BASE (const FT_TYPE &i_type)
FT_BASE (const std::string &i_name, const FT_TYPE &i_type)
const unsigned int size () const
std::vector< boost::shared_ptr< FT_BASE > > & getFTs ()
virtual void clear ()
std::vector< boost::shared_ptr< FT_BASE > >::iterator begin ()
std::vector< boost::shared_ptr< FT_BASE > >::iterator end ()
boost::shared_ptr< FT_BASE > & operator[] (const int &i)
virtual void validate (const boost::shared_ptr< FT_BASE > &i_FT)
bool put (const std::vector< boost::shared_ptr< FT_BASE >> &i_FTs)
bool put (const boost::shared_ptr< FT_BASE > &i_base)
template<typename... Args>
bool put (const boost::shared_ptr< FT_BASE > &i_base, Args... args)
boost::shared_ptr< FT_BASE > get_elem (const std::string &gate_name)
virtual boost::shared_ptr< FT_BASE > h_copy_cyclic (std::vector< boost::shared_ptr< FT_BASE >> paths)
virtual boost::shared_ptr< FT_BASE > h_copy_non_cyclic ()
virtual boost::shared_ptr< FT_BASE > h_copy ()
bool find (const std::string &i_string) const
virtual bool verify ()
virtual boost::shared_ptr< FT_BASE > coalesce (bool second_call=false)
void swap (const boost::shared_ptr< FT_BASE > &from, const boost::shared_ptr< FT_BASE > &to)
bool is_cyclic ()
bool is_cyclic (const std::vector< boost::shared_ptr< FATAL::FT::FT_BASE > > &targets)
template<typename... Args>
bool put (const boost::shared_ptr< FATAL::FT::FT_BASE > &i_base, Args... args)
Public Member Functions inherited from FATAL::FT::BASE
virtual ~BASE ()
BASE ()
BASE (const std::string &i_name)
BASE (const FT_TYPE &i_type)
BASE (const std::string &i_name, const FT_TYPE &i_type)
virtual const FT_TYPE & identify () const
void set_name (const std::string &i_name)
Public Member Functions inherited from FATAL::FT::FT_PROPERTY
virtual bool is_coalescible () const
virtual bool is_cyclic (const std::vector< boost::shared_ptr< FATAL::FT::FT_BASE >> &targets)
virtual bool is_cond () const
Protected Attributes
boost::shared_ptr< BE > m_BE
Protected Attributes inherited from FATAL::FT::FT_BASE
std::vector< boost::shared_ptr< FT_BASE > > FTs
boost::shared_ptr< FT_BASE > _equiv_ft
Protected Attributes inherited from FATAL::FT::BASE
std::string name
FT_TYPE my_type
Detailed Description
this is negated BE event. result is always opposite to BE.
Definition at line 36 of file NBE.hpp.
Constructor & Destructor Documentation
NBE() [1/3]
FATAL::FT::NBE::NBE () inline
constructor without a regular basic event
Definition at line 50 of file NBE.hpp.
References get_same_type().
NBE() [2/3]
FATAL::FT::NBE::NBE (const boost::shared_ptr< BE > & BE_in)
constructor from a regular basic event
Definition at line 246 of file NBE.hpp.
References m_BE.
NBE() [3/3]
FATAL::FT::NBE::NBE (const boost::shared_ptr< FT_BASE > & BE_in)
constructor from a regular basic event
Definition at line 210 of file NBE.hpp.
References m_BE.
~NBE()
virtual FATAL::FT::NBE::~NBE () inline virtual
default destructor
Definition at line 164 of file NBE.hpp.
Member Function Documentation
assign_prob()
void FATAL::FT::NBE::assign_prob (double new_prob)
assign a probability to negated event. this is not allowed.
Definition at line 240 of file NBE.hpp.
Referenced by init().
depth()
int FATAL::FT::NBE::depth (bool initial = true) inline virtual
Returns
a depth of a negated basic event. always 0
Reimplemented from FATAL::FT::FT_BASE.
Definition at line 69 of file NBE.hpp.
References get_prob(), and get_ptr().
dice()
void FATAL::FT::NBE::dice () inline
dice does nothing because dice is called in a regular basic event
Definition at line 167 of file NBE.hpp.
GateOp() [1/8]
template<> bool FATAL::FT::NBE::GateOp ()
Definition at line 43 of file MC_GATE_OP.hpp.
References FATAL::FT::BE::get_state().
GateOp() [2/8]
template<> cacBDD::BDD FATAL::FT::NBE::GateOp (boost::shared_ptr< FATAL::DD::dd_mgr< cacBDD::XBDDManager, cacBDD::BDD >> & i_mgr)
Definition at line 78 of file CacBDD_GATEOP.hpp.
GateOp() [3/8]
template<> BDD FATAL::FT::NBE::GateOp (boost::shared_ptr< FATAL::DD::dd_mgr< Cudd, BDD >> & i_mgr)
Definition at line 88 of file CUDD_GATEOP.hpp.
GateOp() [4/8]
template<> std::unordered_set<MCS> FATAL::FT::NBE::GateOp (boost::shared_ptr< BE_DB > & i_DB, double & i_cut_point, int & i_max_num)
Definition at line 88 of file MCS_GATEOP.hpp.
GateOp() [5/8]
template<class return_type > return_type FATAL::FT::NBE::GateOp ()
Definition at line 331 of file GATEOP.hpp.
Referenced by is_negated().
GateOp() [6/8]
template<class return_type , class mgr > return_type FATAL::FT::NBE::GateOp (mgr & i_mgr)
trick to implement virtual template class with two template paramters
Definition at line 337 of file GATEOP.hpp.
GateOp() [7/8]
template<class return_type , class class1 , class class2 > return_type FATAL::FT::NBE::GateOp (class1 & i_class1, class2 & i_class2)
trick to implement virtual template class with three template paramters
Definition at line 346 of file GATEOP.hpp.
GateOp() [8/8]
template<class return_type , class class1 , class class2 , class class3 > return_type FATAL::FT::NBE::GateOp (class1 & i_class1, class2 & i_class2, class3 & i_class3)
trick to implement virtual template class with four template paramters
Definition at line 355 of file GATEOP.hpp.
get_name()
std::string FATAL::FT::NBE::get_name () const inline virtual
access a basic event name
Reimplemented from FATAL::FT::BASE.
Definition at line 103 of file NBE.hpp.
get_prob()
double FATAL::FT::NBE::get_prob () inline
get a probability of success
Returns
a probability of a negated basic event
Definition at line 227 of file NBE.hpp.
References m_BE.
Referenced by depth().
get_ptr()
boost::shared_ptr< FT_BASE > FATAL::FT::NBE::get_ptr ()
a function to get a shared_ptr to a regular basic event
Returns
a shared pointer of a regular type.
Definition at line 197 of file NBE.hpp.
References m_BE.
Referenced by FATAL::FT::BE_DB::AddBE(), and depth().
get_same_type()
boost::shared_ptr< FT_BASE > FATAL::FT::NBE::get_same_type () const virtual
a function to obtain the same type of fault tree gate.
Returns
a shared pointer of the same fault tree type.
Reimplemented from FATAL::FT::FT_BASE.
Definition at line 192 of file NBE.hpp.
Referenced by NBE().
get_state()
bool FATAL::FT::NBE::get_state () inline
Returns
a state of a negate basic evengt
Definition at line 157 of file NBE.hpp.
init() [1/2]
void FATAL::FT::NBE::init () inline
Definition at line 169 of file NBE.hpp.
init() [2/2]
void FATAL::FT::NBE::init (unsigned int seed) inline
Definition at line 170 of file NBE.hpp.
References assign_prob().
is_cyclic() [1/2]
bool FATAL::FT::NBE::is_cyclic () inline virtual
check if cyclic. always false
Returns
false
Reimplemented from FATAL::FT::FT_PROPERTY.
Definition at line 90 of file NBE.hpp.
is_cyclic() [2/2]
bool FATAL::FT::NBE::is_cyclic (const std::vector< boost::shared_ptr< FT_BASE >> & targets) inline
check if cyclic. always false
Returns
false
Definition at line 97 of file NBE.hpp.
is_negated() [1/2]
bool FATAL::FT::NBE::is_negated () const inline virtual
check if this fault tree is negated type
Returns
true if a fault tree is negated. Otherwise false
Reimplemented from FATAL::FT::FT_PROPERTY.
Definition at line 123 of file NBE.hpp.
References GateOp().
is_negated() [2/2]
bool FATAL::FT::NBE::is_negated () inline
check if a fault tree is negated or not. always true
Returns
true
Definition at line 175 of file NBE.hpp.
isBE()
bool FATAL::FT::NBE::isBE () const inline virtual
check if this is a basic event. Always true
Reimplemented from FATAL::FT::FT_PROPERTY.
Definition at line 109 of file NBE.hpp.
isNBE()
bool FATAL::FT::NBE::isNBE () const inline virtual
check if this is a negated basic event. Always true
Returns
true
Reimplemented from FATAL::FT::FT_PROPERTY.
Definition at line 116 of file NBE.hpp.
transform()
boost::shared_ptr<FT_BASE> FATAL::FT::NBE::transform () inline virtual
a function to obtain equivalent gate structure.
Reimplemented from FATAL::FT::FT_BASE.
Definition at line 180 of file NBE.hpp.
Member Data Documentation
m_BE
boost::shared_ptr<BE> FATAL::FT::NBE::m_BE protected
Parameters
shared_ptrt to a regular basic event
Definition at line 42 of file NBE.hpp.
Referenced by get_prob(), get_ptr(), and NBE().
The documentation for this class was generated from the following files:
NBE.hpp
GATEOP.hpp
CacBDD_GATEOP.hpp
CUDD_GATEOP.hpp
MC_GATE_OP.hpp
MCS_GATEOP.hpp
[ FATALPRA Home Page(Not Ready Yet!) ] © 2014–2015, FATALPRA Developer Team.