FATALPRA: FATAL::ET::ET_PROPERTY Class Reference
FATAL::ET::ET_PROPERTY Class Reference
#include <ET_PROPERTY.hpp>
Public Member Functions
ET_PROPERTY ()
ET_PROPERTY (std::string i_evt)
void set_evt (const std::string &i_name)
std::string get_evt ()
virtual ET_TYPE GET_ET_TYPE ()
Detailed Description
a class that defines properties of event trees
Definition at line 33 of file ET_PROPERTY.hpp.
Constructor & Destructor Documentation
ET_PROPERTY() [1/2]
FATAL::ET::ET_PROPERTY::ET_PROPERTY () inline
default constructor
Definition at line 49 of file ET_PROPERTY.hpp.
References rand_string().
ET_PROPERTY() [2/2]
FATAL::ET::ET_PROPERTY::ET_PROPERTY (std::string i_evt) inline
default constructor
Parameters
i_evt event name
Definition at line 58 of file ET_PROPERTY.hpp.
Member Function Documentation
GET_ET_TYPE()
ET_TYPE FATAL::ET::ET_PROPERTY::GET_ET_TYPE () inline virtual
obtain an ET_TYPE
Returns
ET_TYPE::UNDEF
Reimplemented in FATAL::ET::ET_BASE, FATAL::ET::SEQ, FATAL::ET::IE, and FATAL::ET::ET.
Definition at line 83 of file ET_PROPERTY.hpp.
References FATAL::UNDEF.
get_evt()
std::string FATAL::ET::ET_PROPERTY::get_evt () inline
get an event name
Returns
std::string of an event name
Definition at line 73 of file ET_PROPERTY.hpp.
Referenced by FATAL::ET::ET_BASE::print(), and FATAL::ET::IE::print().
set_evt()
void FATAL::ET::ET_PROPERTY::set_evt (const std::string & i_name) inline
assign name
Definition at line 63 of file ET_PROPERTY.hpp.
The documentation for this class was generated from the following file:
ET_PROPERTY.hpp
[ FATALPRA Home Page(Not Ready Yet!) ] © 2014–2015, FATALPRA Developer Team.