FATALPRA: FATAL::MCS Class Reference
FATAL::MCS Class Reference
#include <MCS.hpp>
Public Member Functions
void print (boost::shared_ptr< FT::BE_DB > DB) const
double prob (const boost::shared_ptr< FT::BE_DB > &i_DB) const
size_t hash () const
unsigned int size () const
size_t count ()
~MCS ()
MCS ()
MCS (const MCS &i_MCS)
MCS (const int N)
MCS (const boost::dynamic_bitset<> &i_bitset)
MCS (boost::dynamic_bitset<> &i_bitset)
bool is_subset (const MCS B) const
bool is_subset (const MCS i_MCS)
bool operator== (const MCS &i_MCS) const
bool operator!= (const MCS &i_MCS) const
std::unordered_set< MCS > operator+ (const MCS &i_MCS) const
std::unordered_set< MCS > operator+ (const std::unordered_set< MCS > &Bs) const
MCS operator* (const MCS &i_MCS) const
std::unordered_set< MCS > operator* (const std::unordered_set< MCS > &As) const
bool will_be_remove (const double &cut_point, const boost::shared_ptr< FT::BE_DB > &i_DB) const
bool operator[] (const unsigned int i) const
void set (const unsigned int &i, bool state)
int getN () const
Public Attributes
boost::dynamic_bitset _MCS
Detailed Description
implementation of minimal cut set
Definition at line 63 of file MCS.hpp.
Constructor & Destructor Documentation
~MCS()
FATAL::MCS::~MCS () inline
destructor
Definition at line 126 of file MCS.hpp.
MCS() [1/5]
FATAL::MCS::MCS () inline
default constructor
Definition at line 129 of file MCS.hpp.
MCS() [2/5]
FATAL::MCS::MCS (const MCS & i_MCS) inline
copy constructor
Definition at line 132 of file MCS.hpp.
MCS() [3/5]
FATAL::MCS::MCS (const int N) inline
constructor
Definition at line 135 of file MCS.hpp.
MCS() [4/5]
FATAL::MCS::MCS (const boost::dynamic_bitset<> & i_bitset) inline
constructor from bit set
Definition at line 138 of file MCS.hpp.
MCS() [5/5]
FATAL::MCS::MCS (boost::dynamic_bitset<> & i_bitset) inline
constructor from bit set
Definition at line 141 of file MCS.hpp.
Member Function Documentation
count()
size_t FATAL::MCS::count () inline
obtain number of trues in bit set. Equivalently, this returns number of basic events in MCS.
Definition at line 123 of file MCS.hpp.
Referenced by FATAL::mcs_sort().
getN()
int FATAL::MCS::getN () const inline
Definition at line 214 of file MCS.hpp.
hash()
size_t FATAL::MCS::hash () const inline
compute hash for MCS
Returns
hash of minimal cut set
Definition at line 110 of file MCS.hpp.
Referenced by std::hash< FATAL::MCS >::operator()().
is_subset() [1/2]
bool FATAL::MCS::is_subset (const MCS B) const
this identify A in B -> A + B = A (in terms of MCS. in set theory, A + B = B)
Definition at line 521 of file MCS.hpp.
References _MCS, and size().
is_subset() [2/2]
bool FATAL::MCS::is_subset (const MCS B)
this identify A in B -> A + B = A (in terms of MCS. in set theory, A + B = B)
Definition at line 547 of file MCS.hpp.
References _MCS, and size().
operator!=()
bool FATAL::MCS::operator!= (const MCS & i_MCS) const inline
!= operator for MCS
Definition at line 165 of file MCS.hpp.
References _MCS, and operator+().
operator*() [1/2]
MCS FATAL::MCS::operator* (const MCS & i_MCS) const inline
*operation on MCS
Warning
* operation for MCS is different from set theory
Definition at line 186 of file MCS.hpp.
References _MCS, and operator*().
operator*() [2/2]
std::unordered_set< MCS > FATAL::MCS::operator* (const std::unordered_set< MCS > & As) const
*operation on MCS
Warning
* operation for MCS is different from set theory
Definition at line 381 of file MCS.hpp.
References FATAL::iden_common().
operator+() [1/2]
std::unordered_set< MCS > FATAL::MCS::operator+ (const MCS & i_MCS) const
+operation on MCS
Warning
+ operation for MCS is different from set theory
Definition at line 332 of file MCS.hpp.
References _MCS, and size().
operator+() [2/2]
std::unordered_set< MCS > FATAL::MCS::operator+ (const std::unordered_set< MCS > & Bs) const
+operation on MCS
Warning
+ operation for MCS is different from set theory
Definition at line 438 of file MCS.hpp.
operator==()
bool FATAL::MCS::operator== (const MCS & i_MCS) const inline
== operator for MCS
Definition at line 159 of file MCS.hpp.
References _MCS.
operator[]()
bool FATAL::MCS::operator[] (const unsigned int i) const
access bit of MCS. Since _MCS in public scope, directly access it.
Returns
bit
Definition at line 576 of file MCS.hpp.
print()
void FATAL::MCS::print (boost::shared_ptr< FT::BE_DB > DB) const inline
Definition at line 69 of file MCS.hpp.
prob()
double FATAL::MCS::prob (const boost::shared_ptr< FT::BE_DB > & i_DB) const
obtain probability
Parameters
i_DB a database which holds probability information of basic events
Returns
a probability of minimal cut set
Definition at line 498 of file MCS.hpp.
set()
void FATAL::MCS::set (const unsigned int & i, bool state)
assign a bit to MCS.
Definition at line 317 of file MCS.hpp.
Referenced by FATAL::FT::BE::GateOp().
size()
unsigned int FATAL::MCS::size () const inline
obtain the number of BEs in DB
Returns
a size of MCS
Definition at line 117 of file MCS.hpp.
Referenced by is_subset(), and operator+().
will_be_remove()
bool FATAL::MCS::will_be_remove (const double & cut_point, const boost::shared_ptr< FT::BE_DB > & i_DB) const
check if a minimal cut set should be removed based on probabilistic cut off.
Definition at line 571 of file MCS.hpp.
Member Data Documentation
_MCS
boost::dynamic_bitset FATAL::MCS::_MCS
Parameters
_MCS this represents minimal cut set
Definition at line 95 of file MCS.hpp.
Referenced by is_subset(), operator!=(), operator*(), operator+(), operator==(), and FATAL::FT::BE_DB::prob().
The documentation for this class was generated from the following file:
MCS.hpp
[ FATALPRA Home Page(Not Ready Yet!) ] © 2014–2015, FATALPRA Developer Team.