FATALPRA: FATAL::CCF::alpha< tag > Class Template Reference
FATAL::CCF::alpha< tag > Class Template Reference
#include <alpha.hpp>
Public Member Functions
alpha ()
alpha (const Impact_Vector &IV)
std::vector< double > get_alpha (const unsigned int &CCCG, const double &rho) const
std::vector< double > get_alpha (const unsigned int &CCCG, std::function< const double(std::vector< double >)> rho_functor) const
std::vector< double > get_prob (const double &Q, const std::vector< double > &alphas) const
std::vector< double > get_prob (const double &Q, const unsigned int &CCCG, const double &rho) const
std::vector< double > get_prob (const double &Q, const unsigned int &CCCG, std::function< const double(std::vector< double >)> rho_functor) const
Public Attributes
Impact_Vector _IV
Detailed Description
template<typename tag>
class FATAL::CCF::alpha< tag >
Definition at line 39 of file alpha.hpp.
Constructor & Destructor Documentation
alpha() [1/2]
template<typename tag > FATAL::CCF::alpha< tag >::alpha () inline
Definition at line 73 of file alpha.hpp.
alpha() [2/2]
template<typename tag > FATAL::CCF::alpha< tag >::alpha (const Impact_Vector & IV) inline
Definition at line 75 of file alpha.hpp.
Member Function Documentation
get_alpha() [1/2]
template<typename tag > std::vector<double> FATAL::CCF::alpha< tag >::get_alpha (const unsigned int & CCCG, const double & rho) const inline
Definition at line 77 of file alpha.hpp.
References FATAL::CCF::Impact_Vector::getImpactVector().
Referenced by FATAL::CCF::alpha< tag >::get_prob().
get_alpha() [2/2]
template<typename tag > std::vector<double> FATAL::CCF::alpha< tag >::get_alpha (const unsigned int & CCCG, std::function< const double(std::vector< double >)> rho_functor) const inline
Definition at line 92 of file alpha.hpp.
References FATAL::CCF::Impact_Vector::getImpactVector().
get_prob() [1/3]
template<typename tag > std::vector<double> FATAL::CCF::alpha< tag >::get_prob (const double & Q, const std::vector< double > & alphas) const inline
Definition at line 107 of file alpha.hpp.
Referenced by FATAL::CCF::alpha< tag >::get_prob().
get_prob() [2/3]
template<typename tag > std::vector<double> FATAL::CCF::alpha< tag >::get_prob (const double & Q, const unsigned int & CCCG, const double & rho) const inline
Definition at line 122 of file alpha.hpp.
References FATAL::CCF::alpha< tag >::get_alpha().
get_prob() [3/3]
template<typename tag > std::vector<double> FATAL::CCF::alpha< tag >::get_prob (const double & Q, const unsigned int & CCCG, std::function< const double(std::vector< double >)> rho_functor) const inline
Definition at line 129 of file alpha.hpp.
References FATAL::CCF::alpha< tag >::get_alpha(), and FATAL::CCF::alpha< tag >::get_prob().
Member Data Documentation
_IV
template<typename tag > Impact_Vector FATAL::CCF::alpha< tag >::_IV
Definition at line 71 of file alpha.hpp.
The documentation for this class was generated from the following file:
alpha.hpp
[ FATALPRA Home Page(Not Ready Yet!) ] © 2014–2015, FATALPRA Developer Team.