FATALPRA: FATAL Namespace Reference
FATAL Namespace Reference
Probabilistic Risk Assessment Library.
Namespaces
CCF
DD
a set of classes for Decision Diagram comparison
ET
a set of classes for event tree manipulation
Exception
a set of classes for exception handling in FATAL
FT
a set of classes for fault tree manipulation
Functor
a functor class for probabilistic distribution
io
Matrix
misc
multi
prob
utils
a utility class for probabilistic distribution
Classes
struct capacity
struct correlated
class correlated_randoms
class dist_interface
class global_vars
class mat_gen
class mc_mgr
class MCS
class mcs_compare
class MCS_MGR
an implementation of minimal cut set manager
struct non_correlated
struct non_permutable_pair
struct permutable_pair
struct response
Typedefs
using gamma = dist_interface< boost::math::gamma_distribution<>, boost::random::gamma_distribution<> >
using normal = dist_interface< boost::math::normal_distribution<>, boost::random::normal_distribution<> >
using lnorm = dist_interface< boost::math::lognormal_distribution<>, boost::random::lognormal_distribution<> >
using uniform = dist_interface< boost::math::uniform_distribution<>, boost::random::uniform_real_distribution<> >
using weibull = dist_interface< boost::math::weibull_distribution<>, boost::random::weibull_distribution<> >
using logitnorm = dist_interface< prob::logit_normal, prob::logit_normal_random >
typedef int mc
typedef double hmc
Enumerations
enum OS { OS::MAC, OS::WINDOWS, OS::LINUX, OS::UNDEF }
enum CD_SEQ {
CD_SEQ::FIRST = -1, CD_SEQ::OK, CD_SEQ::TQUV, CD_SEQ::TQUX,
CD_SEQ::TQU, CD_SEQ::TX, CD_SEQ::TBW, CD_SEQ::TB,
CD_SEQ::TBD, CD_SEQ::TBU, CD_SEQ::TW, CD_SEQ::TC,
CD_SEQ::IC, CD_SEQ::LOCA, CD_SEQ::SIF, CD_SEQ::V,
CD_SEQ::AE, CD_SEQ::AUV, CD_SEQ::C, CD_SEQ::W,
CD_SEQ::QUV, CD_SEQ::QUX, CD_SEQ::CD, CD_SEQ::UNDEF,
CD_SEQ::END
}
enum FATAL_DIST_TYPE {
FATAL_DIST_TYPE::LOGNORMAL, FATAL_DIST_TYPE::NORMAL, FATAL_DIST_TYPE::BETA, FATAL_DIST_TYPE::GAMMA,
FATAL_DIST_TYPE::HAZARD, FATAL_DIST_TYPE::UNIFORM, FATAL_DIST_TYPE::FIX
}
enum class for defining probability distribution type.
enum FATAL_FAILURE_TYPE {
FATAL_FAILURE_TYPE::REPAIRABLE_COMPONENT = 1, FATAL_FAILURE_TYPE::PERIODIC_TESTING = 2, FATAL_FAILURE_TYPE::DEMAND_FAILURE = 3, FATAL_FAILURE_TYPE::FAIL_TO_RUN = 4,
FATAL_FAILURE_TYPE::MODULAR = 5, FATAL_FAILURE_TYPE::NON_REPAIRABLE = 6, FATAL_FAILURE_TYPE::FRAGILITY = 7
}
enum class for failure types defined in FATAL
enum ET_TYPE { ET_TYPE::UNDEF = -1, ET_TYPE::ET, ET_TYPE::IE, ET_TYPE::SEQ }
enum class for event tree type.
enum FT_TYPE {
FT_TYPE::BE, FT_TYPE::NBE, FT_TYPE::AND, FT_TYPE::NAND,
FT_TYPE::OR, FT_TYPE::NOR, FT_TYPE::KN, FT_TYPE::NKN,
FT_TYPE::CND, FT_TYPE::XOR, FT_TYPE::XNOR, FT_TYPE::LT,
FT_TYPE::LTE, FT_TYPE::GT, FT_TYPE::GTE, FT_TYPE::ITE,
FT_TYPE::NOT, FT_TYPE::UNDEF
}
enum class for fault tree type.
Functions
template<typename random_dist = lnorm>
random_dist initialize (const std::vector< double > &param)
OS _get_os ()
double kn (const int &k, std::vector< double >::iterator begin, std::vector< double >::iterator end, const int &i)
std::string to_lower (const std::string &i_string)
long combination (const int &n, const int &k)
template<class ReturnVal , typename TmpVal , typename ReturnManip , typename Initializer , typename Functor1 , typename Functor2 , typename Container >
void combinations (ReturnVal &val, TmpVal &val_tmp, ReturnManip Manip, unsigned int k, unsigned int m, Initializer init, Functor1 func1, Functor2 func2, Container container)
std::string id2str (const ET_TYPE &i_type)
std::string id2str (const FT_TYPE &i_type)
std::string id2str (const CD_SEQ &i_type)
CD_SEQ str2id (const std::string &i_type)
void remove_num (std::unordered_set< FATAL::MCS > &return_val, const unsigned int &max_num_mcs, boost::shared_ptr< FT::BE_DB > &i_DB)
void remove (std::unordered_set< FATAL::MCS > &i_MCS, const double &cut_point, const boost::shared_ptr< FT::BE_DB > &i_DB)
boost::dynamic_bitset iden_common (const std::unordered_set< FATAL::MCS > &left, const std::unordered_set< FATAL::MCS > &right)
bool mcs_sort (FATAL::MCS i, FATAL::MCS j)
std::unordered_set< FATAL::MCS > conjunction (const std::unordered_set< FATAL::MCS > &As, const std::unordered_set< FATAL::MCS > &Bs, boost::shared_ptr< FATAL::FT::BE_DB > i_DB=nullptr, unsigned int max_num_mcs=10000, double cut_point=0)
std::unordered_set< FATAL::MCS > disjunction (const std::unordered_set< FATAL::MCS > &left, const std::unordered_set< FATAL::MCS > &right, boost::shared_ptr< FATAL::FT::BE_DB > i_DB=nullptr, unsigned int max_num_mcs=10000, double cut_point=0)
(MCS + MCS + ... MCS) + (MCS + MCS + ... MCS)
std::unordered_set< FATAL::MCS > mcs_kn (const int &k, std::vector< std::unordered_set< FATAL::MCS >>::iterator begin, const int &i, const double trnct_point, const int max_mcs)
void version ()
void getLisenceInfo ()
Variables
const bool SUCCESS = true
const bool FAILURE = false
const std::string MAJOR_VERSION = "1"
const std::string MINOR_VERSION = "1"
const std::string PATCH_VERSION = "0"
const std::string DEVELOP_STATUS ="Release"
const std::string RELEASE_YEAR = "2015-2018"
const std::string COMPANY_NAME ="Central Research Institute of Electric Power Industry"
const std::string Primary_AUTHORS = "S. SOGA"
Detailed Description
Probabilistic Risk Assessment Library.
Probabilistic Risk Assessment Library.
namespace for FATALPRA
Typedef Documentation
gamma
using FATAL::gamma = typedef dist_interface <boost::math::gamma_distribution<>, boost::random::gamma_distribution<> >
Definition at line 193 of file PROB_INTERFACE.hpp.
hmc
typedef double FATAL::hmc
Definition at line 42 of file MC_BASE.hpp.
lnorm
using FATAL::lnorm = typedef dist_interface <boost::math::lognormal_distribution<>, boost::random::lognormal_distribution<> >
Definition at line 195 of file PROB_INTERFACE.hpp.
logitnorm
using FATAL::logitnorm = typedef dist_interface < prob::logit_normal, prob::logit_normal_random >
Definition at line 198 of file PROB_INTERFACE.hpp.
mc
typedef int FATAL::mc
Definition at line 41 of file MC_BASE.hpp.
normal
using FATAL::normal = typedef dist_interface <boost::math::normal_distribution<>, boost::random::normal_distribution<> >
Definition at line 194 of file PROB_INTERFACE.hpp.
uniform
using FATAL::uniform = typedef dist_interface <boost::math::uniform_distribution<>, boost::random::uniform_real_distribution<> >
Definition at line 196 of file PROB_INTERFACE.hpp.
weibull
using FATAL::weibull = typedef dist_interface <boost::math::weibull_distribution<>, boost::random::weibull_distribution<> >
Definition at line 197 of file PROB_INTERFACE.hpp.
Enumeration Type Documentation
CD_SEQ
enum FATAL::CD_SEQ strong
Enumerator
FIRST
this must be always at the first
OK
TQUV
TQUX
TQU
TX
TBW
TB
TBD
TBU
TW
TC
IC
LOCA
SIF
V
AE
AUV
Equivalent to AE
C
W
QUV
QUX
CD
UNDEF
not defined in FATAL
END
this must be placed at the end. This is used to count how many CD sequences are defined in FATAL
Definition at line 31 of file new_enum.hpp.
ET_TYPE
enum FATAL::ET_TYPE strong
enum class for event tree type.
Enumerator
UNDEF
not defined
ET
basic event tree
IE
initiating event
SEQ
terminal sequence
Definition at line 133 of file new_enum.hpp.
FATAL_DIST_TYPE
enum FATAL::FATAL_DIST_TYPE strong
enum class for defining probability distribution type.
Enumerator
LOGNORMAL
Lognormal distribution
NORMAL
normal distribution
BETA
beta distribution
GAMMA
gamma distribution
HAZARD
hazard curse such as fragility curve
UNIFORM
uniform distribution
FIX
fixed probability
Definition at line 89 of file new_enum.hpp.
FATAL_FAILURE_TYPE
enum FATAL::FATAL_FAILURE_TYPE strong
enum class for failure types defined in FATAL
Enumerator
REPAIRABLE_COMPONENT
repairable failure
PERIODIC_TESTING
periodic maintenance failure
DEMAND_FAILURE
demand failure
FAIL_TO_RUN
fail to run
MODULAR
Modular
NON_REPAIRABLE
Non-Repairable
FRAGILITY
Fragility
Definition at line 111 of file new_enum.hpp.
FT_TYPE
enum FATAL::FT_TYPE strong
enum class for fault tree type.
Enumerator
BE
Basic Event
NBE
Basic Event
AND
and gate
NAND
negated and gate
OR
or gate
NOR
negated OR gate
KN
K out of N gate
NKN
Negated K out N gate.
CND
conditional gate.
XOR
XOR gate.
XNOR
XNOR gate
LT
Less than
LTE
Less than equal
GT
Greater than
GTE
Greater than equal
ITE
ITE
NOT
negation
UNDEF
UNDEF
Definition at line 148 of file new_enum.hpp.
OS
enum FATAL::OS strong
Enumerator
MAC
WINDOWS
LINUX
UNDEF
Definition at line 21 of file detect_platform.hpp.
Function Documentation
_get_os()
OS FATAL::_get_os ()
Definition at line 30 of file detect_platform.hpp.
References LINUX, MAC, UNDEF, and WINDOWS.
combination()
long FATAL::combination (const int & n, const int & k)
Definition at line 45 of file math.hpp.
Referenced by FATAL::CCF::Datum::coef(), FATAL::CCF::Datum::MapUp(), FATAL::CCF::Datum::probability_lower(), and FATAL::CCF::Datum::probability_same().
combinations()
template<class ReturnVal , typename TmpVal , typename ReturnManip , typename Initializer , typename Functor1 , typename Functor2 , typename Container > void FATAL::combinations (ReturnVal & val, TmpVal & val_tmp, ReturnManip Manip, unsigned int k, unsigned int m, Initializer init, Functor1 func1, Functor2 func2, Container container)
Definition at line 61 of file math.hpp.
References FATAL::CCF::func1, FATAL::CCF::func2, and FATAL::CCF::init.
Referenced by FATAL::CCF::Datum::_F(), and FATAL::CCF::Combinations::getAllCombintions().
conjunction()
std::unordered_set< FATAL::MCS > FATAL::conjunction (const std::unordered_set< FATAL::MCS > & As, const std::unordered_set< FATAL::MCS > & Bs, boost::shared_ptr< FATAL::FT::BE_DB > i_DB = nullptr, unsigned int max_num_mcs = 10000, double cut_point = 0)
Definition at line 663 of file MCS.hpp.
References mcs_sort(), remove(), and remove_num().
Referenced by mcs_sort(), and operator*().
disjunction()
std::unordered_set< FATAL::MCS > FATAL::disjunction (const std::unordered_set< FATAL::MCS > & left, const std::unordered_set< FATAL::MCS > & right, boost::shared_ptr< FATAL::FT::BE_DB > i_DB = nullptr, unsigned int max_num_mcs = 10000, double cut_point = 0)
(MCS + MCS + ... MCS) + (MCS + MCS + ... MCS)
Definition at line 796 of file MCS.hpp.
References iden_common(), remove(), and remove_num().
Referenced by mcs_sort(), and operator+().
getLisenceInfo()
void FATAL::getLisenceInfo ()
Definition at line 74 of file version.hpp.
id2str() [1/3]
std::string FATAL::id2str (const ET_TYPE & i_type)
a function to convert ET_TYPE to std::string.
You need to update this function if you add ET_TYPE
Parameters
[in] i_type input ET_TYPE
Returns
std::string of ET_TYPE
Definition at line 197 of file new_enum.hpp.
References ET, IE, and SEQ.
Referenced by FATAL::misc::FT_I::FT_I(), FATAL::misc::FT_O::generate_file(), FATAL::ET::SEQ::id2str(), and operator<<().
id2str() [2/3]
std::string FATAL::id2str (const FT_TYPE & i_type)
a function to convert FT_TYPE to std::string.
You need to update this function if you add FT_TYPE
Parameters
[in] i_type input FT_TYPE
Returns
std::string of FT_TYPE
Definition at line 225 of file new_enum.hpp.
References AND, BE, CND, GT, GTE, KN, LT, LTE, NAND, NBE, NKN, NOR, NOT, OR, UNDEF, XNOR, and XOR.
id2str() [3/3]
std::string FATAL::id2str (const CD_SEQ & i_type)
a function to convert CD_SEQ to std::string.
You need to update this function if you add CD_SEQ
Parameters
[in] i_type input CD_SEQ
Returns
std::string of CD_SEQ
Todo:
fix this to throw an error
Definition at line 308 of file new_enum.hpp.
References AE, AUV, C, CD, IC, LOCA, OK, QUV, QUX, SIF, TB, TBD, TBU, TBW, TC, TQU, TQUV, TQUX, TW, TX, UNDEF, V, and W.
iden_common()
boost::dynamic_bitset FATAL::iden_common (const std::unordered_set< FATAL::MCS > & left, const std::unordered_set< FATAL::MCS > & right)
Definition at line 647 of file MCS.hpp.
Referenced by disjunction(), std::hash< FATAL::MCS >::operator()(), and FATAL::MCS::operator*().
initialize()
template<typename random_dist = lnorm> random_dist FATAL::initialize (const std::vector< double > & param)
Definition at line 208 of file PROB_INTERFACE.hpp.
kn()
double FATAL::kn (const int & k, std::vector< double >::iterator begin, std::vector< double >::iterator end, const int & i)
a function to compute kn_gate
Parameters
k number of failures
[in] begin an iterator for first element
[in] end an iterator for last element
[in] i a size of vector<double>
Returns
approximated value for KN gate.
Definition at line 30 of file KN_MC.hpp.
Referenced by FATAL::FT::KN::GateOp(), and FATAL::FT::NKN::GateOp().
mcs_kn()
std::unordered_set< FATAL::MCS > FATAL::mcs_kn (const int & k, std::vector< std::unordered_set< FATAL::MCS >>::iterator begin, const int & i, const double trnct_point, const int max_mcs)
compute K/N gate for minimal cut sets
Parameters
k a number of failures
begin an iterator to a vector of MCSs
i number of remaining sets of minimal cut sets
trnct_point a value of probability cut off point
number of maximum cut sets
Returns
a set of minimal cut sets a function to compute kn_gate
Definition at line 484 of file MCS_GATEOP.hpp.
References FATAL::FT::FT_BASE::begin().
Referenced by FATAL::FT::KN::GateOp().
mcs_sort()
bool FATAL::mcs_sort (FATAL::MCS i, FATAL::MCS j)
Definition at line 264 of file MCS.hpp.
References conjunction(), FATAL::MCS::count(), and disjunction().
Referenced by conjunction().
remove()
void FATAL::remove (std::unordered_set< FATAL::MCS > & i_MCS, const double & cut_point, const boost::shared_ptr< FT::BE_DB > & i_DB)
Definition at line 626 of file MCS.hpp.
Referenced by conjunction(), and disjunction().
remove_num()
void FATAL::remove_num (std::unordered_set< FATAL::MCS > & return_val, const unsigned int & max_num_mcs, boost::shared_ptr< FT::BE_DB > & i_DB)
Definition at line 608 of file MCS.hpp.
Referenced by conjunction(), disjunction(), and std::hash< FATAL::MCS >::operator()().
str2id()
CD_SEQ FATAL::str2id (const std::string & i_type)
Todo:
fix this to throw an error
Definition at line 412 of file new_enum.hpp.
References AE, AUV, C, CD, IC, LOCA, OK, QUV, QUX, SIF, TB, TBD, TBU, TBW, TC, TQU, TQUV, TQUX, TW, TX, UNDEF, V, and W.
to_lower()
std::string FATAL::to_lower (const std::string & i_string)
Definition at line 22 of file manip_string.hpp.
Referenced by FATAL::FT::BE_DB::check_mc().
version()
void FATAL::version ()
Definition at line 53 of file version.hpp.
Variable Documentation
COMPANY_NAME
const std::string FATAL::COMPANY_NAME ="Central Research Institute of Electric Power Industry"
the name of publisher
Definition at line 48 of file version.hpp.
DEVELOP_STATUS
const std::string FATAL::DEVELOP_STATUS ="Release"
Development Status
Definition at line 42 of file version.hpp.
FAILURE
const bool FATAL::FAILURE = false
Definition at line 36 of file MACRO.hpp.
MAJOR_VERSION
const std::string FATAL::MAJOR_VERSION = "1"
Major version number for FATAL package
Definition at line 33 of file version.hpp.
MINOR_VERSION
const std::string FATAL::MINOR_VERSION = "1"
Minor version number for FATAL package
Definition at line 36 of file version.hpp.
PATCH_VERSION
const std::string FATAL::PATCH_VERSION = "0"
Patch version for FATAL package
Definition at line 39 of file version.hpp.
Primary_AUTHORS
const std::string FATAL::Primary_AUTHORS = "S. SOGA"
how made this library
Definition at line 51 of file version.hpp.
RELEASE_YEAR
const std::string FATAL::RELEASE_YEAR = "2015-2018"
release year of current version
Definition at line 45 of file version.hpp.
SUCCESS
const bool FATAL::SUCCESS = true
Definition at line 35 of file MACRO.hpp.
[ FATALPRA Home Page(Not Ready Yet!) ] © 2014–2015, FATALPRA Developer Team.