FATALPRA: FATAL::mc_mgr< mc_type > Class Template Reference
FATAL::mc_mgr< mc_type > Class Template Reference
#include <MC_BASE.hpp>
Public Member Functions
void clear ()
virtual ~mc_mgr ()
mc_mgr ()=delete
mc_mgr (const boost::shared_ptr< FT::FT_BASE > &i_target)
void init ()
std::vector< std::vector< int > > gen_dagger (const int &num)
void reapply (unsigned int num, const boost::shared_ptr< FT::BE_DB > &i_DB=nullptr)
void apply (unsigned int num, const boost::shared_ptr< FT::BE_DB > &i_DB=nullptr)
double mean ()
double var ()
double MCSE ()
void mem ()
void getBE (const boost::shared_ptr< FT::FT_BASE > &i_FT)
void getBE (const boost::shared_ptr< FT::FT_BASE > &i_FT, std::map< boost::shared_ptr< FT::BE >, int > &counter)
template<>
void getBE (const boost::shared_ptr< FT::FT_BASE > &i_FT)
template<>
double mean ()
template<>
double var ()
template<>
void reapply (unsigned int num, const boost::shared_ptr< FT::BE_DB > &i_DB)
Protected Attributes
boost::shared_ptr< FT::FT_BASE > target
std::vector< boost::shared_ptr< FT::FT_BASE > > BEs
std::vector< double > probs
mc_type _mean
mc_type _var
unsigned int _trial
Detailed Description
template<typename mc_type = mc>
class FATAL::mc_mgr< mc_type >
Definition at line 46 of file MC_BASE.hpp.
Constructor & Destructor Documentation
~mc_mgr()
template<typename mc_type = mc> virtual FATAL::mc_mgr< mc_type >::~mc_mgr () inline virtual
destructor
Definition at line 77 of file MC_BASE.hpp.
References FATAL::mc_mgr< mc_type >::apply(), FATAL::mc_mgr< mc_type >::gen_dagger(), FATAL::mc_mgr< mc_type >::getBE(), FATAL::mc_mgr< mc_type >::init(), FATAL::mc_mgr< mc_type >::mc_mgr(), FATAL::mc_mgr< mc_type >::MCSE(), FATAL::mc_mgr< mc_type >::mean(), FATAL::mc_mgr< mc_type >::mem(), FATAL::mc_mgr< mc_type >::reapply(), and FATAL::mc_mgr< mc_type >::var().
mc_mgr() [1/2]
template<typename mc_type = mc> FATAL::mc_mgr< mc_type >::mc_mgr () delete
constructor deleted
Referenced by FATAL::mc_mgr< mc_type >::~mc_mgr().
mc_mgr() [2/2]
template<typename mc_type > FATAL::mc_mgr< mc_type >::mc_mgr (const boost::shared_ptr< FT::FT_BASE > & i_target)
default constructor. Assume FT as default. this constructor covors mc and hmc for FT_BASE
Definition at line 169 of file MC_BASE.hpp.
References CHECKNULL, and FATAL::mc_mgr< mc_type >::init().
Member Function Documentation
apply()
template<typename mc_type > void FATAL::mc_mgr< mc_type >::apply (unsigned int num, const boost::shared_ptr< FT::BE_DB > & i_DB = nullptr)
run monte carlo sampling
Warning
this reset the statisitics
See also
void reapply(unsigned int num)
Definition at line 477 of file MC_BASE.hpp.
References FATAL::mc_mgr< mc_type >::clear(), FATAL::mc_mgr< mc_type >::init(), and FATAL::mc_mgr< mc_type >::reapply().
Referenced by FATAL::mc_mgr< mc_type >::~mc_mgr().
clear()
template<typename mc_type > void FATAL::mc_mgr< mc_type >::clear ()
Definition at line 158 of file MC_BASE.hpp.
References FATAL::mc_mgr< mc_type >::_mean, FATAL::mc_mgr< mc_type >::_trial, FATAL::mc_mgr< mc_type >::_var, FATAL::mc_mgr< mc_type >::BEs, and FATAL::mc_mgr< mc_type >::probs.
Referenced by FATAL::mc_mgr< mc_type >::apply().
gen_dagger()
template<typename mc_type > std::vector< std::vector< int > > FATAL::mc_mgr< mc_type >::gen_dagger (const int & num)
Definition at line 361 of file MC_BASE.hpp.
References FATAL::mc_mgr< mc_type >::probs.
Referenced by FATAL::mc_mgr< mc_type >::reapply(), and FATAL::mc_mgr< mc_type >::~mc_mgr().
getBE() [1/3]
template<typename mc_type > void FATAL::mc_mgr< mc_type >::getBE (const boost::shared_ptr< FT::FT_BASE > & i_FT)
Definition at line 287 of file MC_BASE.hpp.
References FATAL::mc_mgr< mc_type >::BEs, and CHECKZERO.
Referenced by FATAL::mc_mgr< mc_type >::getBE(), FATAL::mc_mgr< mc_type >::init(), and FATAL::mc_mgr< mc_type >::~mc_mgr().
getBE() [2/3]
template<typename mc_type > void FATAL::mc_mgr< mc_type >::getBE (const boost::shared_ptr< FT::FT_BASE > & i_FT, std::map< boost::shared_ptr< FT::BE >, int > & counter)
Definition at line 320 of file MC_BASE.hpp.
References CHECKZERO, and FATAL::mc_mgr< mc_type >::getBE().
getBE() [3/3]
template<> void FATAL::mc_mgr< hmc >::getBE (const boost::shared_ptr< FT::FT_BASE > & i_FT)
Definition at line 185 of file MC_BASE.hpp.
References FATAL::mc_mgr< mc_type >::BEs, and FATAL::mc_mgr< mc_type >::getBE().
init()
template<typename mc_type > void FATAL::mc_mgr< mc_type >::init ()
construct lookup table for BE status from FT
Definition at line 176 of file MC_BASE.hpp.
References FATAL::mc_mgr< mc_type >::getBE(), FATAL::mc_mgr< mc_type >::mem(), and FATAL::mc_mgr< mc_type >::target.
Referenced by FATAL::mc_mgr< mc_type >::apply(), FATAL::mc_mgr< mc_type >::mc_mgr(), and FATAL::mc_mgr< mc_type >::~mc_mgr().
MCSE()
template<typename mc_type > double FATAL::mc_mgr< mc_type >::MCSE ()
a function to compute variance
Returns
monte carlo standard error
Definition at line 500 of file MC_BASE.hpp.
References FATAL::mc_mgr< mc_type >::_trial, and FATAL::mc_mgr< mc_type >::var().
Referenced by FATAL::mc_mgr< mc_type >::~mc_mgr().
mean() [1/2]
template<typename mc_type > double FATAL::mc_mgr< mc_type >::mean ()
a function to compute mean value
Returns
mean value
Definition at line 486 of file MC_BASE.hpp.
References FATAL::mc_mgr< mc_type >::_mean, and FATAL::mc_mgr< mc_type >::_trial.
Referenced by FATAL::mc_mgr< mc_type >::var(), and FATAL::mc_mgr< mc_type >::~mc_mgr().
mean() [2/2]
template<> double FATAL::mc_mgr< hmc >::mean ()
Definition at line 207 of file MC_BASE.hpp.
References FATAL::mc_mgr< mc_type >::_mean, and FATAL::mc_mgr< mc_type >::_trial.
mem()
template<typename mc_type > void FATAL::mc_mgr< mc_type >::mem ()
memorize probability of each basic event
Definition at line 506 of file MC_BASE.hpp.
References FATAL::mc_mgr< mc_type >::BEs, and FATAL::mc_mgr< mc_type >::probs.
Referenced by FATAL::mc_mgr< mc_type >::init(), and FATAL::mc_mgr< mc_type >::~mc_mgr().
reapply() [1/2]
template<typename mc_type > void FATAL::mc_mgr< mc_type >::reapply (unsigned int num, const boost::shared_ptr< FT::BE_DB > & i_DB = nullptr)
add more monte carlo trial for estimate
Definition at line 407 of file MC_BASE.hpp.
References FATAL::mc_mgr< mc_type >::_mean, FATAL::mc_mgr< mc_type >::_trial, FATAL::mc_mgr< mc_type >::BEs, FATAL::mc_mgr< mc_type >::gen_dagger(), FATAL::mc_mgr< mc_type >::probs, and FATAL::mc_mgr< mc_type >::target.
Referenced by FATAL::mc_mgr< mc_type >::apply(), and FATAL::mc_mgr< mc_type >::~mc_mgr().
reapply() [2/2]
template<> void FATAL::mc_mgr< hmc >::reapply (unsigned int num, const boost::shared_ptr< FT::BE_DB > & i_DB)
Definition at line 223 of file MC_BASE.hpp.
References FATAL::mc_mgr< mc_type >::_mean, FATAL::mc_mgr< mc_type >::_trial, FATAL::mc_mgr< mc_type >::_var, FATAL::mc_mgr< mc_type >::BEs, FATAL::mc_mgr< mc_type >::gen_dagger(), FATAL::mc_mgr< mc_type >::probs, and FATAL::mc_mgr< mc_type >::target.
var() [1/2]
template<typename mc_type > double FATAL::mc_mgr< mc_type >::var ()
a function to compute variance
Returns
variance
Definition at line 493 of file MC_BASE.hpp.
References FATAL::mc_mgr< mc_type >::mean().
Referenced by FATAL::mc_mgr< mc_type >::MCSE(), and FATAL::mc_mgr< mc_type >::~mc_mgr().
var() [2/2]
template<> double FATAL::mc_mgr< hmc >::var ()
Definition at line 214 of file MC_BASE.hpp.
References FATAL::mc_mgr< mc_type >::_trial, FATAL::mc_mgr< mc_type >::_var, and FATAL::mc_mgr< mc_type >::mean().
Member Data Documentation
_mean
template<typename mc_type = mc> mc_type FATAL::mc_mgr< mc_type >::_mean protected
Definition at line 64 of file MC_BASE.hpp.
Referenced by FATAL::mc_mgr< mc_type >::clear(), FATAL::mc_mgr< mc_type >::mean(), and FATAL::mc_mgr< mc_type >::reapply().
_trial
template<typename mc_type = mc> unsigned int FATAL::mc_mgr< mc_type >::_trial protected
Definition at line 68 of file MC_BASE.hpp.
Referenced by FATAL::mc_mgr< mc_type >::clear(), FATAL::mc_mgr< mc_type >::MCSE(), FATAL::mc_mgr< mc_type >::mean(), FATAL::mc_mgr< mc_type >::reapply(), and FATAL::mc_mgr< mc_type >::var().
_var
template<typename mc_type = mc> mc_type FATAL::mc_mgr< mc_type >::_var protected
Definition at line 66 of file MC_BASE.hpp.
Referenced by FATAL::mc_mgr< mc_type >::clear(), FATAL::mc_mgr< mc_type >::reapply(), and FATAL::mc_mgr< mc_type >::var().
BEs
template<typename mc_type = mc> std::vector<boost::shared_ptr<FT::FT_BASE> > FATAL::mc_mgr< mc_type >::BEs protected
Definition at line 58 of file MC_BASE.hpp.
Referenced by FATAL::mc_mgr< mc_type >::clear(), FATAL::mc_mgr< mc_type >::getBE(), FATAL::mc_mgr< mc_type >::mem(), and FATAL::mc_mgr< mc_type >::reapply().
probs
template<typename mc_type = mc> std::vector<double> FATAL::mc_mgr< mc_type >::probs protected
Definition at line 61 of file MC_BASE.hpp.
Referenced by FATAL::mc_mgr< mc_type >::clear(), FATAL::mc_mgr< mc_type >::gen_dagger(), FATAL::mc_mgr< mc_type >::mem(), and FATAL::mc_mgr< mc_type >::reapply().
target
template<typename mc_type = mc> boost::shared_ptr<FT::FT_BASE> FATAL::mc_mgr< mc_type >::target protected
Definition at line 55 of file MC_BASE.hpp.
Referenced by FATAL::mc_mgr< mc_type >::init(), and FATAL::mc_mgr< mc_type >::reapply().
The documentation for this class was generated from the following file:
MC_BASE.hpp
[ FATALPRA Home Page(Not Ready Yet!) ] © 2014–2015, FATALPRA Developer Team.