FATALPRA: FATAL::Functor::mission_time< Dist_Info1 > Class Template Reference
FATAL::Functor::mission_time< Dist_Info1 > Class Template Reference
#include <FixedMissionTime.hpp>
Public Member Functions
mission_time ()=delete
mission_time (const std::vector< double > &param1, const double &time)
virtual ~mission_time ()
double previous ()
double operator() ()
double mean ()
double median ()
double _5th ()
double _95th ()
double operator() (double time)
double mean (double time)
double median (double time)
double _5th (double time)
double _95th (double time)
Public Member Functions inherited from FATAL::Functor::BE_FUNCTOR_BASE
virtual bool is_corr ()
virtual int order ()
virtual bool is_mc_type ()
virtual ~BE_FUNCTOR_BASE ()
virtual FATAL::FATAL_FAILURE_TYPE get_type ()
virtual void set (const int &_index, const int &_unit_number)
virtual bool get_state (const int &trial)
BE_FUNCTOR_BASE ()
BE_FUNCTOR_BASE (const FATAL::FATAL_FAILURE_TYPE &i_type)
template<class T >
boost::shared_ptr< T > upcast ()
double prob (const int &i_int)
Detailed Description
template<class Dist_Info1>
class FATAL::Functor::mission_time< Dist_Info1 >
a class which is a base class for basic event computation
Template Parameters
Dist_Info1 a template parameter of a distribution type
Dist_Info2 a template parameter of a distribution type
Definition at line 41 of file FixedMissionTime.hpp.
Constructor & Destructor Documentation
mission_time() [1/2]
template<class Dist_Info1 > FATAL::Functor::mission_time< Dist_Info1 >::mission_time () delete
default constructor deleted
mission_time() [2/2]
template<class Dist_Info1 > FATAL::Functor::mission_time< Dist_Info1 >::mission_time (const std::vector< double > & param1, const double & time)
Definition at line 108 of file FixedMissionTime.hpp.
References FATAL::FAIL_TO_RUN.
~mission_time()
template<class Dist_Info1 > virtual FATAL::Functor::mission_time< Dist_Info1 >::~mission_time () inline virtual
default destructor
Definition at line 78 of file FixedMissionTime.hpp.
Member Function Documentation
_5th() [1/2]
template<class Dist_Info1 > double FATAL::Functor::mission_time< Dist_Info1 >::_5th () virtual
a function to obtain 5th percentile from distribution
Returns
a 5th percentile of failure
Implements FATAL::Functor::BE_FUNCTOR_BASE.
Definition at line 143 of file FixedMissionTime.hpp.
Referenced by FATAL::Functor::mission_time< Dist_Info1 >::previous().
_5th() [2/2]
template<class Dist_Info1 > double FATAL::Functor::mission_time< Dist_Info1 >::_5th (double time) virtual
a function to obtain 5th percentile from distribution at given time
Parameters
time time passed
Returns
a 5th percentile of failure
Implements FATAL::Functor::BE_FUNCTOR_BASE.
Definition at line 192 of file FixedMissionTime.hpp.
_95th() [1/2]
template<class Dist_Info1 > double FATAL::Functor::mission_time< Dist_Info1 >::_95th () virtual
a function to obtain 95th percentile from distribution
Returns
a 95th percentile of failure
Implements FATAL::Functor::BE_FUNCTOR_BASE.
Definition at line 153 of file FixedMissionTime.hpp.
Referenced by FATAL::Functor::mission_time< Dist_Info1 >::previous().
_95th() [2/2]
template<class Dist_Info1 > double FATAL::Functor::mission_time< Dist_Info1 >::_95th (double time) virtual
a function to obtain random probability from distribution at given time
Parameters
time time passed
Returns
a 95th percentile of failure
Implements FATAL::Functor::BE_FUNCTOR_BASE.
Definition at line 202 of file FixedMissionTime.hpp.
mean() [1/2]
template<class Dist_Info1 > double FATAL::Functor::mission_time< Dist_Info1 >::mean () virtual
a function to obtain mean value from distribution
Returns
a mean probability of failure
Implements FATAL::Functor::BE_FUNCTOR_BASE.
Definition at line 123 of file FixedMissionTime.hpp.
Referenced by FATAL::Functor::mission_time< Dist_Info1 >::previous().
mean() [2/2]
template<class Dist_Info1 > double FATAL::Functor::mission_time< Dist_Info1 >::mean (double time) virtual
a function to obtain mean probability from distribution at given time
Parameters
time time passed
Returns
mean probability at given time
Implements FATAL::Functor::BE_FUNCTOR_BASE.
Definition at line 172 of file FixedMissionTime.hpp.
median() [1/2]
template<class Dist_Info1 > double FATAL::Functor::mission_time< Dist_Info1 >::median () virtual
a function to obtain median value from distribution
Returns
a median probability of failure
Implements FATAL::Functor::BE_FUNCTOR_BASE.
Definition at line 133 of file FixedMissionTime.hpp.
Referenced by FATAL::Functor::mission_time< Dist_Info1 >::previous().
median() [2/2]
template<class Dist_Info1 > double FATAL::Functor::mission_time< Dist_Info1 >::median (double time) virtual
a function to obtain median probability from distribution at given time
Parameters
time time passed
Returns
a median probability of failure
Implements FATAL::Functor::BE_FUNCTOR_BASE.
Definition at line 182 of file FixedMissionTime.hpp.
operator()() [1/2]
template<class Dist_Info1 > double FATAL::Functor::mission_time< Dist_Info1 >::operator() () virtual
a function to obtain random value from distribution
Returns
a random probability of failure
Reimplemented from FATAL::Functor::BE_FUNCTOR_BASE.
Definition at line 113 of file FixedMissionTime.hpp.
Referenced by FATAL::Functor::mission_time< Dist_Info1 >::previous().
operator()() [2/2]
template<class Dist_Info1 > double FATAL::Functor::mission_time< Dist_Info1 >::operator() (double time) virtual
a function to obtain random probability from distribution at given time
Parameters
time time passed
Returns
a random probability from distribution at given time
Reimplemented from FATAL::Functor::BE_FUNCTOR_BASE.
Definition at line 162 of file FixedMissionTime.hpp.
previous()
template<class Dist_Info1 > double FATAL::Functor::mission_time< Dist_Info1 >::previous () inline virtual
obtan a probability of previos calculation
Returns
a probability of previous state
Implements FATAL::Functor::BE_FUNCTOR_BASE.
Definition at line 82 of file FixedMissionTime.hpp.
References FATAL::Functor::mission_time< Dist_Info1 >::_5th(), FATAL::Functor::mission_time< Dist_Info1 >::_95th(), FATAL::Functor::mission_time< Dist_Info1 >::mean(), FATAL::Functor::mission_time< Dist_Info1 >::median(), and FATAL::Functor::mission_time< Dist_Info1 >::operator()().
The documentation for this class was generated from the following file:
FixedMissionTime.hpp
[ FATALPRA Home Page(Not Ready Yet!) ] © 2014–2015, FATALPRA Developer Team.