FATALPRA: FATAL::DD::dd_mgr< MGR, XDD > Class Template Reference
FATAL::DD::dd_mgr< MGR, XDD > Class Template Reference
#include <BDD_MGR.hpp>
Public Member Functions
boost::shared_ptr< FT::BE_DB > get_DB ()
void clear_prob ()
boost::shared_ptr< FATAL::FT::BE > get_BE (const XDD &i_BDD) const
virtual ~dd_mgr ()
dd_mgr ()
dd_mgr (const boost::shared_ptr< FT::FT_BASE > &i_FT)
void setFT (const boost::shared_ptr< FT::FT_BASE > &i_FT)
boost::shared_ptr< MGR > & mgr ()
XDD Zero () const
bool IsZero (const XDD &i_XDD) const
XDD operator() (const boost::shared_ptr< FT::BE > &i)
XDD One () const
bool IsOne (const XDD &i_XDD) const
void permute (std::vector< int > &permuter)
long long count (const XDD &i_XDD)
long long path_count (const XDD &i_XDD)
long long path_count (const XDD &i_XDD, boost::unordered_map< XDD, long long > &map)
bool find (const boost::shared_ptr< FT::FT_BASE > &i_BE)
XDD ithVar (const int &i) const
XDD Then (const XDD &i_XDD) const
XDD Else (const XDD &i_XDD) const
bool IsConstant (const XDD &i_XDD) const
XDD TopVar (const XDD &i_XDD) const
int Position (const XDD &i_XDD) const
XDD ITE (const XDD &a, const XDD &b, const XDD &c)
int order (const boost::shared_ptr< FT::FT_BASE > &i_BE) const
XDD order (const int &i)
void noOrder ()
void noOrder (const boost::shared_ptr< FATAL::FT::FT_BASE > &i_FT)
void DFLM ()
void LFDM ()
size_t size ()
void DFLM (const boost::shared_ptr< FATAL::FT::FT_BASE > &i_FT)
void LFDM (const boost::shared_ptr< FATAL::FT::FT_BASE > &i_FT)
boost::shared_ptr< FT::FT_BASE > getFT ()
XDD getBDD ()
XDD FT2BDD (const boost::shared_ptr< FT::FT_BASE > &i_FT)
double prob ()
XDD minsol_rauzy (XDD &F)
std::vector< std::pair< boost::shared_ptr< FATAL::FT::FT_BASE >, double > > raw ()
template<>
cacBDD::BDD Zero () const
template<>
cacBDD::BDD ITE (const cacBDD::BDD &a, const cacBDD::BDD &b, const cacBDD::BDD &c)
template<>
cacBDD::BDD One () const
template<>
cacBDD::BDD Then (const cacBDD::BDD &i_BDD) const
template<>
cacBDD::BDD Else (const cacBDD::BDD &i_BDD) const
template<>
void permute (std::vector< int > &permuter)
template<>
bool IsConstant (const cacBDD::BDD &i_BDD) const
template<>
long long count (const cacBDD::BDD &i_BDD)
template<>
long long path_count (const cacBDD::BDD &i_BDD)
template<>
cacBDD::BDD TopVar (const cacBDD::BDD &i_BDD) const
template<>
int Position (const cacBDD::BDD &i_BDD) const
template<>
cacBDD::BDD ithVar (const int &i) const
template<>
bool IsZero (const cacBDD::BDD &i_XDD) const
template<>
BDD Zero () const
template<>
BDD ITE (const BDD &a, const BDD &b, const BDD &c)
template<>
BDD One () const
template<>
BDD Then (const BDD &i_BDD) const
template<>
BDD Else (const BDD &i_BDD) const
template<>
void permute (std::vector< int > &permuter)
template<>
bool IsConstant (const BDD &i_BDD) const
template<>
long long count (const BDD &i_BDD)
template<>
BDD TopVar (const BDD &i_BDD) const
template<>
int Position (const BDD &i_BDD) const
template<>
BDD ithVar (const int &i) const
template<>
bool IsZero (const BDD &i_BDD) const
Protected Attributes
boost::shared_ptr< MGR > _mgr
boost::shared_ptr< FT::FT_BASE > _FT
boost::shared_ptr< FT::BE_DB > data
boost::unordered_map< XDD, boost::shared_ptr< FT::BE > > BDD2BE
boost::unordered_map< boost::shared_ptr< FATAL::FT::BE >, XDD > BE2BDD
PROB_MGR< MGR, XDD > PROB
without_map< MGR, XDD > _without_map
XDD results
Detailed Description
template<class MGR, class XDD>
class FATAL::DD::dd_mgr< MGR, XDD >
a simple wrapper for BDD class.
Todo:
modify this class to accept BDD library such as BuDDy and Sylvan. Note: dd_mgr is initialized as shared_ptr so that it can be used with PROB_MGR
Definition at line 45 of file BDD_MGR.hpp.
Constructor & Destructor Documentation
~dd_mgr()
template<class MGR , class XDD > FATAL::DD::dd_mgr< MGR, XDD >::~dd_mgr () virtual
Definition at line 532 of file BDD_MGR.hpp.
References FATAL::DD::dd_mgr< MGR, XDD >::_FT, FATAL::DD::dd_mgr< MGR, XDD >::_mgr, FATAL::DD::dd_mgr< MGR, XDD >::BDD2BE, FATAL::DD::dd_mgr< MGR, XDD >::BE2BDD, FATAL::DD::dd_mgr< MGR, XDD >::data, and FATAL::DD::dd_mgr< MGR, XDD >::PROB.
Referenced by FATAL::DD::dd_mgr< MGR, XDD >::clear_prob().
dd_mgr() [1/2]
template<class MGR , class XDD > FATAL::DD::dd_mgr< MGR, XDD >::dd_mgr ()
Definition at line 524 of file BDD_MGR.hpp.
References FATAL::DD::dd_mgr< MGR, XDD >::_mgr, and FATAL::DD::dd_mgr< MGR, XDD >::PROB.
Referenced by FATAL::DD::dd_mgr< MGR, XDD >::clear_prob().
dd_mgr() [2/2]
template<class MGR , class XDD > FATAL::DD::dd_mgr< MGR, XDD >::dd_mgr (const boost::shared_ptr< FT::FT_BASE > & i_FT)
Definition at line 512 of file BDD_MGR.hpp.
References FATAL::DD::dd_mgr< MGR, XDD >::_FT, FATAL::DD::dd_mgr< MGR, XDD >::_mgr, FATAL::DD::dd_mgr< MGR, XDD >::data, and FATAL::DD::dd_mgr< MGR, XDD >::PROB.
Member Function Documentation
clear_prob()
template<class MGR , class XDD > void FATAL::DD::dd_mgr< MGR, XDD >::clear_prob () inline
Definition at line 81 of file BDD_MGR.hpp.
References FATAL::DD::PROB_MGR< MGR, XDD >::clear(), FATAL::DD::dd_mgr< MGR, XDD >::dd_mgr(), FATAL::DD::dd_mgr< MGR, XDD >::get_BE(), FATAL::DD::dd_mgr< MGR, XDD >::setFT(), and FATAL::DD::dd_mgr< MGR, XDD >::~dd_mgr().
Referenced by FATAL::DD::dd_mgr< MGR, XDD >::raw().
count() [1/3]
template<> long long FATAL::DD::dd_mgr< cacBDD::XBDDManager, cacBDD::BDD >::count (const cacBDD::BDD & i_BDD)
Definition at line 110 of file cacBDD.hpp.
count() [2/3]
template<class MGR , class XDD > long long FATAL::DD::dd_mgr< MGR, XDD >::count (const XDD & i_XDD)
Referenced by FATAL::DD::dd_mgr< MGR, XDD >::IsOne().
count() [3/3]
template<> long long FATAL::DD::dd_mgr< Cudd, BDD >::count (const BDD & i_BDD)
Definition at line 140 of file CUDD.hpp.
DFLM() [1/2]
template<class MGR , class XDD > void FATAL::DD::dd_mgr< MGR, XDD >::DFLM ()
Definition at line 310 of file BDD_MGR.hpp.
References FATAL::DD::dd_mgr< MGR, XDD >::_FT, FATAL::DD::dd_mgr< MGR, XDD >::BDD2BE, FATAL::DD::dd_mgr< MGR, XDD >::BE2BDD, CHECKNULL, and FATAL::DD::dd_mgr< MGR, XDD >::data.
Referenced by FATAL::DD::dd_mgr< MGR, XDD >::DFLM(), FATAL::DD::dd_mgr< MGR, XDD >::path_count(), FATAL::DD::dd_mgr< MGR, XDD >::setFT(), and FATAL::DD::dd_mgr< MGR, XDD >::size().
DFLM() [2/2]
template<class MGR , class XDD > void FATAL::DD::dd_mgr< MGR, XDD >::DFLM (const boost::shared_ptr< FATAL::FT::FT_BASE > & i_FT)
Definition at line 321 of file BDD_MGR.hpp.
References FATAL::DD::dd_mgr< MGR, XDD >::BDD2BE, FATAL::DD::dd_mgr< MGR, XDD >::BE2BDD, FATAL::DD::dd_mgr< MGR, XDD >::data, FATAL::DD::dd_mgr< MGR, XDD >::DFLM(), and FATAL::DD::dd_mgr< MGR, XDD >::ithVar().
Else() [1/3]
template<> cacBDD::BDD FATAL::DD::dd_mgr< cacBDD::XBDDManager, cacBDD::BDD >::Else (const cacBDD::BDD & i_BDD) const
Definition at line 89 of file cacBDD.hpp.
References FATAL::DD::dd_mgr< MGR, XDD >::Else().
Else() [2/3]
template<> BDD FATAL::DD::dd_mgr< Cudd, BDD >::Else (const BDD & i_BDD) const
Definition at line 111 of file CUDD.hpp.
Else() [3/3]
template<class MGR , class XDD > XDD FATAL::DD::dd_mgr< MGR, XDD >::Else (const XDD & i_XDD) const
Referenced by FATAL::DD::dd_mgr< MGR, XDD >::Else(), and FATAL::DD::dd_mgr< MGR, XDD >::path_count().
find()
template<class MGR , class XDD > bool FATAL::DD::dd_mgr< MGR, XDD >::find (const boost::shared_ptr< FT::FT_BASE > & i_BE)
Definition at line 470 of file BDD_MGR.hpp.
References FATAL::DD::dd_mgr< MGR, XDD >::BE2BDD.
Referenced by FATAL::DD::dd_mgr< MGR, XDD >::path_count().
FT2BDD()
template<class MGR , class XDD > XDD FATAL::DD::dd_mgr< MGR, XDD >::FT2BDD (const boost::shared_ptr< FT::FT_BASE > & i_FT)
Definition at line 285 of file BDD_MGR.hpp.
Referenced by FATAL::DD::dd_mgr< MGR, XDD >::getFT().
get_BE()
template<class MGR , class XDD > boost::shared_ptr< FATAL::FT::BE > FATAL::DD::dd_mgr< MGR, XDD >::get_BE (const XDD & i_BDD) const
Definition at line 544 of file BDD_MGR.hpp.
References FATAL::DD::dd_mgr< MGR, XDD >::BDD2BE.
Referenced by FATAL::DD::dd_mgr< MGR, XDD >::clear_prob().
get_DB()
template<class MGR , class XDD > boost::shared_ptr<FT::BE_DB> FATAL::DD::dd_mgr< MGR, XDD >::get_DB () inline
Definition at line 76 of file BDD_MGR.hpp.
References FATAL::DD::dd_mgr< MGR, XDD >::data.
getBDD()
template<class MGR , class XDD > XDD FATAL::DD::dd_mgr< MGR, XDD >::getBDD ()
Definition at line 276 of file BDD_MGR.hpp.
References FATAL::DD::dd_mgr< MGR, XDD >::_FT, and FATAL::DD::dd_mgr< MGR, XDD >::results.
Referenced by FATAL::DD::dd_mgr< MGR, XDD >::getFT(), and FATAL::DD::dd_mgr< MGR, XDD >::prob().
getFT()
template<class MGR , class XDD > boost::shared_ptr<FT::FT_BASE> FATAL::DD::dd_mgr< MGR, XDD >::getFT () inline
Definition at line 182 of file BDD_MGR.hpp.
References FATAL::DD::dd_mgr< MGR, XDD >::_FT, FATAL::DD::dd_mgr< MGR, XDD >::FT2BDD(), FATAL::DD::dd_mgr< MGR, XDD >::getBDD(), and FATAL::DD::dd_mgr< MGR, XDD >::prob().
IsConstant() [1/3]
template<> bool FATAL::DD::dd_mgr< cacBDD::XBDDManager, cacBDD::BDD >::IsConstant (const cacBDD::BDD & i_BDD) const
Definition at line 103 of file cacBDD.hpp.
IsConstant() [2/3]
template<> bool FATAL::DD::dd_mgr< Cudd, BDD >::IsConstant (const BDD & i_BDD) const
Definition at line 134 of file CUDD.hpp.
IsConstant() [3/3]
template<class MGR , class XDD > bool FATAL::DD::dd_mgr< MGR, XDD >::IsConstant (const XDD & i_XDD) const
Referenced by FATAL::DD::dd_mgr< MGR, XDD >::IsOne(), and FATAL::DD::dd_mgr< MGR, XDD >::path_count().
IsOne()
template<class MGR , class XDD > bool FATAL::DD::dd_mgr< MGR, XDD >::IsOne (const XDD & i_XDD) const inline
Definition at line 108 of file BDD_MGR.hpp.
References FATAL::DD::dd_mgr< MGR, XDD >::count(), FATAL::DD::dd_mgr< MGR, XDD >::IsConstant(), FATAL::DD::dd_mgr< MGR, XDD >::IsZero(), and FATAL::DD::dd_mgr< MGR, XDD >::permute().
Referenced by FATAL::DD::dd_mgr< MGR, XDD >::path_count().
IsZero() [1/3]
template<class MGR , class XDD > bool FATAL::DD::dd_mgr< MGR, XDD >::IsZero (const XDD & i_XDD) const
Referenced by FATAL::DD::dd_mgr< MGR, XDD >::IsOne(), and FATAL::DD::dd_mgr< MGR, XDD >::mgr().
IsZero() [2/3]
template<> bool FATAL::DD::dd_mgr< cacBDD::XBDDManager, cacBDD::BDD >::IsZero (const cacBDD::BDD & i_XDD) const
Definition at line 153 of file cacBDD.hpp.
IsZero() [3/3]
template<> bool FATAL::DD::dd_mgr< Cudd, BDD >::IsZero (const BDD & i_BDD) const
Definition at line 201 of file CUDD.hpp.
ITE() [1/3]
template<> cacBDD::BDD FATAL::DD::dd_mgr< cacBDD::XBDDManager, cacBDD::BDD >::ITE (const cacBDD::BDD & a, const cacBDD::BDD & b, const cacBDD::BDD & c)
Definition at line 71 of file cacBDD.hpp.
ITE() [2/3]
template<> BDD FATAL::DD::dd_mgr< Cudd, BDD >::ITE (const BDD & a, const BDD & b, const BDD & c)
Definition at line 85 of file CUDD.hpp.
ITE() [3/3]
template<class MGR , class XDD > XDD FATAL::DD::dd_mgr< MGR, XDD >::ITE (const XDD & a, const XDD & b, const XDD & c)
Referenced by FATAL::DD::dd_mgr< MGR, XDD >::path_count().
ithVar() [1/3]
template<> cacBDD::BDD FATAL::DD::dd_mgr< cacBDD::XBDDManager, cacBDD::BDD >::ithVar (const int & i) const
Definition at line 147 of file cacBDD.hpp.
ithVar() [2/3]
template<class MGR , class XDD > XDD FATAL::DD::dd_mgr< MGR, XDD >::ithVar (const int & i) const
Referenced by FATAL::DD::dd_mgr< MGR, XDD >::DFLM(), FATAL::DD::dd_mgr< MGR, XDD >::LFDM(), FATAL::DD::dd_mgr< MGR, XDD >::noOrder(), and FATAL::DD::dd_mgr< MGR, XDD >::path_count().
ithVar() [3/3]
template<> BDD FATAL::DD::dd_mgr< Cudd, BDD >::ithVar (const int & i) const
Definition at line 195 of file CUDD.hpp.
LFDM() [1/2]
template<class MGR , class XDD > void FATAL::DD::dd_mgr< MGR, XDD >::LFDM ()
Definition at line 299 of file BDD_MGR.hpp.
References FATAL::DD::dd_mgr< MGR, XDD >::_FT, FATAL::DD::dd_mgr< MGR, XDD >::BDD2BE, FATAL::DD::dd_mgr< MGR, XDD >::BE2BDD, CHECKNULL, and FATAL::DD::dd_mgr< MGR, XDD >::data.
Referenced by FATAL::DD::dd_mgr< MGR, XDD >::LFDM(), FATAL::DD::dd_mgr< MGR, XDD >::path_count(), and FATAL::DD::dd_mgr< MGR, XDD >::size().
LFDM() [2/2]
template<class MGR , class XDD > void FATAL::DD::dd_mgr< MGR, XDD >::LFDM (const boost::shared_ptr< FATAL::FT::FT_BASE > & i_FT)
Definition at line 368 of file BDD_MGR.hpp.
References FATAL::DD::dd_mgr< MGR, XDD >::BDD2BE, FATAL::DD::dd_mgr< MGR, XDD >::BE2BDD, FATAL::DD::dd_mgr< MGR, XDD >::data, FATAL::DD::dd_mgr< MGR, XDD >::ithVar(), and FATAL::DD::dd_mgr< MGR, XDD >::LFDM().
mgr()
template<class MGR , class XDD > boost::shared_ptr<MGR>& FATAL::DD::dd_mgr< MGR, XDD >::mgr () inline
Definition at line 97 of file BDD_MGR.hpp.
References FATAL::DD::dd_mgr< MGR, XDD >::_mgr, FATAL::DD::dd_mgr< MGR, XDD >::IsZero(), FATAL::DD::dd_mgr< MGR, XDD >::One(), FATAL::DD::dd_mgr< MGR, XDD >::operator()(), and FATAL::DD::dd_mgr< MGR, XDD >::Zero().
minsol_rauzy()
template<class MGR , class XDD > XDD FATAL::DD::dd_mgr< MGR, XDD >::minsol_rauzy (XDD & F) inline
Definition at line 190 of file BDD_MGR.hpp.
References FATAL::DD::without_map< MGR, XDD >::minsol_rauzy().
noOrder() [1/2]
template<class MGR , class XDD > void FATAL::DD::dd_mgr< MGR, XDD >::noOrder ()
Definition at line 415 of file BDD_MGR.hpp.
References FATAL::DD::dd_mgr< MGR, XDD >::_FT, FATAL::DD::dd_mgr< MGR, XDD >::BDD2BE, FATAL::DD::dd_mgr< MGR, XDD >::BE2BDD, CHECKNULL, and FATAL::DD::dd_mgr< MGR, XDD >::data.
Referenced by FATAL::DD::dd_mgr< MGR, XDD >::path_count().
noOrder() [2/2]
template<class MGR , class XDD > void FATAL::DD::dd_mgr< MGR, XDD >::noOrder (const boost::shared_ptr< FATAL::FT::FT_BASE > & i_FT)
Definition at line 427 of file BDD_MGR.hpp.
References FATAL::DD::dd_mgr< MGR, XDD >::BDD2BE, FATAL::DD::dd_mgr< MGR, XDD >::BE2BDD, FATAL::DD::dd_mgr< MGR, XDD >::data, and FATAL::DD::dd_mgr< MGR, XDD >::ithVar().
One() [1/3]
template<> cacBDD::BDD FATAL::DD::dd_mgr< cacBDD::XBDDManager, cacBDD::BDD >::One () const
Definition at line 77 of file cacBDD.hpp.
One() [2/3]
template<> BDD FATAL::DD::dd_mgr< Cudd, BDD >::One () const
Definition at line 92 of file CUDD.hpp.
One() [3/3]
template<class MGR , class XDD > XDD FATAL::DD::dd_mgr< MGR, XDD >::One () const
Referenced by FATAL::DD::dd_mgr< MGR, XDD >::mgr().
operator()()
template<class MGR , class XDD > XDD FATAL::DD::dd_mgr< MGR, XDD >::operator() (const boost::shared_ptr< FT::BE > & i)
Definition at line 492 of file BDD_MGR.hpp.
References _plog, and FATAL::DD::dd_mgr< MGR, XDD >::BE2BDD.
Referenced by FATAL::DD::dd_mgr< MGR, XDD >::mgr().
order() [1/2]
template<class MGR , class XDD > int FATAL::DD::dd_mgr< MGR, XDD >::order (const boost::shared_ptr< FT::FT_BASE > & i_BE) const
Todo:
this should check whether an input is BE
Definition at line 460 of file BDD_MGR.hpp.
References FATAL::DD::dd_mgr< MGR, XDD >::BE2BDD, and FATAL::DD::dd_mgr< MGR, XDD >::Position().
Referenced by FATAL::DD::dd_mgr< MGR, XDD >::order(), and FATAL::DD::dd_mgr< MGR, XDD >::path_count().
order() [2/2]
template<class MGR , class XDD > XDD FATAL::DD::dd_mgr< MGR, XDD >::order (const int & i)
Definition at line 448 of file BDD_MGR.hpp.
References FATAL::DD::dd_mgr< MGR, XDD >::BE2BDD, FATAL::DD::dd_mgr< MGR, XDD >::data, and FATAL::DD::dd_mgr< MGR, XDD >::order().
path_count() [1/3]
template<class MGR , class XDD > long long FATAL::DD::dd_mgr< MGR, XDD >::path_count (const XDD & i_XDD) inline
Definition at line 117 of file BDD_MGR.hpp.
Referenced by FATAL::DD::dd_mgr< MGR, XDD >::path_count().
path_count() [2/3]
template<> long long FATAL::DD::dd_mgr< cacBDD::XBDDManager, cacBDD::BDD >::path_count (const cacBDD::BDD & i_BDD)
Definition at line 119 of file cacBDD.hpp.
path_count() [3/3]
template<class MGR , class XDD > long long FATAL::DD::dd_mgr< MGR, XDD >::path_count (const XDD & i_XDD, boost::unordered_map< XDD, long long > & map) inline
Definition at line 124 of file BDD_MGR.hpp.
References FATAL::DD::dd_mgr< MGR, XDD >::DFLM(), FATAL::DD::dd_mgr< MGR, XDD >::Else(), FATAL::DD::dd_mgr< MGR, XDD >::find(), FATAL::DD::dd_mgr< MGR, XDD >::IsConstant(), FATAL::DD::dd_mgr< MGR, XDD >::IsOne(), FATAL::DD::dd_mgr< MGR, XDD >::ITE(), FATAL::DD::dd_mgr< MGR, XDD >::ithVar(), FATAL::DD::dd_mgr< MGR, XDD >::LFDM(), FATAL::DD::dd_mgr< MGR, XDD >::noOrder(), FATAL::DD::dd_mgr< MGR, XDD >::order(), FATAL::DD::dd_mgr< MGR, XDD >::path_count(), FATAL::DD::dd_mgr< MGR, XDD >::Position(), FATAL::DD::dd_mgr< MGR, XDD >::Then(), and FATAL::DD::dd_mgr< MGR, XDD >::TopVar().
permute() [1/3]
template<> void FATAL::DD::dd_mgr< cacBDD::XBDDManager, cacBDD::BDD >::permute (std::vector< int > & permuter)
Definition at line 95 of file cacBDD.hpp.
permute() [2/3]
template<class MGR , class XDD > void FATAL::DD::dd_mgr< MGR, XDD >::permute (std::vector< int > & permuter)
Referenced by FATAL::DD::dd_mgr< MGR, XDD >::IsOne().
permute() [3/3]
template<> void FATAL::DD::dd_mgr< Cudd, BDD >::permute (std::vector< int > & permuter)
Definition at line 128 of file CUDD.hpp.
Position() [1/3]
template<> int FATAL::DD::dd_mgr< cacBDD::XBDDManager, cacBDD::BDD >::Position (const cacBDD::BDD & i_BDD) const
Definition at line 137 of file cacBDD.hpp.
Position() [2/3]
template<class MGR , class XDD > int FATAL::DD::dd_mgr< MGR, XDD >::Position (const XDD & i_XDD) const
Referenced by FATAL::DD::dd_mgr< MGR, XDD >::order(), and FATAL::DD::dd_mgr< MGR, XDD >::path_count().
Position() [3/3]
template<> int FATAL::DD::dd_mgr< Cudd, BDD >::Position (const BDD & i_BDD) const
Definition at line 171 of file CUDD.hpp.
prob()
template<class MGR , class XDD > double FATAL::DD::dd_mgr< MGR, XDD >::prob ()
Definition at line 292 of file BDD_MGR.hpp.
References FATAL::DD::dd_mgr< MGR, XDD >::getBDD(), and FATAL::DD::dd_mgr< MGR, XDD >::PROB.
Referenced by FATAL::DD::dd_mgr< MGR, XDD >::getFT(), and FATAL::DD::dd_mgr< MGR, XDD >::raw().
raw()
template<class MGR , class XDD > std::vector<std::pair<boost::shared_ptr<FATAL::FT::FT_BASE>, double> > FATAL::DD::dd_mgr< MGR, XDD >::raw () inline
Definition at line 198 of file BDD_MGR.hpp.
References FATAL::DD::bdd_kn(), FATAL::DD::dd_mgr< MGR, XDD >::clear_prob(), and FATAL::DD::dd_mgr< MGR, XDD >::prob().
setFT()
template<class MGR , class XDD > void FATAL::DD::dd_mgr< MGR, XDD >::setFT (const boost::shared_ptr< FT::FT_BASE > & i_FT)
Definition at line 503 of file BDD_MGR.hpp.
References FATAL::DD::dd_mgr< MGR, XDD >::_FT, FATAL::DD::dd_mgr< MGR, XDD >::data, and FATAL::DD::dd_mgr< MGR, XDD >::DFLM().
Referenced by FATAL::DD::dd_mgr< MGR, XDD >::clear_prob().
size()
template<class MGR , class XDD > size_t FATAL::DD::dd_mgr< MGR, XDD >::size () inline
Definition at line 176 of file BDD_MGR.hpp.
References FATAL::DD::dd_mgr< MGR, XDD >::DFLM(), and FATAL::DD::dd_mgr< MGR, XDD >::LFDM().
Then() [1/3]
template<> cacBDD::BDD FATAL::DD::dd_mgr< cacBDD::XBDDManager, cacBDD::BDD >::Then (const cacBDD::BDD & i_BDD) const
Definition at line 83 of file cacBDD.hpp.
References FATAL::DD::dd_mgr< MGR, XDD >::Then().
Then() [2/3]
template<> BDD FATAL::DD::dd_mgr< Cudd, BDD >::Then (const BDD & i_BDD) const
Definition at line 98 of file CUDD.hpp.
Then() [3/3]
template<class MGR , class XDD > XDD FATAL::DD::dd_mgr< MGR, XDD >::Then (const XDD & i_XDD) const
Referenced by FATAL::DD::dd_mgr< MGR, XDD >::path_count(), and FATAL::DD::dd_mgr< MGR, XDD >::Then().
TopVar() [1/3]
template<> cacBDD::BDD FATAL::DD::dd_mgr< cacBDD::XBDDManager, cacBDD::BDD >::TopVar (const cacBDD::BDD & i_BDD) const
Definition at line 127 of file cacBDD.hpp.
TopVar() [2/3]
template<> BDD FATAL::DD::dd_mgr< Cudd, BDD >::TopVar (const BDD & i_BDD) const
Definition at line 146 of file CUDD.hpp.
TopVar() [3/3]
template<class MGR , class XDD > XDD FATAL::DD::dd_mgr< MGR, XDD >::TopVar (const XDD & i_XDD) const
Referenced by FATAL::DD::dd_mgr< MGR, XDD >::path_count().
Zero() [1/3]
template<> cacBDD::BDD FATAL::DD::dd_mgr< cacBDD::XBDDManager, cacBDD::BDD >::Zero () const
Definition at line 65 of file cacBDD.hpp.
Zero() [2/3]
template<> BDD FATAL::DD::dd_mgr< Cudd, BDD >::Zero () const
Definition at line 79 of file CUDD.hpp.
Zero() [3/3]
template<class MGR , class XDD > XDD FATAL::DD::dd_mgr< MGR, XDD >::Zero () const
Referenced by FATAL::DD::dd_mgr< MGR, XDD >::mgr().
Member Data Documentation
_FT
template<class MGR , class XDD > boost::shared_ptr<FT::FT_BASE> FATAL::DD::dd_mgr< MGR, XDD >::_FT protected
Definition at line 53 of file BDD_MGR.hpp.
Referenced by FATAL::DD::dd_mgr< MGR, XDD >::dd_mgr(), FATAL::DD::dd_mgr< MGR, XDD >::DFLM(), FATAL::DD::dd_mgr< MGR, XDD >::getBDD(), FATAL::DD::dd_mgr< MGR, XDD >::getFT(), FATAL::DD::dd_mgr< MGR, XDD >::LFDM(), FATAL::DD::dd_mgr< MGR, XDD >::noOrder(), FATAL::DD::dd_mgr< MGR, XDD >::setFT(), and FATAL::DD::dd_mgr< MGR, XDD >::~dd_mgr().
_mgr
template<class MGR , class XDD > boost::shared_ptr<MGR> FATAL::DD::dd_mgr< MGR, XDD >::_mgr protected
Definition at line 52 of file BDD_MGR.hpp.
Referenced by FATAL::DD::dd_mgr< MGR, XDD >::dd_mgr(), FATAL::DD::dd_mgr< MGR, XDD >::mgr(), and FATAL::DD::dd_mgr< MGR, XDD >::~dd_mgr().
_without_map
template<class MGR , class XDD > without_map<MGR, XDD> FATAL::DD::dd_mgr< MGR, XDD >::_without_map protected
Definition at line 68 of file BDD_MGR.hpp.
BDD2BE
template<class MGR , class XDD > boost::unordered_map<XDD, boost::shared_ptr<FT::BE> > FATAL::DD::dd_mgr< MGR, XDD >::BDD2BE protected
Definition at line 59 of file BDD_MGR.hpp.
Referenced by FATAL::DD::dd_mgr< MGR, XDD >::DFLM(), FATAL::DD::dd_mgr< MGR, XDD >::get_BE(), FATAL::DD::dd_mgr< MGR, XDD >::LFDM(), FATAL::DD::dd_mgr< MGR, XDD >::noOrder(), and FATAL::DD::dd_mgr< MGR, XDD >::~dd_mgr().
BE2BDD
template<class MGR , class XDD > boost::unordered_map<boost::shared_ptr<FATAL::FT::BE>, XDD> FATAL::DD::dd_mgr< MGR, XDD >::BE2BDD protected
an inverse map between BDD and BE
Definition at line 62 of file BDD_MGR.hpp.
Referenced by FATAL::DD::dd_mgr< MGR, XDD >::DFLM(), FATAL::DD::dd_mgr< MGR, XDD >::find(), FATAL::DD::dd_mgr< MGR, XDD >::LFDM(), FATAL::DD::dd_mgr< MGR, XDD >::noOrder(), FATAL::DD::dd_mgr< MGR, XDD >::operator()(), FATAL::DD::dd_mgr< MGR, XDD >::order(), and FATAL::DD::dd_mgr< MGR, XDD >::~dd_mgr().
data
template<class MGR , class XDD > boost::shared_ptr<FT::BE_DB> FATAL::DD::dd_mgr< MGR, XDD >::data protected
a pointer to basic event database
Definition at line 56 of file BDD_MGR.hpp.
Referenced by FATAL::DD::dd_mgr< MGR, XDD >::dd_mgr(), FATAL::DD::dd_mgr< MGR, XDD >::DFLM(), FATAL::DD::dd_mgr< MGR, XDD >::get_DB(), FATAL::DD::dd_mgr< MGR, XDD >::LFDM(), FATAL::DD::dd_mgr< MGR, XDD >::noOrder(), FATAL::DD::dd_mgr< MGR, XDD >::order(), FATAL::DD::dd_mgr< MGR, XDD >::setFT(), and FATAL::DD::dd_mgr< MGR, XDD >::~dd_mgr().
PROB
template<class MGR , class XDD > PROB_MGR<MGR, XDD> FATAL::DD::dd_mgr< MGR, XDD >::PROB protected
Definition at line 65 of file BDD_MGR.hpp.
Referenced by FATAL::DD::dd_mgr< MGR, XDD >::dd_mgr(), FATAL::DD::dd_mgr< MGR, XDD >::prob(), and FATAL::DD::dd_mgr< MGR, XDD >::~dd_mgr().
results
template<class MGR , class XDD > XDD FATAL::DD::dd_mgr< MGR, XDD >::results protected
Definition at line 71 of file BDD_MGR.hpp.
Referenced by FATAL::DD::dd_mgr< MGR, XDD >::getBDD().
The documentation for this class was generated from the following file:
BDD_MGR.hpp
[ FATALPRA Home Page(Not Ready Yet!) ] © 2014–2015, FATALPRA Developer Team.