FATALPRA: FATAL::CCF::beta< tag > Class Template Reference
FATAL::CCF::beta< tag > Class Template Reference
#include <beta.hpp>
Public Member Functions
beta ()
beta (const Impact_Vector &IV)
double get_beta (const unsigned int &CCCG, const double &rho) const
double get_beta (const unsigned int &CCCG, std::function< const double(std::vector< double >)> rho_functor) const
std::vector< double > get_prob (const double &Q, const double &beta_val, const unsigned int &CCCG) const
std::vector< double > get_prob (const double &Q, const unsigned int &CCCG, const double &rho) const
std::vector< double > get_prob (const double &Q, const unsigned int &CCCG, std::function< const double(std::vector< double >)> rho_functor) const
Public Attributes
const Impact_Vector _IV
Detailed Description
template<typename tag>
class FATAL::CCF::beta< tag >
Definition at line 38 of file beta.hpp.
Constructor & Destructor Documentation
beta() [1/2]
template<typename tag > FATAL::CCF::beta< tag >::beta () inline
Definition at line 45 of file beta.hpp.
beta() [2/2]
template<typename tag > FATAL::CCF::beta< tag >::beta (const Impact_Vector & IV) inline
Definition at line 47 of file beta.hpp.
Member Function Documentation
get_beta() [1/2]
template<typename tag > double FATAL::CCF::beta< tag >::get_beta (const unsigned int & CCCG, const double & rho) const inline
Definition at line 49 of file beta.hpp.
References FATAL::CCF::Impact_Vector::getImpactVector().
Referenced by FATAL::CCF::beta< tag >::get_prob().
get_beta() [2/2]
template<typename tag > double FATAL::CCF::beta< tag >::get_beta (const unsigned int & CCCG, std::function< const double(std::vector< double >)> rho_functor) const inline
Definition at line 62 of file beta.hpp.
References FATAL::CCF::Impact_Vector::getImpactVector().
get_prob() [1/3]
template<typename tag > std::vector<double> FATAL::CCF::beta< tag >::get_prob (const double & Q, const double & beta_val, const unsigned int & CCCG) const inline
Definition at line 76 of file beta.hpp.
get_prob() [2/3]
template<typename tag > std::vector<double> FATAL::CCF::beta< tag >::get_prob (const double & Q, const unsigned int & CCCG, const double & rho) const inline
Definition at line 86 of file beta.hpp.
References FATAL::CCF::beta< tag >::get_beta().
get_prob() [3/3]
template<typename tag > std::vector<double> FATAL::CCF::beta< tag >::get_prob (const double & Q, const unsigned int & CCCG, std::function< const double(std::vector< double >)> rho_functor) const inline
Definition at line 98 of file beta.hpp.
References FATAL::CCF::beta< tag >::get_beta().
Member Data Documentation
_IV
template<typename tag > const Impact_Vector FATAL::CCF::beta< tag >::_IV
Definition at line 43 of file beta.hpp.
The documentation for this class was generated from the following file:
beta.hpp
[ FATALPRA Home Page(Not Ready Yet!) ] © 2014–2015, FATALPRA Developer Team.