FATALPRA: FATAL::dist_interface< dist, rand > Class Template Reference
FATAL::dist_interface< dist, rand > Class Template Reference
#include <PROB_INTERFACE.hpp>
Public Types
typedef non_correlated is_correlated
typedef rand rand_type
typedef dist dist_type
using DIST_TYPE = dist
using RAND_TYPE = rand
Public Member Functions
rand_type get_rand ()
dist_type get_dist ()
dist_interface ()=delete
dist_interface (const std::vector< double > &param1, const std::vector< double > &param2)
dist_interface (const std::vector< double > &param1, const std::vector< double > &param2, const double &T)
virtual ~dist_interface ()
double operator() ()
double percentile (const double &_percentile)
double _5th ()
double _50th ()
double _95th ()
double mean ()
double median ()
template<>
double percentile (const double &_percentile)
template<>
double mean ()
Detailed Description
template<class dist, class rand>
class FATAL::dist_interface< dist, rand >
Definition at line 57 of file PROB_INTERFACE.hpp.
Member Typedef Documentation
dist_type
template<class dist, class rand> typedef dist FATAL::dist_interface< dist, rand >::dist_type
Definition at line 80 of file PROB_INTERFACE.hpp.
DIST_TYPE
template<class dist, class rand> using FATAL::dist_interface< dist, rand >::DIST_TYPE = dist
Definition at line 92 of file PROB_INTERFACE.hpp.
is_correlated
template<class dist, class rand> typedef non_correlated FATAL::dist_interface< dist, rand >::is_correlated
Definition at line 78 of file PROB_INTERFACE.hpp.
rand_type
template<class dist, class rand> typedef rand FATAL::dist_interface< dist, rand >::rand_type
Definition at line 79 of file PROB_INTERFACE.hpp.
RAND_TYPE
template<class dist, class rand> using FATAL::dist_interface< dist, rand >::RAND_TYPE = rand
Definition at line 93 of file PROB_INTERFACE.hpp.
Constructor & Destructor Documentation
dist_interface() [1/3]
template<class dist, class rand> FATAL::dist_interface< dist, rand >::dist_interface () delete
dist_interface() [2/3]
template<class dist, class rand> FATAL::dist_interface< dist, rand >::dist_interface (const std::vector< double > & param1, const std::vector< double > & param2) inline
Definition at line 105 of file PROB_INTERFACE.hpp.
dist_interface() [3/3]
template<class dist, class rand> FATAL::dist_interface< dist, rand >::dist_interface (const std::vector< double > & param1, const std::vector< double > & param2, const double & T) inline
Definition at line 115 of file PROB_INTERFACE.hpp.
~dist_interface()
template<class dist, class rand> virtual FATAL::dist_interface< dist, rand >::~dist_interface () inline virtual
Definition at line 132 of file PROB_INTERFACE.hpp.
Member Function Documentation
_50th()
template<class dist, class rand> double FATAL::dist_interface< dist, rand >::_50th () inline
Definition at line 155 of file PROB_INTERFACE.hpp.
References FATAL::dist_interface< dist, rand >::percentile().
_5th()
template<class dist, class rand> double FATAL::dist_interface< dist, rand >::_5th () inline
Definition at line 149 of file PROB_INTERFACE.hpp.
References FATAL::dist_interface< dist, rand >::percentile().
_95th()
template<class dist, class rand> double FATAL::dist_interface< dist, rand >::_95th () inline
Definition at line 161 of file PROB_INTERFACE.hpp.
References FATAL::dist_interface< dist, rand >::percentile().
get_dist()
template<class dist, class rand> dist_type FATAL::dist_interface< dist, rand >::get_dist () inline
Definition at line 87 of file PROB_INTERFACE.hpp.
get_rand()
template<class dist, class rand> rand_type FATAL::dist_interface< dist, rand >::get_rand () inline
Definition at line 82 of file PROB_INTERFACE.hpp.
mean() [1/2]
template<class dist, class rand> double FATAL::dist_interface< dist, rand >::mean () inline
Definition at line 167 of file PROB_INTERFACE.hpp.
mean() [2/2]
template<> double FATAL::dist_interface< prob::logit_normal, prob::logit_normal_random >::mean ()
Definition at line 186 of file PROB_INTERFACE.hpp.
median()
template<class dist, class rand> double FATAL::dist_interface< dist, rand >::median () inline
Definition at line 172 of file PROB_INTERFACE.hpp.
References FATAL::dist_interface< dist, rand >::percentile().
operator()()
template<class dist, class rand> double FATAL::dist_interface< dist, rand >::operator() () inline
Definition at line 137 of file PROB_INTERFACE.hpp.
percentile() [1/2]
template<class dist, class rand> double FATAL::dist_interface< dist, rand >::percentile (const double & _percentile) inline
Definition at line 144 of file PROB_INTERFACE.hpp.
Referenced by FATAL::dist_interface< dist, rand >::_50th(), FATAL::dist_interface< dist, rand >::_5th(), FATAL::dist_interface< dist, rand >::_95th(), and FATAL::dist_interface< dist, rand >::median().
percentile() [2/2]
template<> double FATAL::dist_interface< prob::logit_normal, prob::logit_normal_random >::percentile (const double & _percentile)
Definition at line 180 of file PROB_INTERFACE.hpp.
The documentation for this class was generated from the following file:
PROB_INTERFACE.hpp
[ FATALPRA Home Page(Not Ready Yet!) ] © 2014–2015, FATALPRA Developer Team.