FATALPRA: FATAL::CCF::Impact_Vector Class Reference
FATAL::CCF::Impact_Vector Class Reference
#include <impactVector.hpp>
Public Member Functions
Impact_Vector ()
void set_IND (const std::vector< double > &P)
void set_IND (const int &CCCG, const double &val)
void set_CCF (const std::vector< double > &P, const double &c, const double p)
std::vector< double > getImpactVector (const unsigned int &new_CCCG, const double rho) const
std::vector< double > getImpactVector (const unsigned int &new_CCCG, std::function< const double(const std::vector< double >)> functor=nullptr) const
Detailed Description
Definition at line 345 of file impactVector.hpp.
Constructor & Destructor Documentation
Impact_Vector()
FATAL::CCF::Impact_Vector::Impact_Vector () inline
Definition at line 352 of file impactVector.hpp.
Member Function Documentation
getImpactVector() [1/2]
std::vector<double> FATAL::CCF::Impact_Vector::getImpactVector (const unsigned int & new_CCCG, const double rho) const inline
Definition at line 373 of file impactVector.hpp.
Referenced by FATAL::CCF::alpha< tag >::get_alpha(), FATAL::CCF::beta< tag >::get_beta(), and FATAL::CCF::MGL< tag >::get_MGLs().
getImpactVector() [2/2]
std::vector<double> FATAL::CCF::Impact_Vector::getImpactVector (const unsigned int & new_CCCG, std::function< const double(const std::vector< double >)> functor = nullptr) const inline
Definition at line 389 of file impactVector.hpp.
set_CCF()
void FATAL::CCF::Impact_Vector::set_CCF (const std::vector< double > & P, const double & c, const double p) inline
Definition at line 368 of file impactVector.hpp.
References FATAL::CCF::CCF.
set_IND() [1/2]
void FATAL::CCF::Impact_Vector::set_IND (const std::vector< double > & P) inline
Definition at line 354 of file impactVector.hpp.
References FATAL::CCF::IND.
set_IND() [2/2]
void FATAL::CCF::Impact_Vector::set_IND (const int & CCCG, const double & val) inline
Definition at line 359 of file impactVector.hpp.
References FATAL::CCF::IND.
The documentation for this class was generated from the following file:
impactVector.hpp
[ FATALPRA Home Page(Not Ready Yet!) ] © 2014–2015, FATALPRA Developer Team.