FATALPRA: FATAL::DD Namespace Reference
FATAL::DD Namespace Reference
a set of classes for Decision Diagram comparison
Classes
class dd_mgr
class Depth_Greater
a class to compare depth of two fault trees
class Depth_Less
a class to compare depth of two fault trees
class PROB_MGR
class without_map
Functions
template<class _BDD , class _MGR >
_BDD bdd_kn (const int &k, typename std::vector< _BDD >::iterator begin, const int &i, const boost::shared_ptr< FATAL::DD::dd_mgr< _MGR, _BDD >> &i_mgr)
Detailed Description
a set of classes for Decision Diagram comparison
a set of classes for Decision Diagram comparison
Function Documentation
bdd_kn()
template<class _BDD , class _MGR > _BDD FATAL::DD::bdd_kn (const int & k, typename std::vector< _BDD >::iterator begin, const int & i, const boost::shared_ptr< FATAL::DD::dd_mgr< _MGR, _BDD >> & i_mgr)
Definition at line 253 of file BDD_MGR.hpp.
Referenced by FATAL::FT::KN::GateOp(), FATAL::FT::NKN::GateOp(), and FATAL::DD::dd_mgr< MGR, XDD >::raw().
[ FATALPRA Home Page(Not Ready Yet!) ] © 2014–2015, FATALPRA Developer Team.