FATALPRA: FATAL::ET::ET Class Reference
FATAL::ET::ET Class Reference
#include <ET.hpp>
Public Member Functions
ET ()
ET (boost::shared_ptr< ET_BASE > i_success, boost::shared_ptr< ET_BASE > i_fail, boost::shared_ptr< FATAL::FT::FT_BASE > i_FT)
ET (const std::string &i_name)
void clear ()
ET_TYPE GET_ET_TYPE ()
bool is_cyclic ()
bool is_cyclic (std::vector< boost::shared_ptr< ET_BASE >> &targets)
virtual ~ET ()
Public Member Functions inherited from FATAL::ET::ET_BASE
template<class T >
boost::shared_ptr< T > cast ()
virtual void assign_type (CD_SEQ _ID)
virtual boost::shared_ptr< FATAL::FT::FT_BASE > get_Equiv_FT ()
virtual void print ()
virtual void null2seq (bool isIE=false)
virtual void prep (bool is_IE=false)
virtual void prep (std::vector< boost::shared_ptr< FT::FT_BASE >> i_FTs, std::vector< bool > i_branch_info)
bool is_branch_null (bool state)
ET_BASE ()
ET_BASE (const boost::shared_ptr< ET_BASE > &i_success, const boost::shared_ptr< ET_BASE > &i_fail, const boost::shared_ptr< FATAL::FT::FT_BASE > &i_FT)
ET_BASE (const std::string &i_name)
boost::shared_ptr< FT::FT_BASE > & getFT ()
void assign (const boost::shared_ptr< ET_BASE > i_success, const boost::shared_ptr< ET_BASE > i_fail, bool force=false)
void assign (const boost::shared_ptr< FT::FT_BASE > &i_FT)
void assign (bool path, const boost::shared_ptr< ET_BASE > i_ET)
boost::shared_ptr< ET_BASE > getET (bool status)
void clear ()
void assign_FT (const boost::shared_ptr< FT::FT_BASE > &i_FT)
virtual ~ET_BASE ()
virtual std::vector< boost::shared_ptr< ET_BASE > > get_seq (bool is_IE=false, bool validate=true)
virtual void auto_replace (std::vector< boost::shared_ptr< ET_BASE >> &sequences)
virtual bool is_replacible (bool state)
Public Member Functions inherited from FATAL::ET::ET_PROPERTY
ET_PROPERTY ()
ET_PROPERTY (std::string i_evt)
void set_evt (const std::string &i_name)
std::string get_evt ()
Additional Inherited Members
Protected Attributes inherited from FATAL::ET::ET_BASE
boost::shared_ptr< FT::FT_BASE > FT
boost::shared_ptr< ET_BASE > success
boost::shared_ptr< ET_BASE > fail
Detailed Description
Definition at line 35 of file ET/ET.hpp.
Constructor & Destructor Documentation
ET() [1/3]
FATAL::ET::ET::ET () inline
default constructor
Definition at line 51 of file ET/ET.hpp.
ET() [2/3]
FATAL::ET::ET::ET (boost::shared_ptr< ET_BASE > i_success, boost::shared_ptr< ET_BASE > i_fail, boost::shared_ptr< FATAL::FT::FT_BASE > i_FT)
default constructor
Definition at line 107 of file ET/ET.hpp.
References FATAL::ET::ET_BASE::fail, FATAL::ET::ET_BASE::FT, and FATAL::ET::ET_BASE::success.
ET() [3/3]
FATAL::ET::ET::ET (const std::string & i_name) inline
default constructor
Definition at line 60 of file ET/ET.hpp.
References clear(), GET_ET_TYPE(), and is_cyclic().
~ET()
virtual FATAL::ET::ET::~ET () inline virtual
default constructor
Definition at line 91 of file ET/ET.hpp.
Member Function Documentation
clear()
void FATAL::ET::ET::clear ()
clear memory
Definition at line 123 of file ET/ET.hpp.
References FATAL::ET::ET_BASE::fail, and FATAL::ET::ET_BASE::success.
Referenced by ET().
GET_ET_TYPE()
ET_TYPE FATAL::ET::ET::GET_ET_TYPE () virtual
obtain an ET_TYPE
Reimplemented from FATAL::ET::ET_BASE.
Definition at line 102 of file ET/ET.hpp.
References FATAL::ET.
Referenced by ET().
is_cyclic() [1/2]
bool FATAL::ET::ET::is_cyclic () virtual
check if ET is cyclic
Implements FATAL::ET::ET_BASE.
Definition at line 157 of file ET/ET.hpp.
References FATAL::ET::ET_BASE::fail, and FATAL::ET::ET_BASE::success.
Referenced by ET().
is_cyclic() [2/2]
bool FATAL::ET::ET::is_cyclic (std::vector< boost::shared_ptr< ET_BASE >> & targets) virtual
check if ET is cyclic
Implements FATAL::ET::ET_BASE.
Definition at line 129 of file ET/ET.hpp.
References FATAL::ET::ET_BASE::fail, and FATAL::ET::ET_BASE::success.
The documentation for this class was generated from the following file:
ET/ET.hpp
[ FATALPRA Home Page(Not Ready Yet!) ] © 2014–2015, FATALPRA Developer Team.