FATALPRA: MCS.hpp File Reference
MCS.hpp File Reference
implementation for minimal cut set using dynamic_bitset
#include <vector>
#include <unordered_set>
#include <EH/Exception.hpp>
#include <boost/progress.hpp>
#include <FT/BE/BE_DB.hpp>
#include <boost/dynamic_bitset.hpp>
Classes
class FATAL::MCS
class FATAL::mcs_compare
struct std::hash< FATAL::MCS >
Namespaces
boost
template specialization of boost C++ library
FATAL
Probabilistic Risk Assessment Library.
std
template specialization of standard library for FATAL
Macros
#define BOOST_DYNAMIC_BITSET_DONT_USE_FRIENDS
Functions
template<typename B , typename A >
std::size_t boost::hash_value (const boost::dynamic_bitset< B, A > &bs)
void FATAL::remove_num (std::unordered_set< FATAL::MCS > &return_val, const unsigned int &max_num_mcs, boost::shared_ptr< FT::BE_DB > &i_DB)
void FATAL::remove (std::unordered_set< FATAL::MCS > &i_MCS, const double &cut_point, const boost::shared_ptr< FT::BE_DB > &i_DB)
boost::dynamic_bitset FATAL::iden_common (const std::unordered_set< FATAL::MCS > &left, const std::unordered_set< FATAL::MCS > &right)
bool FATAL::mcs_sort (FATAL::MCS i, FATAL::MCS j)
std::unordered_set< FATAL::MCS > FATAL::conjunction (const std::unordered_set< FATAL::MCS > &As, const std::unordered_set< FATAL::MCS > &Bs, boost::shared_ptr< FATAL::FT::BE_DB > i_DB=nullptr, unsigned int max_num_mcs=10000, double cut_point=0)
std::unordered_set< FATAL::MCS > FATAL::disjunction (const std::unordered_set< FATAL::MCS > &left, const std::unordered_set< FATAL::MCS > &right, boost::shared_ptr< FATAL::FT::BE_DB > i_DB=nullptr, unsigned int max_num_mcs=10000, double cut_point=0)
(MCS + MCS + ... MCS) + (MCS + MCS + ... MCS)
std::unordered_set< FATAL::MCS > operator+ (const std::unordered_set< FATAL::MCS > &left, const std::unordered_set< FATAL::MCS > &right)
(MCS + MCS + ... MCS) + (MCS + MCS + ... MCS)
std::unordered_set< FATAL::MCS > operator* (const std::unordered_set< FATAL::MCS > &left, const FATAL::MCS &right)
std::unordered_set< FATAL::MCS > operator* (const std::unordered_set< FATAL::MCS > &As, const std::unordered_set< FATAL::MCS > &Bs)
std::unordered_set< FATAL::MCS > operator+ (const std::unordered_set< FATAL::MCS > &left, const FATAL::MCS &right)
Detailed Description
implementation for minimal cut set using dynamic_bitset
****10********20********30********40********50********60********70********80********90*******100*******110*******120
Version
1.0
Date
2015/06/10 Updates in comments.
Author
S. Soga
DESCRIPTION
This file implements minimal cut set using dynamic bitset.
History
2015/06/10 S. Spga
Updated the doxygen comments
clean up source codes
Note
minimal cut set can be implemented by several approach. This is just one example implementaion for reference.
Copyright (C) Central Research Institute of Electric Power Industry 2015-2016. Distributed under the CRIEPI Open Source Software License, Version 1.0. (See accompanying file FATALPRA_OSS_LICENSE(JP)_151202.pdf or copy at https://github.com/soga-denken/fatalpra/blob/master/FATALPRA_OSS_LICENSE(JP)_151202.pdf)
Definition in file MCS.hpp.
Macro Definition Documentation
BOOST_DYNAMIC_BITSET_DONT_USE_FRIENDS
#define BOOST_DYNAMIC_BITSET_DONT_USE_FRIENDS
Definition at line 34 of file MCS.hpp.
Function Documentation
operator*() [1/2]
std::unordered_set<FATAL::MCS> operator* (const std::unordered_set< FATAL::MCS > & left, const FATAL::MCS & right)
Definition at line 287 of file MCS.hpp.
Referenced by FATAL::MCS::operator*().
operator*() [2/2]
std::unordered_set<FATAL::MCS> operator* (const std::unordered_set< FATAL::MCS > & As, const std::unordered_set< FATAL::MCS > & Bs)
Definition at line 295 of file MCS.hpp.
References FATAL::conjunction().
operator+() [1/2]
std::unordered_set<FATAL::MCS> operator+ (const std::unordered_set< FATAL::MCS > & left, const std::unordered_set< FATAL::MCS > & right)
(MCS + MCS + ... MCS) + (MCS + MCS + ... MCS)
Definition at line 280 of file MCS.hpp.
References FATAL::disjunction().
Referenced by FATAL::MCS::operator!=().
operator+() [2/2]
std::unordered_set<FATAL::MCS> operator+ (const std::unordered_set< FATAL::MCS > & left, const FATAL::MCS & right)
Definition at line 303 of file MCS.hpp.
[ FATALPRA Home Page(Not Ready Yet!) ] © 2014–2015, FATALPRA Developer Team.