FATALPRA: SpectExp::integrate Class Reference
SpectExp::integrate Class Reference
#include <eval.hpp>
Public Member Functions
integrate ()=delete
integrate (std::vector< double > _coef, std::pair< double, double > _interval)
double eval ()
double transform (const double &x)
double eval (const double &lower, const double &upper)
Detailed Description
Definition at line 87 of file eval.hpp.
Constructor & Destructor Documentation
integrate() [1/2]
SpectExp::integrate::integrate () delete
integrate() [2/2]
SpectExp::integrate::integrate (std::vector< double > _coef, std::pair< double, double > _interval) inline
Definition at line 101 of file eval.hpp.
Member Function Documentation
eval() [1/2]
double SpectExp::integrate::eval () inline
Definition at line 107 of file eval.hpp.
References SpectExp::cheby_base::integrals().
eval() [2/2]
double SpectExp::integrate::eval (const double & lower, const double & upper) inline
Definition at line 127 of file eval.hpp.
References SpectExp::cheby_base::integrals(), and SpectExp::interpolate::transform().
transform()
double SpectExp::integrate::transform (const double & x) inline
Definition at line 122 of file eval.hpp.
The documentation for this class was generated from the following file:
eval.hpp
[ FATALPRA Home Page(Not Ready Yet!) ] © 2014–2015, FATALPRA Developer Team.