FATALPRA: SpectExp::cheby_base Class Reference
SpectExp::cheby_base Class Reference abstract
an abstract interface for chebyshev polynomials
#include <chebyshev.hpp>
Public Member Functions
double integrate ()
double integrate (const double &lower, const double &upper)
virtual void show ()
cheby_base ()=delete
cheby_base (const int &i)
virtual double eval (const double &x)=0
std::vector< double > evals (const double &x)
virtual void evals (std::vector< double > &vec)
virtual void integrals (std::vector< double > &vec)
std::vector< double > integrals (const double &_lower, const double &upper)
virtual void integrals (const double &_lower, const double &upper, std::vector< double > &lower_vec, std::vector< double > &upper_vec, std::vector< double > &vec)
virtual double _integrate (std::vector< double > &at_upper)=0
virtual double _integrate (const double &_lower, const double &upper, std::vector< double > &lower_vec, std::vector< double > &upper_vec)=0
Public Attributes
std::shared_ptr< cheby_base > lower
Protected Attributes
int order
double prev_x
double prev
Detailed Description
an abstract interface for chebyshev polynomials
Definition at line 33 of file chebyshev.hpp.
Constructor & Destructor Documentation
cheby_base() [1/2]
SpectExp::cheby_base::cheby_base () delete
Referenced by show().
cheby_base() [2/2]
SpectExp::cheby_base::cheby_base (const int & i) inline
Definition at line 75 of file chebyshev.hpp.
References eval().
Member Function Documentation
_integrate() [1/2]
virtual double SpectExp::cheby_base::_integrate (std::vector< double > & at_upper) pure virtual
Implemented in SpectExp::cheby_nth, SpectExp::cheby_1st, and SpectExp::cheby_zero.
Referenced by integrals(), and integrate().
_integrate() [2/2]
virtual double SpectExp::cheby_base::_integrate (const double & _lower, const double & upper, std::vector< double > & lower_vec, std::vector< double > & upper_vec) pure virtual
Implemented in SpectExp::cheby_nth, SpectExp::cheby_1st, and SpectExp::cheby_zero.
eval()
virtual double SpectExp::cheby_base::eval (const double & x) pure virtual
Implemented in SpectExp::cheby_nth, SpectExp::cheby_1st, and SpectExp::cheby_zero.
Referenced by cheby_base(), and evals().
evals() [1/2]
std::vector<double> SpectExp::cheby_base::evals (const double & x) inline
Definition at line 79 of file chebyshev.hpp.
References eval().
Referenced by SpectExp::interpolate::eval(), SpectExp::solve::get(), integrals(), and integrate().
evals() [2/2]
virtual void SpectExp::cheby_base::evals (std::vector< double > & vec) inline virtual
Reimplemented in SpectExp::cheby_zero.
Definition at line 90 of file chebyshev.hpp.
integrals() [1/3]
virtual void SpectExp::cheby_base::integrals (std::vector< double > & vec) inline virtual
Reimplemented in SpectExp::cheby_zero.
Definition at line 99 of file chebyshev.hpp.
References integrate().
Referenced by SpectExp::integrate::eval(), and integrals().
integrals() [2/3]
std::vector<double> SpectExp::cheby_base::integrals (const double & _lower, const double & upper) inline
Definition at line 108 of file chebyshev.hpp.
References evals(), and integrals().
integrals() [3/3]
virtual void SpectExp::cheby_base::integrals (const double & _lower, const double & upper, std::vector< double > & lower_vec, std::vector< double > & upper_vec, std::vector< double > & vec) inline virtual
Reimplemented in SpectExp::cheby_zero.
Definition at line 123 of file chebyshev.hpp.
References _integrate().
integrate() [1/2]
double SpectExp::cheby_base::integrate () inline
Definition at line 45 of file chebyshev.hpp.
References _integrate(), and evals().
Referenced by integrals(), and SpectExp::cheby_zero::integrals().
integrate() [2/2]
double SpectExp::cheby_base::integrate (const double & lower, const double & upper) inline
Definition at line 57 of file chebyshev.hpp.
References _integrate(), and evals().
show()
virtual void SpectExp::cheby_base::show () inline virtual
Reimplemented in SpectExp::cheby_1st, and SpectExp::cheby_zero.
Definition at line 69 of file chebyshev.hpp.
References cheby_base().
Member Data Documentation
lower
std::shared_ptr<cheby_base> SpectExp::cheby_base::lower
Definition at line 43 of file chebyshev.hpp.
Referenced by SpectExp::cheby_1st::cheby_1st(), SpectExp::cheby_nth::cheby_nth(), SpectExp::cheby_zero::cheby_zero(), and SpectExp::cheby_nth::eval().
order
int SpectExp::cheby_base::order protected
Definition at line 37 of file chebyshev.hpp.
Referenced by SpectExp::cheby_nth::_eval(), SpectExp::cheby_nth::_integrate(), SpectExp::cheby_zero::show(), and SpectExp::cheby_1st::show().
prev
double SpectExp::cheby_base::prev protected
Definition at line 39 of file chebyshev.hpp.
Referenced by SpectExp::cheby_zero::cheby_zero(), SpectExp::cheby_1st::eval(), and SpectExp::cheby_nth::eval().
prev_x
double SpectExp::cheby_base::prev_x protected
Definition at line 38 of file chebyshev.hpp.
Referenced by SpectExp::cheby_nth::eval().
The documentation for this class was generated from the following file:
chebyshev.hpp
[ FATALPRA Home Page(Not Ready Yet!) ] © 2014–2015, FATALPRA Developer Team.