FATALPRA: FATAL::CCF::Combinations Class Reference
FATAL::CCF::Combinations Class Reference
#include <utils.hpp>
Public Member Functions
size_t size () const
unsigned int & operator[] (const unsigned int &i)
std::vector< std::vector< unsigned int > > getAllCombintions (const unsigned int &i) const
Combinations ()=delete
Combinations (const unsigned int &m)
Detailed Description
Definition at line 19 of file utils.hpp.
Constructor & Destructor Documentation
Combinations() [1/2]
FATAL::CCF::Combinations::Combinations () delete
Referenced by getAllCombintions().
Combinations() [2/2]
FATAL::CCF::Combinations::Combinations (const unsigned int & m) inline
Definition at line 53 of file utils.hpp.
Member Function Documentation
getAllCombintions()
std::vector<std::vector<unsigned int> > FATAL::CCF::Combinations::getAllCombintions (const unsigned int & i) const inline
Definition at line 37 of file utils.hpp.
References FATAL::CCF::adder, Combinations(), FATAL::combinations(), FATAL::CCF::func1, FATAL::CCF::func2, and FATAL::CCF::init.
Referenced by FATAL::CCF::Specific_K::Aggregator().
operator[]()
unsigned int& FATAL::CCF::Combinations::operator[] (const unsigned int & i) inline
Definition at line 32 of file utils.hpp.
Referenced by FATAL::CCF::Any_K::get_Q().
size()
size_t FATAL::CCF::Combinations::size () const inline
Definition at line 27 of file utils.hpp.
The documentation for this class was generated from the following file:
utils.hpp
[ FATALPRA Home Page(Not Ready Yet!) ] © 2014–2015, FATALPRA Developer Team.