FATALPRA: SpectExp::interpolate Class Reference
SpectExp::interpolate Class Reference
Base class for Fault Tree Manipulations
This class uses curiously recursive template pattern so as to use multiple solution scheme.
#include <eval.hpp>
Public Member Functions
interpolate ()=delete
interpolate (std::vector< double > _coef, std::pair< double, double > _interval)
double transform (const double &x)
double eval (const double &x)
Detailed Description
Base class for Fault Tree Manipulations
This class uses curiously recursive template pattern so as to use multiple solution scheme.
Definition at line 32 of file eval.hpp.
Constructor & Destructor Documentation
interpolate() [1/2]
SpectExp::interpolate::interpolate () delete
interpolate() [2/2]
SpectExp::interpolate::interpolate (std::vector< double > _coef, std::pair< double, double > _interval) inline
Definition at line 47 of file eval.hpp.
Member Function Documentation
eval()
double SpectExp::interpolate::eval (const double & x) inline
Definition at line 58 of file eval.hpp.
References SpectExp::cheby_base::evals(), and transform().
transform()
double SpectExp::interpolate::transform (const double & x) inline
Definition at line 53 of file eval.hpp.
Referenced by eval(), and SpectExp::integrate::eval().
The documentation for this class was generated from the following file:
eval.hpp
[ FATALPRA Home Page(Not Ready Yet!) ] © 2014–2015, FATALPRA Developer Team.