FATALPRA: FATAL::CCF::MGL< tag > Class Template Reference
FATAL::CCF::MGL< tag > Class Template Reference
#include <MGL.hpp>
Public Member Functions
MGL ()
MGL (const Impact_Vector &IV)
std::vector< double > get_MGLs (const unsigned int &CCCG, const double &rho) const
std::vector< double > get_MGLs (const unsigned int &CCCG, std::function< const double(std::vector< double >)> &rho_functor) const
std::vector< double > get_prob (const double &Q, const unsigned int &CCCG, const double &rho) const
std::vector< double > get_prob (const double &Q, const unsigned int &CCCG, std::function< const double(std::vector< double >)> &rho_functor) const
Static Public Member Functions
static std::vector< double > prob (const double &Q, const std::vector< double > &MGLs)
Detailed Description
template<typename tag>
class FATAL::CCF::MGL< tag >
Definition at line 36 of file MGL.hpp.
Constructor & Destructor Documentation
MGL() [1/2]
template<typename tag > FATAL::CCF::MGL< tag >::MGL ()
MGL() [2/2]
template<typename tag > FATAL::CCF::MGL< tag >::MGL (const Impact_Vector & IV) inline
Definition at line 99 of file MGL.hpp.
Member Function Documentation
get_MGLs() [1/2]
template<typename tag > std::vector<double> FATAL::CCF::MGL< tag >::get_MGLs (const unsigned int & CCCG, const double & rho) const inline
Definition at line 101 of file MGL.hpp.
References FATAL::CCF::Impact_Vector::getImpactVector().
get_MGLs() [2/2]
template<typename tag > std::vector<double> FATAL::CCF::MGL< tag >::get_MGLs (const unsigned int & CCCG, std::function< const double(std::vector< double >)> & rho_functor) const inline
Definition at line 109 of file MGL.hpp.
References FATAL::CCF::Impact_Vector::getImpactVector().
get_prob() [1/2]
template<typename tag > std::vector<double> FATAL::CCF::MGL< tag >::get_prob (const double & Q, const unsigned int & CCCG, const double & rho) const inline
Definition at line 124 of file MGL.hpp.
References FATAL::CCF::MGL< tag >::prob().
get_prob() [2/2]
template<typename tag > std::vector<double> FATAL::CCF::MGL< tag >::get_prob (const double & Q, const unsigned int & CCCG, std::function< const double(std::vector< double >)> & rho_functor) const inline
Definition at line 131 of file MGL.hpp.
References FATAL::CCF::MGL< tag >::prob().
prob()
template<typename tag > static std::vector<double> FATAL::CCF::MGL< tag >::prob (const double & Q, const std::vector< double > & MGLs) inline static
Definition at line 118 of file MGL.hpp.
Referenced by FATAL::CCF::MGL< tag >::get_prob().
The documentation for this class was generated from the following file:
MGL.hpp
[ FATALPRA Home Page(Not Ready Yet!) ] © 2014–2015, FATALPRA Developer Team.