FATALPRA: FATAL::multi::ET_SET Class Reference
FATAL::multi::ET_SET Class Reference
#include <MU.hpp>
Public Member Functions
ET_SET ()
void add_ET (const boost::shared_ptr< ET::ET_BASE > &i_ET)
std::vector< multi_sequence > recursive_seq_const (std::vector< std::vector< boost::shared_ptr< ET::ET_BASE >>>::iterator begin, std::vector< std::vector< boost::shared_ptr< ET::ET_BASE >>>::iterator end)
std::vector< multi_sequence > construct_seq_sets (bool is_ET=true)
Friends
class MUI
Detailed Description
Definition at line 34 of file MU.hpp.
Constructor & Destructor Documentation
ET_SET()
FATAL::multi::ET_SET::ET_SET () inline
default constructor
Definition at line 49 of file MU.hpp.
Member Function Documentation
add_ET()
void FATAL::multi::ET_SET::add_ET (const boost::shared_ptr< ET::ET_BASE > & i_ET) inline
Definition at line 51 of file MU.hpp.
construct_seq_sets()
void FATAL::multi::ET_SET::construct_seq_sets (bool construct_all = true) inline
a function to construct sequence sets for multi unit ET analysis.
Definition at line 109 of file MU.hpp.
References recursive_seq_const().
recursive_seq_const()
std::vector<multi_sequence> FATAL::multi::ET_SET::recursive_seq_const (std::vector< std::vector< boost::shared_ptr< ET::ET_BASE >>>::iterator begin, std::vector< std::vector< boost::shared_ptr< ET::ET_BASE >>>::iterator end) inline
Definition at line 60 of file MU.hpp.
References FATAL::multi::multi_sequence::add().
Referenced by construct_seq_sets().
Friends And Related Function Documentation
MUI
friend class MUI friend
Definition at line 38 of file MU.hpp.
The documentation for this class was generated from the following file:
MU.hpp
[ FATALPRA Home Page(Not Ready Yet!) ] © 2014–2015, FATALPRA Developer Team.