FATALPRA: FATAL::Functor::demand< Dist_Info1 > Class Template Reference
FATAL::Functor::demand< Dist_Info1 > Class Template Reference
#include <Demand.hpp>
Public Member Functions
demand ()=delete
demand (const std::vector< double > &param1)
virtual ~demand ()
double previous ()
double operator() ()
double mean ()
double median ()
double _5th ()
double _95th ()
double operator() (double time)
double mean (double time)
double median (double time)
double _5th (double time)
double _95th (double time)
Public Member Functions inherited from FATAL::Functor::BE_FUNCTOR_BASE
virtual bool is_corr ()
virtual int order ()
virtual bool is_mc_type ()
virtual ~BE_FUNCTOR_BASE ()
virtual FATAL::FATAL_FAILURE_TYPE get_type ()
virtual void set (const int &_index, const int &_unit_number)
virtual bool get_state (const int &trial)
BE_FUNCTOR_BASE ()
BE_FUNCTOR_BASE (const FATAL::FATAL_FAILURE_TYPE &i_type)
template<class T >
boost::shared_ptr< T > upcast ()
double prob (const int &i_int)
Detailed Description
template<class Dist_Info1>
class FATAL::Functor::demand< Dist_Info1 >
a class which is a base class for basic event computation
Template Parameters
Dist_Info1 a template parameter of a distribution type
Dist_Info2 a template parameter of a distribution type
Definition at line 39 of file Demand.hpp.
Constructor & Destructor Documentation
demand() [1/2]
template<class Dist_Info1 > FATAL::Functor::demand< Dist_Info1 >::demand () delete
default constructor deleted
demand() [2/2]
template<class Dist_Info1 > FATAL::Functor::demand< Dist_Info1 >::demand (const std::vector< double > & param1)
default constructor
Parameters
param1 parameters for template parameter 1
Definition at line 100 of file Demand.hpp.
References FATAL::DEMAND_FAILURE.
~demand()
template<class Dist_Info1 > virtual FATAL::Functor::demand< Dist_Info1 >::~demand () inline virtual
default destructor
Definition at line 70 of file Demand.hpp.
Member Function Documentation
_5th() [1/2]
template<class Dist_Info1 > double FATAL::Functor::demand< Dist_Info1 >::_5th () virtual
a function to obtain 5th percentile from distribution
Returns
a 5th percentile of failure
Implements FATAL::Functor::BE_FUNCTOR_BASE.
Definition at line 131 of file Demand.hpp.
Referenced by FATAL::Functor::demand< Dist_Info1 >::previous().
_5th() [2/2]
template<class Dist_Info1 > double FATAL::Functor::demand< Dist_Info1 >::_5th (double time) virtual
a function to obtain 5th percentile from distribution at given time
Parameters
time time passed
Returns
a 5th percentile of failure
Implements FATAL::Functor::BE_FUNCTOR_BASE.
Definition at line 180 of file Demand.hpp.
_95th() [1/2]
template<class Dist_Info1 > double FATAL::Functor::demand< Dist_Info1 >::_95th () virtual
a function to obtain 95th percentile from distribution
Returns
a 95th percentile of failure
Implements FATAL::Functor::BE_FUNCTOR_BASE.
Definition at line 139 of file Demand.hpp.
Referenced by FATAL::Functor::demand< Dist_Info1 >::previous().
_95th() [2/2]
template<class Dist_Info1 > double FATAL::Functor::demand< Dist_Info1 >::_95th (double time) virtual
a function to obtain random probability from distribution at given time
Parameters
time time passed
Returns
a 95th percentile of failure
Implements FATAL::Functor::BE_FUNCTOR_BASE.
Definition at line 191 of file Demand.hpp.
mean() [1/2]
template<class Dist_Info1 > double FATAL::Functor::demand< Dist_Info1 >::mean () virtual
a function to obtain mean value from distribution
Returns
a mean probability of failure
Implements FATAL::Functor::BE_FUNCTOR_BASE.
Definition at line 115 of file Demand.hpp.
Referenced by FATAL::Functor::demand< Dist_Info1 >::previous().
mean() [2/2]
template<class Dist_Info1 > double FATAL::Functor::demand< Dist_Info1 >::mean (double time) virtual
a function to obtain mean probability from distribution at given time
Parameters
time time passed
Returns
mean probability at given time
Implements FATAL::Functor::BE_FUNCTOR_BASE.
Definition at line 158 of file Demand.hpp.
median() [1/2]
template<class Dist_Info1 > double FATAL::Functor::demand< Dist_Info1 >::median () virtual
a function to obtain median value from distribution
Returns
a median probability of failure
Implements FATAL::Functor::BE_FUNCTOR_BASE.
Definition at line 123 of file Demand.hpp.
Referenced by FATAL::Functor::demand< Dist_Info1 >::previous().
median() [2/2]
template<class Dist_Info1 > double FATAL::Functor::demand< Dist_Info1 >::median (double time) virtual
a function to obtain median probability from distribution at given time
Parameters
time time passed
Returns
a median probability of failure
Implements FATAL::Functor::BE_FUNCTOR_BASE.
Definition at line 169 of file Demand.hpp.
operator()() [1/2]
template<class Dist_Info1 > double FATAL::Functor::demand< Dist_Info1 >::operator() () virtual
a function to obtain random value from distribution
Returns
a random probability of failure
Reimplemented from FATAL::Functor::BE_FUNCTOR_BASE.
Definition at line 107 of file Demand.hpp.
Referenced by FATAL::Functor::demand< Dist_Info1 >::previous().
operator()() [2/2]
template<class Dist_Info1 > double FATAL::Functor::demand< Dist_Info1 >::operator() (double time) virtual
a function to obtain random probability from distribution at given time
Parameters
time time passed
Returns
a random probability from distribution at given time
Reimplemented from FATAL::Functor::BE_FUNCTOR_BASE.
Definition at line 147 of file Demand.hpp.
previous()
template<class Dist_Info1 > double FATAL::Functor::demand< Dist_Info1 >::previous () inline virtual
obtan a probability of previos calculation
Returns
a probability of previous state
Implements FATAL::Functor::BE_FUNCTOR_BASE.
Definition at line 74 of file Demand.hpp.
References FATAL::Functor::demand< Dist_Info1 >::_5th(), FATAL::Functor::demand< Dist_Info1 >::_95th(), FATAL::Functor::demand< Dist_Info1 >::mean(), FATAL::Functor::demand< Dist_Info1 >::median(), and FATAL::Functor::demand< Dist_Info1 >::operator()().
The documentation for this class was generated from the following file:
Demand.hpp
[ FATALPRA Home Page(Not Ready Yet!) ] © 2014–2015, FATALPRA Developer Team.