FATALPRA: SpectExp::adaptive::simpson Class Reference
SpectExp::adaptive::simpson Class Reference
#include <adaptive_simpson.hpp>
Public Member Functions
double get_result ()
simpson (std::function< double(double)> &f, const double lower, const double upper, const double &epsilon=1E-15, const int &max_depth=1000, const int &min_depth=20)
double _simpson (const double &lower, const double &middle, const double &upper, const double &diff, const double &prev_simpson, const double &f_lower, const double &f_middle, const double &f_upper, const double &epsilon, const int &current_depth=1, const int &min_depth=20)
Detailed Description
Definition at line 25 of file adaptive_simpson.hpp.
Constructor & Destructor Documentation
simpson()
SpectExp::adaptive::simpson::simpson (std::function< double(double)> & f, const double lower, const double upper, const double & epsilon = 1E-15, const int & max_depth = 1000, const int & min_depth = 20) inline
Definition at line 42 of file adaptive_simpson.hpp.
References _simpson().
Member Function Documentation
_simpson()
double SpectExp::adaptive::simpson::_simpson (const double & lower, const double & middle, const double & upper, const double & diff, const double & prev_simpson, const double & f_lower, const double & f_middle, const double & f_upper, const double & epsilon, const int & current_depth = 1, const int & min_depth = 20) inline
Definition at line 59 of file adaptive_simpson.hpp.
Referenced by SpectExp::adaptive::t_simpson< value >::_simpson(), simpson(), and SpectExp::adaptive::t_simpson< value >::t_simpson().
get_result()
double SpectExp::adaptive::simpson::get_result () inline
Definition at line 37 of file adaptive_simpson.hpp.
Referenced by FATAL::prob::logit_normal::mean(), and FATAL::prob::logit_normal::variance().
The documentation for this class was generated from the following file:
adaptive_simpson.hpp
[ FATALPRA Home Page(Not Ready Yet!) ] © 2014–2015, FATALPRA Developer Team.