FATALPRA: FATAL::misc::FT_GEN Class Reference
FATAL::misc::FT_GEN Class Reference
#include <FT_generator.hpp>
Public Member Functions
void max_duplicate_num (int num)
FT_GEN ()
FT_GEN (long long seed)
void set_russian (double val)
void define_decay_rate (double rate)
int min_depth ()
std::pair< int, int > expected_num ()
boost::filesystem::path get_path ()
std::vector< std::pair< boost::shared_ptr< FT::BE >, int > > get_be ()
void define_number_of_elements (int i, int j)
void add_type (boost::shared_ptr< FT::FT_BASE > GATE_TYPE, double occurence_frequency)
void num_be (int num, double upper=1, double lower=0)
void set_min_depth (int depth)
int random_be ()
int num_swap ()
void be_prob (double val)
boost::shared_ptr< FT::FT_BASE > generate (bool initial=true)
void generate_file (std::string suffix, int i, std::string folder_name)
boost::shared_ptr< FT::FT_BASE > recursive_generate (const double russian, FT_TYPE previous, bool initial, bool &fail, int depth, const int &max_depth)
void reset ()
int max_duplicity ()
int swap_num ()
boost::shared_ptr< FT::FT_BASE > gate_select ()
boost::shared_ptr< FT::FT_BASE > random_gate (boost::shared_ptr< FT::FT_BASE > compare)
std::pair< int, boost::shared_ptr< FT::FT_BASE > > select_be (boost::shared_ptr< FT::FT_BASE > &FT)
Detailed Description
Definition at line 57 of file FT_generator.hpp.
Constructor & Destructor Documentation
FT_GEN() [1/2]
FATAL::misc::FT_GEN::FT_GEN () inline
default constructor
Definition at line 160 of file FT_generator.hpp.
FT_GEN() [2/2]
FATAL::misc::FT_GEN::FT_GEN (long long seed) inline
a constructor with an initial seed for reproductivity
Parameters
seed an initial seed for reproductivity purpose.
Definition at line 174 of file FT_generator.hpp.
Member Function Documentation
add_type()
void FATAL::misc::FT_GEN::add_type (boost::shared_ptr< FT::FT_BASE > GATE_TYPE, double occurence_frequency)
add a type of a gate in a randomized fault tree with its occurence probability
Parameters
GATE_TYPE a shared pointer of a gate to be used in a raondmized fault tree `
occurence_frequency occurence frequency of a gate specified
Definition at line 429 of file FT_generator.hpp.
Referenced by get_be().
be_prob()
void FATAL::misc::FT_GEN::be_prob (double val) inline
Definition at line 244 of file FT_generator.hpp.
References generate(), generate_file(), max_duplicity(), recursive_generate(), reset(), and swap_num().
define_decay_rate()
void FATAL::misc::FT_GEN::define_decay_rate (double rate)
set a decay_rate such that decay_rate = 1/mean * rate
Parameters
rate a rate at which an expected number of gates decreases
Definition at line 368 of file FT_generator.hpp.
Referenced by set_russian().
define_number_of_elements()
void FATAL::misc::FT_GEN::define_number_of_elements (int i, int j)
set an interval of a uniform distribution to select a number of elements in each gate
Parameters
i lower limit of a distribution
j upper limit of a distribution
Definition at line 406 of file FT_generator.hpp.
Referenced by get_be().
expected_num()
std::pair< int, int > FATAL::misc::FT_GEN::expected_num ()
Definition at line 379 of file FT_generator.hpp.
Referenced by min_depth().
gate_select()
boost::shared_ptr<FT::FT_BASE> FATAL::misc::FT_GEN::gate_select () inline
Definition at line 258 of file FT_generator.hpp.
References random_gate().
Referenced by recursive_generate().
generate()
boost::shared_ptr< FT::FT_BASE > FATAL::misc::FT_GEN::generate (bool initial = true)
Definition at line 500 of file FT_generator.hpp.
References FATAL::CND, max_duplicity(), num_swap(), random_gate(), recursive_generate(), reset(), select_be(), and swap_num().
Referenced by be_prob().
generate_file()
void FATAL::misc::FT_GEN::generate_file (std::string suffix, int i, std::string folder_name)
Definition at line 611 of file FT_generator.hpp.
References FATAL::misc::FT_O::generate_file().
Referenced by be_prob().
get_be()
FATAL::misc::FT_GEN::get_be () inline
get a set of all basic events in a randomized fault tree
Definition at line 214 of file FT_generator.hpp.
References add_type(), define_number_of_elements(), and num_be().
get_path()
FATAL::misc::FT_GEN::get_path () inline
get a path to a randomized fault tree
Definition at line 208 of file FT_generator.hpp.
max_duplicate_num()
void FATAL::misc::FT_GEN::max_duplicate_num (int num) inline
Definition at line 154 of file FT_generator.hpp.
max_duplicity()
int FATAL::misc::FT_GEN::max_duplicity ()
Definition at line 344 of file FT_generator.hpp.
Referenced by be_prob(), and generate().
min_depth()
FATAL::misc::FT_GEN::min_depth () inline
an expected number of minimal depth of a randomized fault tree
Definition at line 196 of file FT_generator.hpp.
References expected_num().
num_be()
void FATAL::misc::FT_GEN::num_be (int num, double upper = 1, double lower = 0)
define a number of basic events in a randomized fault tree
Definition at line 441 of file FT_generator.hpp.
Referenced by get_be().
num_swap()
int FATAL::misc::FT_GEN::num_swap ()
Definition at line 488 of file FT_generator.hpp.
Referenced by generate(), and set_min_depth().
random_be()
int FATAL::misc::FT_GEN::random_be ()
Definition at line 464 of file FT_generator.hpp.
Referenced by recursive_generate(), and set_min_depth().
random_gate()
boost::shared_ptr< FT::FT_BASE > FATAL::misc::FT_GEN::random_gate (boost::shared_ptr< FT::FT_BASE > compare) inline
Definition at line 296 of file FT_generator.hpp.
Referenced by gate_select(), and generate().
recursive_generate()
boost::shared_ptr< FT::FT_BASE > FATAL::misc::FT_GEN::recursive_generate (const double russian, FT_TYPE previous, bool initial, bool & fail, int depth, const int & max_depth)
Definition at line 617 of file FT_generator.hpp.
References gate_select(), FATAL::KN, FATAL::NKN, rand_string(), and random_be().
Referenced by be_prob(), and generate().
reset()
void FATAL::misc::FT_GEN::reset ()
Definition at line 356 of file FT_generator.hpp.
Referenced by be_prob(), and generate().
select_be()
std::pair<int, boost::shared_ptr<FT::FT_BASE> > FATAL::misc::FT_GEN::select_be (boost::shared_ptr< FT::FT_BASE > & FT) inline
Definition at line 265 of file FT_generator.hpp.
Referenced by generate().
set_min_depth()
void FATAL::misc::FT_GEN::set_min_depth (int depth) inline
Definition at line 238 of file FT_generator.hpp.
References num_swap(), and random_be().
set_russian()
FATAL::misc::FT_GEN::set_russian (double val) inline
set a value for russian roulette. note that the value decays in each iteration.
Parameters
val an initial russian roulette probability. can be greater than 1.
Definition at line 183 of file FT_generator.hpp.
References define_decay_rate().
swap_num()
int FATAL::misc::FT_GEN::swap_num ()
Definition at line 332 of file FT_generator.hpp.
Referenced by be_prob(), and generate().
The documentation for this class was generated from the following file:
FT_generator.hpp
[ FATALPRA Home Page(Not Ready Yet!) ] © 2014–2015, FATALPRA Developer Team.