FATALPRA: FATAL::ET::ET_BASE Class Reference
FATAL::ET::ET_BASE Class Reference abstract
base class for event trees.
#include <ET_BASE.hpp>
Public Member Functions
template<class T >
boost::shared_ptr< T > cast ()
virtual void assign_type (CD_SEQ _ID)
virtual boost::shared_ptr< FATAL::FT::FT_BASE > get_Equiv_FT ()
virtual void print ()
virtual void null2seq (bool isIE=false)
virtual void prep (bool is_IE=false)
virtual void prep (std::vector< boost::shared_ptr< FT::FT_BASE >> i_FTs, std::vector< bool > i_branch_info)
bool is_branch_null (bool state)
ET_BASE ()
ET_BASE (const boost::shared_ptr< ET_BASE > &i_success, const boost::shared_ptr< ET_BASE > &i_fail, const boost::shared_ptr< FATAL::FT::FT_BASE > &i_FT)
ET_BASE (const std::string &i_name)
boost::shared_ptr< FT::FT_BASE > & getFT ()
void assign (const boost::shared_ptr< ET_BASE > i_success, const boost::shared_ptr< ET_BASE > i_fail, bool force=false)
void assign (const boost::shared_ptr< FT::FT_BASE > &i_FT)
void assign (bool path, const boost::shared_ptr< ET_BASE > i_ET)
boost::shared_ptr< ET_BASE > getET (bool status)
void clear ()
void assign_FT (const boost::shared_ptr< FT::FT_BASE > &i_FT)
virtual ET_TYPE GET_ET_TYPE ()
virtual bool is_cyclic ()=0
virtual bool is_cyclic (std::vector< boost::shared_ptr< ET_BASE >> &targets)=0
virtual ~ET_BASE ()
virtual std::vector< boost::shared_ptr< ET_BASE > > get_seq (bool is_IE=false, bool validate=true)
virtual void auto_replace (std::vector< boost::shared_ptr< ET_BASE >> &sequences)
virtual bool is_replacible (bool state)
Public Member Functions inherited from FATAL::ET::ET_PROPERTY
ET_PROPERTY ()
ET_PROPERTY (std::string i_evt)
void set_evt (const std::string &i_name)
std::string get_evt ()
Protected Attributes
boost::shared_ptr< FT::FT_BASE > FT
boost::shared_ptr< ET_BASE > success
boost::shared_ptr< ET_BASE > fail
Detailed Description
base class for event trees.
Definition at line 38 of file ET_BASE.hpp.
Constructor & Destructor Documentation
ET_BASE() [1/3]
FATAL::ET::ET_BASE::ET_BASE () inline
default constructor
Definition at line 193 of file ET_BASE.hpp.
ET_BASE() [2/3]
FATAL::ET::ET_BASE::ET_BASE (const boost::shared_ptr< ET_BASE > & i_success, const boost::shared_ptr< ET_BASE > & i_fail, const boost::shared_ptr< FATAL::FT::FT_BASE > & i_FT)
default constructor
Definition at line 429 of file ET_BASE.hpp.
ET_BASE() [3/3]
FATAL::ET::ET_BASE::ET_BASE (const std::string & i_name) inline
default constructor
Definition at line 201 of file ET_BASE.hpp.
~ET_BASE()
virtual FATAL::ET::ET_BASE::~ET_BASE () inline virtual
default constructor
Definition at line 277 of file ET_BASE.hpp.
References auto_replace(), and get_seq().
Member Function Documentation
assign() [1/3]
void FATAL::ET::ET_BASE::assign (const boost::shared_ptr< ET_BASE > i_success, const boost::shared_ptr< ET_BASE > i_fail, bool force = false)
Definition at line 442 of file ET_BASE.hpp.
References fail, and success.
Referenced by assign(), and getFT().
assign() [2/3]
void FATAL::ET::ET_BASE::assign (const boost::shared_ptr< FT::FT_BASE > & i_FT) inline
Definition at line 218 of file ET_BASE.hpp.
References assign(), assign_FT(), clear(), and getET().
assign() [3/3]
void FATAL::ET::ET_BASE::assign (bool path, const boost::shared_ptr< ET_BASE > i_ET)
path: true = success path, false = failure path
Parameters
path specify a path to be assigned
i_ET an event tree to be added
Definition at line 466 of file ET_BASE.hpp.
References fail, and success.
assign_FT()
void FATAL::ET::ET_BASE::assign_FT (const boost::shared_ptr< FT::FT_BASE > & i_FT)
brief a function to assign FT
Parameters
i_FT a fault to be assigned
Definition at line 520 of file ET_BASE.hpp.
References FT.
Referenced by assign().
assign_type()
void FATAL::ET::ET_BASE::assign_type (CD_SEQ _ID) inline virtual
assign a CD_SEQ type
Parameters
_ID core damage sequence ID
Reimplemented in FATAL::ET::SEQ.
Definition at line 82 of file ET_BASE.hpp.
auto_replace()
void FATAL::ET::ET_BASE::auto_replace (std::vector< boost::shared_ptr< ET_BASE >> & sequences) virtual
this function automatically replace if a null branch with sequence auto replacement rules are below:
if both success and failure branches are null, then this branch is replaced with sequence
either one of branch is null, only the null branch is replaced.
Warning
Do not call this function on IE.
Definition at line 197 of file SEQ.hpp.
References fail, is_replacible(), FATAL::SEQ, and success.
Referenced by ~ET_BASE().
cast()
template<class T > boost::shared_ptr<T> FATAL::ET::ET_BASE::cast () inline
Definition at line 61 of file ET_BASE.hpp.
clear()
void FATAL::ET::ET_BASE::clear ()
clear memory
Definition at line 514 of file ET_BASE.hpp.
References fail, and success.
Referenced by assign().
get_Equiv_FT()
virtual boost::shared_ptr<FATAL::FT::FT_BASE> FATAL::ET::ET_BASE::get_Equiv_FT () inline virtual
Reimplemented in FATAL::ET::SEQ.
Definition at line 88 of file ET_BASE.hpp.
GET_ET_TYPE()
ET_TYPE FATAL::ET::ET_BASE::GET_ET_TYPE () inline virtual
obtain an ET_TYPE
Returns
ET_TYPE::UNDEF
Reimplemented from FATAL::ET::ET_PROPERTY.
Reimplemented in FATAL::ET::SEQ, FATAL::ET::IE, and FATAL::ET::ET.
Definition at line 259 of file ET_BASE.hpp.
References is_cyclic(), and FATAL::UNDEF.
get_seq()
std::vector< boost::shared_ptr< ET_BASE > > FATAL::ET::ET_BASE::get_seq (bool is_IE = false, bool validate = true) virtual
Reimplemented in FATAL::ET::IE, and FATAL::ET::SEQ.
Definition at line 539 of file ET_BASE.hpp.
References fail, null2seq(), prep(), and success.
Referenced by FATAL::ET::IE::get_seq(), and ~ET_BASE().
getET()
boost::shared_ptr< ET_BASE > FATAL::ET::ET_BASE::getET (bool status)
get a success or failure branch of ET
Parameters
status determine which path should be returned. if status is true, then success path is returned. otherwise, failure path.
Returns
a specified branching event tree
Definition at line 490 of file ET_BASE.hpp.
References fail, and success.
Referenced by assign().
getFT()
boost::shared_ptr< FT::FT_BASE > & FATAL::ET::ET_BASE::getFT () inline
get a FT
Returns
a reference to shared pointer of a fault tree
Definition at line 208 of file ET_BASE.hpp.
References assign(), and FT.
is_branch_null()
bool FATAL::ET::ET_BASE::is_branch_null (bool state) inline
check if a branch is null
Returns
true if a specified branch is null
Parameters
state specify a branch to check
Definition at line 190 of file ET_BASE.hpp.
Referenced by FATAL::ET::IE::is_replacible(), and is_replacible().
is_cyclic() [1/2]
bool FATAL::ET::ET_BASE::is_cyclic () pure virtual
check if ET is cyclic
Returns
true if cyclic. Otherwise false.
Implemented in FATAL::ET::SEQ, FATAL::ET::IE, and FATAL::ET::ET.
Referenced by GET_ET_TYPE().
is_cyclic() [2/2]
bool FATAL::ET::ET_BASE::is_cyclic (std::vector< boost::shared_ptr< ET_BASE >> & targets) pure virtual
check if ET is cyclic
Returns
true if cyclic. Otherwise, false.
Parameters
targets a recorded path of event trees
Implemented in FATAL::ET::SEQ, FATAL::ET::IE, and FATAL::ET::ET.
is_replacible()
virtual bool FATAL::ET::ET_BASE::is_replacible (bool state) inline virtual
Reimplemented in FATAL::ET::IE.
Definition at line 294 of file ET_BASE.hpp.
References is_branch_null(), and FATAL::SEQ.
Referenced by auto_replace().
null2seq()
void FATAL::ET::ET_BASE::null2seq (bool isIE = false) virtual
replace all nullptr to sequences
Warning
this function replaces all nullptr with shared pointers of ET::SEQ class.
Reimplemented in FATAL::ET::SEQ, and FATAL::ET::IE.
Definition at line 238 of file SEQ.hpp.
References fail, and success.
Referenced by get_seq(), FATAL::ET::IE::null2seq(), and print().
prep() [1/2]
void FATAL::ET::ET_BASE::prep (bool is_IE = false) virtual
construct sequence information for analysis
Parameters
is_IE true if ET is an initialting event. Otherwise, false.
Reimplemented in FATAL::ET::IE, and FATAL::ET::SEQ.
Definition at line 381 of file ET_BASE.hpp.
References fail, FT, and success.
Referenced by get_seq(), FATAL::ET::IE::prep(), and print().
prep() [2/2]
void FATAL::ET::ET_BASE::prep (std::vector< boost::shared_ptr< FT::FT_BASE >> i_FTs, std::vector< bool > i_branch_info) virtual
construct sequence information for analysis
Todo:
move this function to private member
Parameters
i_FTs a set of fault trees in previous event trees in sequence
i_branch_info information on previous event trees in sequence
Reimplemented in FATAL::ET::SEQ, and FATAL::ET::IE.
Definition at line 342 of file ET_BASE.hpp.
References fail, FT, and success.
print()
virtual void FATAL::ET::ET_BASE::print () inline virtual
Reimplemented in FATAL::ET::IE, and FATAL::ET::SEQ.
Definition at line 96 of file ET_BASE.hpp.
References FATAL::ET::ET_PROPERTY::get_evt(), null2seq(), prep(), and FATAL::SEQ.
Member Data Documentation
fail
boost::shared_ptr<ET_BASE> FATAL::ET::ET_BASE::fail protected
Parameters
fail failure path
Definition at line 50 of file ET_BASE.hpp.
Referenced by FATAL::ET::IE::assign(), assign(), auto_replace(), FATAL::ET::ET::clear(), FATAL::ET::IE::clear(), clear(), FATAL::ET::ET::ET(), get_seq(), FATAL::ET::IE::getET(), getET(), FATAL::ET::IE::IE(), FATAL::ET::ET::is_cyclic(), FATAL::ET::IE::is_cyclic(), FATAL::ET::IE::is_replacible(), null2seq(), FATAL::ET::IE::prep(), prep(), and FATAL::ET::IE::print().
FT
boost::shared_ptr<FT::FT_BASE> FATAL::ET::ET_BASE::FT protected
Parameters
FT Fault Tree, which decide the system fails or successes
Definition at line 46 of file ET_BASE.hpp.
Referenced by assign_FT(), FATAL::ET::ET::ET(), getFT(), FATAL::ET::IE::IE(), FATAL::ET::IE::prep(), and prep().
success
boost::shared_ptr<ET_BASE> FATAL::ET::ET_BASE::success protected
Parameters
success success path
Definition at line 48 of file ET_BASE.hpp.
Referenced by assign(), auto_replace(), FATAL::ET::ET::clear(), clear(), FATAL::ET::ET::ET(), get_seq(), getET(), FATAL::ET::ET::is_cyclic(), null2seq(), and prep().
The documentation for this class was generated from the following files:
ET_BASE.hpp
SEQ.hpp
[ FATALPRA Home Page(Not Ready Yet!) ] © 2014–2015, FATALPRA Developer Team.