FATALPRA: FATAL::DD::without_map< MGR, XDD > Class Template Reference
FATAL::DD::without_map< MGR, XDD > Class Template Reference
#include <WITHOUT_MAP.hpp>
Public Member Functions
without_map ()
without_map (const boost::shared_ptr< MGR > &i_mgr)
XDD without (const XDD &F, const XDD &G, const boost::shared_ptr< dd_mgr< MGR, XDD >> &p_mgr)
XDD minsol_rauzy (const XDD &F, boost::shared_ptr< dd_mgr< MGR, XDD >> &p_mgr)
Detailed Description
template<typename MGR, typename XDD>
class FATAL::DD::without_map< MGR, XDD >
Definition at line 33 of file WITHOUT_MAP.hpp.
Constructor & Destructor Documentation
without_map() [1/2]
template<typename MGR, typename XDD> FATAL::DD::without_map< MGR, XDD >::without_map () inline
Definition at line 53 of file WITHOUT_MAP.hpp.
without_map() [2/2]
template<typename MGR, typename XDD> FATAL::DD::without_map< MGR, XDD >::without_map (const boost::shared_ptr< MGR > & i_mgr) inline
Definition at line 56 of file WITHOUT_MAP.hpp.
Member Function Documentation
minsol_rauzy()
template<typename MGR, typename XDD> XDD FATAL::DD::without_map< MGR, XDD >::minsol_rauzy (const XDD & F, boost::shared_ptr< dd_mgr< MGR, XDD >> & p_mgr) inline
Definition at line 111 of file WITHOUT_MAP.hpp.
References FATAL::V, and FATAL::DD::without_map< MGR, XDD >::without().
Referenced by FATAL::DD::dd_mgr< MGR, XDD >::minsol_rauzy().
without()
template<typename MGR, typename XDD> XDD FATAL::DD::without_map< MGR, XDD >::without (const XDD & F, const XDD & G, const boost::shared_ptr< dd_mgr< MGR, XDD >> & p_mgr) inline
Definition at line 59 of file WITHOUT_MAP.hpp.
References FATAL::V.
Referenced by FATAL::DD::without_map< MGR, XDD >::minsol_rauzy().
The documentation for this class was generated from the following file:
WITHOUT_MAP.hpp
[ FATALPRA Home Page(Not Ready Yet!) ] © 2014–2015, FATALPRA Developer Team.