FATALPRA: FATAL::CCF Namespace Reference
FATAL::CCF Namespace Reference
Classes
class agg_base
class alpha
class Any_K
class beta
class Combinations
class Datum
a class to hold each historical CCF event
class Impact_Vector
class MGL
struct non_staggered
class Specific_K
struct staggered
Enumerations
enum Type { Type::IND = 1, Type::CCF = 2 }
Functions
const double rho_NUREGCR_6268 (const std::vector< double > &F)
const double rho_5500_vol3 (const std::vector< double > &F)
Variables
auto adder = [](std::vector<std::vector<unsigned int>> & vecs, std::vector<unsigned int> &vec) {vecs.push_back(vec); }
auto init = [](std::vector<unsigned int> & _val) {_val.clear(); }
auto func1 = [](std::vector<unsigned int> &vec, const unsigned int & j, double p) {vec.push_back(j); }
auto func2 = [](std::vector<unsigned int> &vec, const unsigned int & j, double p) {}
Enumeration Type Documentation
Type
enum FATAL::CCF::Type strong
Enumerator
IND
CCF
Definition at line 34 of file impactVector.hpp.
Function Documentation
rho_5500_vol3()
const double FATAL::CCF::rho_5500_vol3 (const std::vector< double > & F)
Definition at line 447 of file impactVector.hpp.
rho_NUREGCR_6268()
const double FATAL::CCF::rho_NUREGCR_6268 (const std::vector< double > & F)
Definition at line 420 of file impactVector.hpp.
Variable Documentation
adder
auto FATAL::CCF::adder = [](std::vector<std::vector<unsigned int>> & vecs, std::vector<unsigned int> &vec) {vecs.push_back(vec); }
Definition at line 11 of file utils.hpp.
Referenced by FATAL::CCF::Combinations::getAllCombintions().
func1
auto FATAL::CCF::func1 = [](std::vector<unsigned int> &vec, const unsigned int & j, double p) {vec.push_back(j); }
Definition at line 15 of file utils.hpp.
Referenced by FATAL::CCF::Datum::_F(), FATAL::combinations(), and FATAL::CCF::Combinations::getAllCombintions().
func2
auto FATAL::CCF::func2 = [](std::vector<unsigned int> &vec, const unsigned int & j, double p) {}
Definition at line 17 of file utils.hpp.
Referenced by FATAL::CCF::Datum::_F(), FATAL::combinations(), and FATAL::CCF::Combinations::getAllCombintions().
init
auto FATAL::CCF::init = [](std::vector<unsigned int> & _val) {_val.clear(); }
Definition at line 13 of file utils.hpp.
Referenced by FATAL::CCF::Datum::_F(), FATAL::combinations(), FATAL::misc::FT_I::FT_I(), and FATAL::CCF::Combinations::getAllCombintions().
[ FATALPRA Home Page(Not Ready Yet!) ] © 2014–2015, FATALPRA Developer Team.