FATALPRA: FATAL::multi::multi_sequence Class Reference
FATAL::multi::multi_sequence Class Reference
#include <multi_sequence.hpp>
Public Member Functions
multi_sequence ()
boost::shared_ptr< ET::SEQ > add_seqs (boost::shared_ptr< ET::SEQ > seq1, boost::shared_ptr< ET::SEQ > seq2)
std::tuple< SEQ_STATUS_SET, boost::shared_ptr< ET::SEQ > > get ()
std::tuple< SEQ_STATUS_SET, boost::shared_ptr< FT::FT_BASE > > get_ft ()
void add (const boost::shared_ptr< ET::ET_BASE > &i_seq)
Detailed Description
Definition at line 25 of file multi_sequence.hpp.
Constructor & Destructor Documentation
multi_sequence()
FATAL::multi::multi_sequence::multi_sequence () inline
Definition at line 33 of file multi_sequence.hpp.
Member Function Documentation
add()
void FATAL::multi::multi_sequence::add (const boost::shared_ptr< ET::ET_BASE > & i_seq) inline
Definition at line 89 of file multi_sequence.hpp.
References FATAL::multi::SEQ_STATUS_SET::add(), and FATAL::SEQ.
Referenced by FATAL::multi::ET_SET::recursive_seq_const().
add_seqs()
boost::shared_ptr<ET::SEQ> FATAL::multi::multi_sequence::add_seqs (boost::shared_ptr< ET::SEQ > seq1, boost::shared_ptr< ET::SEQ > seq2) inline
Definition at line 37 of file multi_sequence.hpp.
Referenced by get().
get()
std::tuple<SEQ_STATUS_SET, boost::shared_ptr<ET::SEQ> > FATAL::multi::multi_sequence::get () inline
Definition at line 57 of file multi_sequence.hpp.
References add_seqs().
get_ft()
std::tuple<SEQ_STATUS_SET, boost::shared_ptr<FT::FT_BASE> > FATAL::multi::multi_sequence::get_ft () inline
Definition at line 84 of file multi_sequence.hpp.
The documentation for this class was generated from the following file:
multi_sequence.hpp
[ FATALPRA Home Page(Not Ready Yet!) ] © 2014–2015, FATALPRA Developer Team.