FATALPRA: FATAL::Functor::mc_fragility< capacity_type, response_type > Class Template Reference
FATAL::Functor::mc_fragility< capacity_type, response_type > Class Template Reference
#include <Fragility.hpp>
Public Member Functions
bool is_corr ()
int order ()
void set (const int &_index, const int &_unit_number)
bool is_mc_type ()
bool get_state (const int &trial)
mc_fragility (const std::vector< double > &param1, const std::vector< double > &param2)
double previous ()
double mean ()
double median ()
double _5th ()
double _95th ()
double mean (double time)
double median (double time)
double _5th (double time)
double _95th (double time)
int count () const
Public Member Functions inherited from FATAL::Functor::BE_FUNCTOR_BASE
virtual ~BE_FUNCTOR_BASE ()
virtual FATAL::FATAL_FAILURE_TYPE get_type ()
BE_FUNCTOR_BASE ()
BE_FUNCTOR_BASE (const FATAL::FATAL_FAILURE_TYPE &i_type)
template<class T >
boost::shared_ptr< T > upcast ()
virtual double operator() ()
virtual double operator() (double time)
double prob (const int &i_int)
Detailed Description
template<class capacity_type, class response_type>
class FATAL::Functor::mc_fragility< capacity_type, response_type >
seismic fragility class with correlated response and capacity
Template Parameters
capacity_type corr_rand or ind_rand<pdf>
response_type corr_rand pr ind_rand<pdf>
Definition at line 263 of file Fragility.hpp.
Constructor & Destructor Documentation
mc_fragility()
template<class response_type , class capacity_type > FATAL::Functor::mc_fragility< response_type, capacity_type >::mc_fragility (const std::vector< double > & param1, const std::vector< double > & param2)
default constructor
Definition at line 546 of file Fragility.hpp.
References FATAL::FRAGILITY.
Member Function Documentation
_5th() [1/2]
template<class response_type , class capacity_type > double FATAL::Functor::mc_fragility< response_type, capacity_type >::_5th () virtual
a function to obtain 5th percentile from distribution
Returns
a 5th percentile of failure
Implements FATAL::Functor::BE_FUNCTOR_BASE.
Definition at line 566 of file Fragility.hpp.
Referenced by FATAL::Functor::mc_fragility< capacity_type, response_type >::_5th().
_5th() [2/2]
template<class response_type , class capacity_type > double FATAL::Functor::mc_fragility< response_type, capacity_type >::_5th (double time) virtual
a function to obtain 5th percentile from distribution at given time
Parameters
time time passed
Returns
a 5th percentile of failure
Implements FATAL::Functor::BE_FUNCTOR_BASE.
Definition at line 594 of file Fragility.hpp.
References FATAL::Functor::mc_fragility< capacity_type, response_type >::_5th().
_95th() [1/2]
template<class response_type , class capacity_type > double FATAL::Functor::mc_fragility< response_type, capacity_type >::_95th () virtual
a function to obtain 95th percentile from distribution
Returns
a 95th percentile of failure
Implements FATAL::Functor::BE_FUNCTOR_BASE.
Definition at line 574 of file Fragility.hpp.
Referenced by FATAL::Functor::mc_fragility< capacity_type, response_type >::_95th().
_95th() [2/2]
template<class response_type , class capacity_type > double FATAL::Functor::mc_fragility< response_type, capacity_type >::_95th (double time) virtual
a function to obtain random probability from distribution at given time
Parameters
time time passed
Returns
a 95th percentile of failure
Implements FATAL::Functor::BE_FUNCTOR_BASE.
Definition at line 600 of file Fragility.hpp.
References FATAL::Functor::mc_fragility< capacity_type, response_type >::_95th().
count()
template<class capacity_type , class response_type > int FATAL::Functor::mc_fragility< capacity_type, response_type >::count () const inline
Definition at line 389 of file Fragility.hpp.
get_state()
template<class response_type , class capacity_type > bool FATAL::Functor::mc_fragility< response_type, capacity_type >::get_state (const int & trial) virtual
Returns
a state of a component if it fails or not.
Reimplemented from FATAL::Functor::BE_FUNCTOR_BASE.
Definition at line 520 of file Fragility.hpp.
is_corr()
template<class capacity_type , class response_type > bool FATAL::Functor::mc_fragility< capacity_type, response_type >::is_corr () inline virtual
Reimplemented from FATAL::Functor::BE_FUNCTOR_BASE.
Definition at line 331 of file Fragility.hpp.
is_mc_type()
template<class capacity_type , class response_type > bool FATAL::Functor::mc_fragility< capacity_type, response_type >::is_mc_type () inline virtual
Reimplemented from FATAL::Functor::BE_FUNCTOR_BASE.
Definition at line 353 of file Fragility.hpp.
References FATAL::Functor::BE_FUNCTOR_BASE::get_state().
mean() [1/2]
template<class response_type , class capacity_type > double FATAL::Functor::mc_fragility< response_type, capacity_type >::mean () virtual
a function to obtain mean value from distribution
Returns
a mean probability of failure
Implements FATAL::Functor::BE_FUNCTOR_BASE.
Definition at line 550 of file Fragility.hpp.
Referenced by FATAL::Functor::mc_fragility< capacity_type, response_type >::mean().
mean() [2/2]
template<class response_type , class capacity_type > double FATAL::Functor::mc_fragility< response_type, capacity_type >::mean (double time) virtual
a function to obtain mean probability from distribution at given time
Parameters
time time passed
Returns
mean probability at given time
Implements FATAL::Functor::BE_FUNCTOR_BASE.
Definition at line 582 of file Fragility.hpp.
References FATAL::Functor::mc_fragility< capacity_type, response_type >::mean().
median() [1/2]
template<class response_type , class capacity_type > double FATAL::Functor::mc_fragility< response_type, capacity_type >::median () virtual
a function to obtain median value from distribution
Returns
a median probability of failure
Implements FATAL::Functor::BE_FUNCTOR_BASE.
Definition at line 558 of file Fragility.hpp.
Referenced by FATAL::Functor::mc_fragility< capacity_type, response_type >::median().
median() [2/2]
template<class response_type , class capacity_type > double FATAL::Functor::mc_fragility< response_type, capacity_type >::median (double time) virtual
a function to obtain median probability from distribution at given time
Parameters
time time passed
Returns
a median probability of failure
Implements FATAL::Functor::BE_FUNCTOR_BASE.
Definition at line 588 of file Fragility.hpp.
References FATAL::Functor::mc_fragility< capacity_type, response_type >::median().
order()
template<class capacity_type , class response_type > int FATAL::Functor::mc_fragility< capacity_type, response_type >::order () inline virtual
get an order of a corresponding basic event in correlation matrix
Reimplemented from FATAL::Functor::BE_FUNCTOR_BASE.
Definition at line 340 of file Fragility.hpp.
previous()
template<class capacity_type , class response_type > double FATAL::Functor::mc_fragility< capacity_type, response_type >::previous () inline virtual
Returns
precvious result
Implements FATAL::Functor::BE_FUNCTOR_BASE.
Definition at line 368 of file Fragility.hpp.
References FATAL::Functor::fragility::_5th(), FATAL::Functor::fragility::_95th(), FATAL::Functor::fragility::mean(), and FATAL::Functor::fragility::median().
set()
template<class response_type , class capacity_type > void FATAL::Functor::mc_fragility< response_type, capacity_type >::set (const int & _index, const int & _unit_number) virtual
set an index and unit_number.
Reimplemented from FATAL::Functor::BE_FUNCTOR_BASE.
Definition at line 512 of file Fragility.hpp.
The documentation for this class was generated from the following file:
Fragility.hpp
[ FATALPRA Home Page(Not Ready Yet!) ] © 2014–2015, FATALPRA Developer Team.