FATALPRA: FATAL::Functor::fragility Class Reference
FATAL::Functor::fragility Class Reference
#include <Fragility.hpp>
Public Member Functions
fragility (const fragility &i_fragility)
fragility ()=delete
fragility (const std::vector< double > &param1)
double previous ()
double _fragility (double input)
double _fragility_mean ()
double operator() ()
double mean ()
double median ()
double _5th ()
double _95th ()
double operator() (double time)
double mean (double time)
double median (double time)
double _5th (double time)
double _95th (double time)
Public Member Functions inherited from FATAL::Functor::BE_FUNCTOR_BASE
virtual bool is_corr ()
virtual int order ()
virtual bool is_mc_type ()
virtual ~BE_FUNCTOR_BASE ()
virtual FATAL::FATAL_FAILURE_TYPE get_type ()
virtual void set (const int &_index, const int &_unit_number)
virtual bool get_state (const int &trial)
BE_FUNCTOR_BASE ()
BE_FUNCTOR_BASE (const FATAL::FATAL_FAILURE_TYPE &i_type)
template<class T >
boost::shared_ptr< T > upcast ()
double prob (const int &i_int)
Detailed Description
Definition at line 41 of file Fragility.hpp.
Constructor & Destructor Documentation
fragility() [1/3]
FATAL::Functor::fragility::fragility (const fragility & i_fragility) inline
copy constructor
Definition at line 81 of file Fragility.hpp.
References fragility().
fragility() [2/3]
FATAL::Functor::fragility::fragility () delete
default constructor deleted
Referenced by fragility().
fragility() [3/3]
FATAL::Functor::fragility::fragility (const std::vector< double > & param1)
default constructor
Parameters
param1 parameters for template parameter 1
param[0]: Am, param[1]:beta_u, param[2]:beta_r
Definition at line 400 of file Fragility.hpp.
References FATAL::FRAGILITY, and mean().
Member Function Documentation
_5th() [1/2]
double FATAL::Functor::fragility::_5th () virtual
a function to obtain 5th percentile from distribution
Returns
a 5th percentile of failure
Implements FATAL::Functor::BE_FUNCTOR_BASE.
Definition at line 465 of file Fragility.hpp.
References _fragility().
Referenced by _5th(), previous(), and FATAL::Functor::mc_fragility< capacity_type, response_type >::previous().
_5th() [2/2]
double FATAL::Functor::fragility::_5th (double time) virtual
a function to obtain 5th percentile from distribution at given time
Parameters
time time passed
Returns
a 5th percentile of failure
Implements FATAL::Functor::BE_FUNCTOR_BASE.
Definition at line 489 of file Fragility.hpp.
References _5th().
_95th() [1/2]
double FATAL::Functor::fragility::_95th () virtual
a function to obtain 95th percentile from distribution
Returns
a 95th percentile of failure
Implements FATAL::Functor::BE_FUNCTOR_BASE.
Definition at line 469 of file Fragility.hpp.
References _fragility().
Referenced by _95th(), previous(), and FATAL::Functor::mc_fragility< capacity_type, response_type >::previous().
_95th() [2/2]
double FATAL::Functor::fragility::_95th (double time) virtual
a function to obtain random probability from distribution at given time
Parameters
time time passed
Returns
a 95th percentile of failure
Implements FATAL::Functor::BE_FUNCTOR_BASE.
Definition at line 494 of file Fragility.hpp.
References _95th().
_fragility()
double FATAL::Functor::fragility::_fragility (double input)
a function to calulate percentile of fragility at given pga.
Definition at line 421 of file Fragility.hpp.
References FATAL::global_vars::pga.
Referenced by _5th(), _95th(), median(), operator()(), and previous().
_fragility_mean()
double FATAL::Functor::fragility::_fragility_mean ()
a function to obtain mean fragility curve
Definition at line 437 of file Fragility.hpp.
References FATAL::global_vars::pga.
Referenced by mean(), and previous().
mean() [1/2]
double FATAL::Functor::fragility::mean () virtual
a function to obtain mean value from distribution
Returns
a mean probability of failure
Implements FATAL::Functor::BE_FUNCTOR_BASE.
Definition at line 455 of file Fragility.hpp.
References _fragility_mean().
Referenced by fragility(), mean(), previous(), and FATAL::Functor::mc_fragility< capacity_type, response_type >::previous().
mean() [2/2]
double FATAL::Functor::fragility::mean (double time) virtual
a function to obtain mean probability from distribution at given time
Parameters
time time passed
Returns
mean probability at given time
Implements FATAL::Functor::BE_FUNCTOR_BASE.
Definition at line 479 of file Fragility.hpp.
References mean().
median() [1/2]
double FATAL::Functor::fragility::median () virtual
a function to obtain median value from distribution
Returns
a median probability of failure
Implements FATAL::Functor::BE_FUNCTOR_BASE.
Definition at line 460 of file Fragility.hpp.
References _fragility().
Referenced by median(), previous(), and FATAL::Functor::mc_fragility< capacity_type, response_type >::previous().
median() [2/2]
double FATAL::Functor::fragility::median (double time) virtual
a function to obtain median probability from distribution at given time
Parameters
time time passed
Returns
a median probability of failure
Implements FATAL::Functor::BE_FUNCTOR_BASE.
Definition at line 484 of file Fragility.hpp.
References median().
operator()() [1/2]
double FATAL::Functor::fragility::operator() () virtual
a function to obtain random value from distribution
Returns
a random probability of failure
Reimplemented from FATAL::Functor::BE_FUNCTOR_BASE.
Definition at line 449 of file Fragility.hpp.
References _fragility().
Referenced by operator()(), and previous().
operator()() [2/2]
double FATAL::Functor::fragility::operator() (double time) virtual
a function to obtain random probability from distribution at given time
Parameters
time time passed
Returns
a random probability from distribution at given time
Reimplemented from FATAL::Functor::BE_FUNCTOR_BASE.
Definition at line 474 of file Fragility.hpp.
References operator()().
previous()
double FATAL::Functor::fragility::previous () inline virtual
get a previous value
Implements FATAL::Functor::BE_FUNCTOR_BASE.
Definition at line 111 of file Fragility.hpp.
References _5th(), _95th(), _fragility(), _fragility_mean(), mean(), median(), and operator()().
The documentation for this class was generated from the following file:
Fragility.hpp
[ FATALPRA Home Page(Not Ready Yet!) ] © 2014–2015, FATALPRA Developer Team.