FATALPRA: FATAL::FT::fragility_pack Class Reference
FATAL::FT::fragility_pack Class Reference
data structure to handle seismically correlated basic event data
Using this class, one can construct correlated capacities and responses.
#include <fragility_pack.hpp>
Public Member Functions
unsigned int size () const
void resize (unsigned int i)
fragility_pack ()=delete
int get_order (const boost::shared_ptr< BE > &i_BE)
fragility_pack (const long &i_dim)
std::pair< Eigen::MatrixXd, Eigen::MatrixXd > construct_matrix ()
void update (const boost::shared_ptr< BE > &A, const boost::shared_ptr< BE > &B, const double &r_rho, const double &c_rho=0)
std::pair< double, double > get (const boost::shared_ptr< BE > &A, const boost::shared_ptr< BE > &B)
Detailed Description
data structure to handle seismically correlated basic event data
Using this class, one can construct correlated capacities and responses.
Definition at line 94 of file fragility_pack.hpp.
Constructor & Destructor Documentation
fragility_pack() [1/2]
FATAL::FT::fragility_pack::fragility_pack () delete
destructor
fragility_pack() [2/2]
FATAL::FT::fragility_pack::fragility_pack (const long & i_dim)
constructor
Definition at line 349 of file fragility_pack.hpp.
Member Function Documentation
construct_matrix()
std::pair< Eigen::MatrixXd, Eigen::MatrixXd > FATAL::FT::fragility_pack::construct_matrix ()
a function to construct a pair of correlation matrices
Returns
std::pair of correlation matrices.
Definition at line 296 of file fragility_pack.hpp.
Referenced by FATAL::FT::BE_DB::initialize_matrix().
get()
std::pair< double, double > FATAL::FT::fragility_pack::get (const boost::shared_ptr< BE > & A, const boost::shared_ptr< BE > & B)
a function to get correlation coefficients of response and fragility
Definition at line 199 of file fragility_pack.hpp.
Referenced by FATAL::FT::BE_DB::get_fragility_correlation().
get_order()
int FATAL::FT::fragility_pack::get_order (const boost::shared_ptr< BE > & i_BE)
a function to get an index of a basic event in correlation matrices
Definition at line 319 of file fragility_pack.hpp.
Referenced by FATAL::FT::BE_DB::initialize_matrix().
resize()
void FATAL::FT::fragility_pack::resize (unsigned int i)
resize the dimension of correlation matrces
Definition at line 332 of file fragility_pack.hpp.
Referenced by FATAL::FT::BE_DB::set_corr_dim_fragility().
size()
unsigned int FATAL::FT::fragility_pack::size () const inline
dimension of correlation matrix
Definition at line 153 of file fragility_pack.hpp.
Referenced by FATAL::FT::BE_DB::initialize_matrix().
update()
void FATAL::FT::fragility_pack::update (const boost::shared_ptr< BE > & A, const boost::shared_ptr< BE > & B, const double & r_rho, const double & c_rho = 0)
a function to assign correlation factor between two basic events.
Definition at line 230 of file fragility_pack.hpp.
Referenced by FATAL::FT::BE_DB::add_fragility_correlation(), and FATAL::FT::BE_DB::add_fragility_data().
The documentation for this class was generated from the following file:
fragility_pack.hpp
[ FATALPRA Home Page(Not Ready Yet!) ] © 2014–2015, FATALPRA Developer Team.