FATALPRA: FATAL::ET::IE Class Reference
FATAL::ET::IE Class Reference
#include <IE.hpp>
Public Member Functions
IE ()
IE (boost::shared_ptr< ET_BASE > i_fail, boost::shared_ptr< FATAL::FT::FT_BASE > i_FT)
IE (const std::string &i_name)
void prep (std::vector< boost::shared_ptr< FT::FT_BASE >> i_FTs, std::vector< bool > i_branch_info)
void clear ()
ET_TYPE GET_ET_TYPE ()
bool is_cyclic ()
bool is_cyclic (std::vector< boost::shared_ptr< ET_BASE >> &targets)
virtual ~IE ()
void print ()
void null2seq (bool isIE=true)
void prep (bool is_IE)
void assign (const boost::shared_ptr< ET_BASE > i_ET)
boost::shared_ptr< ET_BASE > getET ()
std::vector< boost::shared_ptr< ET_BASE > > get_seq (bool is_IE=true, bool validate=true)
bool is_replacible (bool state)
Public Member Functions inherited from FATAL::ET::ET_BASE
template<class T >
boost::shared_ptr< T > cast ()
virtual void assign_type (CD_SEQ _ID)
virtual boost::shared_ptr< FATAL::FT::FT_BASE > get_Equiv_FT ()
bool is_branch_null (bool state)
ET_BASE ()
ET_BASE (const boost::shared_ptr< ET_BASE > &i_success, const boost::shared_ptr< ET_BASE > &i_fail, const boost::shared_ptr< FATAL::FT::FT_BASE > &i_FT)
ET_BASE (const std::string &i_name)
boost::shared_ptr< FT::FT_BASE > & getFT ()
void assign (const boost::shared_ptr< ET_BASE > i_success, const boost::shared_ptr< ET_BASE > i_fail, bool force=false)
void assign (const boost::shared_ptr< FT::FT_BASE > &i_FT)
void assign (bool path, const boost::shared_ptr< ET_BASE > i_ET)
boost::shared_ptr< ET_BASE > getET (bool status)
void clear ()
void assign_FT (const boost::shared_ptr< FT::FT_BASE > &i_FT)
virtual ~ET_BASE ()
virtual void auto_replace (std::vector< boost::shared_ptr< ET_BASE >> &sequences)
Public Member Functions inherited from FATAL::ET::ET_PROPERTY
ET_PROPERTY ()
ET_PROPERTY (std::string i_evt)
void set_evt (const std::string &i_name)
std::string get_evt ()
Additional Inherited Members
Protected Attributes inherited from FATAL::ET::ET_BASE
boost::shared_ptr< FT::FT_BASE > FT
boost::shared_ptr< ET_BASE > success
boost::shared_ptr< ET_BASE > fail
Detailed Description
Definition at line 35 of file IE.hpp.
Constructor & Destructor Documentation
IE() [1/3]
FATAL::ET::IE::IE () inline
default constructor
Definition at line 53 of file IE.hpp.
IE() [2/3]
FATAL::ET::IE::IE (boost::shared_ptr< ET_BASE > i_fail, boost::shared_ptr< FATAL::FT::FT_BASE > i_FT)
default constructor
Definition at line 226 of file IE.hpp.
References FATAL::ET::ET_BASE::fail, and FATAL::ET::ET_BASE::FT.
IE() [3/3]
FATAL::ET::IE::IE (const std::string & i_name) inline
default constructor
Definition at line 61 of file IE.hpp.
~IE()
virtual FATAL::ET::IE::~IE () inline virtual
default deconstructor
Definition at line 118 of file IE.hpp.
Member Function Documentation
assign()
void FATAL::ET::IE::assign (const boost::shared_ptr< ET_BASE > i_ET) inline
Definition at line 164 of file IE.hpp.
References FATAL::ET::ET_BASE::fail.
clear()
void FATAL::ET::IE::clear ()
clear memory
Definition at line 239 of file IE.hpp.
References FATAL::ET::ET_BASE::fail.
Referenced by prep().
GET_ET_TYPE()
ET_TYPE FATAL::ET::IE::GET_ET_TYPE () virtual
obtain an ET_TYPE
Reimplemented from FATAL::ET::ET_BASE.
Definition at line 221 of file IE.hpp.
References FATAL::IE.
Referenced by prep().
get_seq()
std::vector<boost::shared_ptr<ET_BASE> > FATAL::ET::IE::get_seq (bool is_IE = true, bool validate = true) inline virtual
Reimplemented from FATAL::ET::ET_BASE.
Definition at line 186 of file IE.hpp.
References FATAL::ET::ET_BASE::get_seq().
getET()
boost::shared_ptr<ET_BASE> FATAL::ET::IE::getET () inline
Definition at line 175 of file IE.hpp.
References FATAL::ET::ET_BASE::fail.
is_cyclic() [1/2]
bool FATAL::ET::IE::is_cyclic () virtual
check if ET is cyclic
Implements FATAL::ET::ET_BASE.
Definition at line 265 of file IE.hpp.
References FATAL::ET::ET_BASE::fail.
Referenced by prep().
is_cyclic() [2/2]
bool FATAL::ET::IE::is_cyclic (std::vector< boost::shared_ptr< ET_BASE >> & targets) virtual
check if ET is cyclic
Implements FATAL::ET::ET_BASE.
Definition at line 244 of file IE.hpp.
References FATAL::ET::ET_BASE::fail.
is_replacible()
bool FATAL::ET::IE::is_replacible (bool state) inline virtual
Reimplemented from FATAL::ET::ET_BASE.
Definition at line 191 of file IE.hpp.
References FATAL::ET::ET_BASE::fail, FATAL::ET::ET_BASE::is_branch_null(), and FATAL::SEQ.
null2seq()
void FATAL::ET::IE::null2seq (bool isIE = true) inline virtual
replace all nullptr to sequences
Warning
this function replaces all nullptr with shared pointers of ET::SEQ class.
Reimplemented from FATAL::ET::ET_BASE.
Definition at line 154 of file IE.hpp.
References FATAL::ET::ET_BASE::null2seq().
prep() [1/2]
void FATAL::ET::IE::prep (std::vector< boost::shared_ptr< FT::FT_BASE >> i_FTs, std::vector< bool > i_branch_info) inline virtual
construct sequence information for analysis
Todo:
move this function to private member
Parameters
i_FTs a set of fault trees in previous event trees in sequence
i_branch_info information on previous event trees in sequence
Reimplemented from FATAL::ET::ET_BASE.
Definition at line 63 of file IE.hpp.
References clear(), FATAL::ET::ET_BASE::fail, FATAL::ET::ET_BASE::FT, GET_ET_TYPE(), and is_cyclic().
prep() [2/2]
void FATAL::ET::IE::prep (bool is_IE) inline virtual
construct sequence information for analysis
Parameters
is_IE true if ET is an initialting event. Otherwise, false.
Reimplemented from FATAL::ET::ET_BASE.
Definition at line 159 of file IE.hpp.
References FATAL::ET::ET_BASE::prep().
print()
void FATAL::ET::IE::print () inline virtual
Reimplemented from FATAL::ET::ET_BASE.
Definition at line 120 of file IE.hpp.
References FATAL::ET::ET_BASE::fail, FATAL::ET::ET_PROPERTY::get_evt(), and FATAL::SEQ.
The documentation for this class was generated from the following file:
IE.hpp
[ FATALPRA Home Page(Not Ready Yet!) ] © 2014–2015, FATALPRA Developer Team.