FATALPRA: FATAL::mat_gen Class Reference
FATAL::mat_gen Class Reference
#include <mat_gen.hpp>
Public Member Functions
size_t size ()
size_t size (unsigned int i)
mat_gen ()=delete
mat_gen (const boost::filesystem::path &i_path)
void file_check (const boost::filesystem::path &i_path)
template<class T >
T get_elem (const unsigned int &i, const unsigned int &j)
void tokenize (const std::string &token)
Detailed Description
Definition at line 30 of file mat_gen.hpp.
Constructor & Destructor Documentation
mat_gen() [1/2]
FATAL::mat_gen::mat_gen () delete
Referenced by size().
mat_gen() [2/2]
FATAL::mat_gen::mat_gen (const boost::filesystem::path & i_path) inline
Definition at line 52 of file mat_gen.hpp.
Member Function Documentation
file_check()
void FATAL::mat_gen::file_check (const boost::filesystem::path & i_path) inline
Bug:
boost::filesystem::exists leaks memory.
Definition at line 55 of file mat_gen.hpp.
Referenced by tokenize().
get_elem()
template<class T > T FATAL::mat_gen::get_elem (const unsigned int & i, const unsigned int & j) inline
Definition at line 70 of file mat_gen.hpp.
size() [1/2]
size_t FATAL::mat_gen::size () inline
Definition at line 40 of file mat_gen.hpp.
size() [2/2]
size_t FATAL::mat_gen::size (unsigned int i) inline
Definition at line 45 of file mat_gen.hpp.
References mat_gen().
tokenize()
void FATAL::mat_gen::tokenize (const std::string & token) inline
Definition at line 77 of file mat_gen.hpp.
References file_check().
The documentation for this class was generated from the following file:
mat_gen.hpp
[ FATALPRA Home Page(Not Ready Yet!) ] © 2014–2015, FATALPRA Developer Team.