FATALPRA: FATAL::FT::SOKC Class Reference
FATAL::FT::SOKC Class Reference
data structure to handle State of knowledge correlation
#include <SOKC.hpp>
Public Member Functions
SOKC ()
void update (const dist_param &i_type)
void add_sokc (const std::string &comp_type, const boost::shared_ptr< Functor::BE_FUNCTOR_BASE > &i_BE_TYPE, const boost::shared_ptr< BE > &i_BE)
std::vector< boost::shared_ptr< FT::BE > > get_list (const std::string &comp_name) const
boost::shared_ptr< Functor::BE_FUNCTOR_BASE > get_param (const std::string &comp_name) const
void add_sokc_param (const std::string &comp_type, const boost::shared_ptr< Functor::BE_FUNCTOR_BASE > &i_BE_TYPE)
void add_sokc_be (const std::string &comp_type, const boost::shared_ptr< BE > &i_BE)
Detailed Description
data structure to handle State of knowledge correlation
Definition at line 47 of file SOKC.hpp.
Constructor & Destructor Documentation
SOKC()
FATAL::FT::SOKC::SOKC () inline
Definition at line 76 of file SOKC.hpp.
References add_sokc(), add_sokc_be(), add_sokc_param(), get_list(), get_param(), and update().
Member Function Documentation
add_sokc()
void FATAL::FT::SOKC::add_sokc (const std::string & comp_type, const boost::shared_ptr< Functor::BE_FUNCTOR_BASE > & i_BE_TYPE, const boost::shared_ptr< BE > & i_BE)
insert a basic event and its distribution into database
Parameters
comp_type a name of a component group
i_BE_TYPE a shared pointer of BE_FUNCTOR_BASE
i_BE an input component basic event name
Definition at line 153 of file SOKC.hpp.
References add_sokc_be(), and add_sokc_param().
Referenced by FATAL::FT::BE_DB::add_sokc(), and SOKC().
add_sokc_be()
void FATAL::FT::SOKC::add_sokc_be (const std::string & comp_type, const boost::shared_ptr< BE > & i_BE)
add a basic event information into database
Parameters
comp_type sokc component name
i_BE an input basic event
Definition at line 212 of file SOKC.hpp.
Referenced by add_sokc(), and SOKC().
add_sokc_param()
void FATAL::FT::SOKC::add_sokc_param (const std::string & comp_type, const boost::shared_ptr< Functor::BE_FUNCTOR_BASE > & i_BE_TYPE)
add a distribution information into database
Parameters
comp_type sokc component name
i_BE_TYPE a shared pointer to a BE_FUNCTOR_BASE
Definition at line 189 of file SOKC.hpp.
Referenced by add_sokc(), and SOKC().
get_list()
std::vector< boost::shared_ptr< FT::BE > > FATAL::FT::SOKC::get_list (const std::string & comp_name) const
Definition at line 159 of file SOKC.hpp.
Referenced by SOKC().
get_param()
boost::shared_ptr< Functor::BE_FUNCTOR_BASE > FATAL::FT::SOKC::get_param (const std::string & comp_name) const
get a shared pointer of a BE_FUNCTOR_BASE
Parameters
comp_name sokc component group name
Returns
a shared pointer of a BE_FUNCTOR_BASE
Definition at line 174 of file SOKC.hpp.
Referenced by SOKC().
update()
void FATAL::FT::SOKC::update (const dist_param & i_type)
a function yo update basic event probabilities based on an input
Parameters
u_type a characteristic of a distribution
Definition at line 131 of file SOKC.hpp.
Referenced by SOKC(), and FATAL::FT::BE_DB::update().
The documentation for this class was generated from the following file:
SOKC.hpp
[ FATALPRA Home Page(Not Ready Yet!) ] © 2014–2015, FATALPRA Developer Team.