FATALPRA: FATAL::Functor::non_repairable< Dist_Info1, Dist_Info2 > Class Template Reference
FATAL::Functor::non_repairable< Dist_Info1, Dist_Info2 > Class Template Reference
#include <NonRepairable.hpp>
Public Member Functions
non_repairable ()=delete
non_repairable (const std::vector< double > &param1, const std::vector< double > &param2)
virtual ~non_repairable ()
double previous ()
double operator() ()
double mean ()
double median ()
double _5th ()
double _95th ()
double operator() (double time)
double mean (double time)
double median (double time)
double _5th (double time)
double _95th (double time)
Public Member Functions inherited from FATAL::Functor::BE_FUNCTOR_BASE
virtual bool is_corr ()
virtual int order ()
virtual bool is_mc_type ()
virtual ~BE_FUNCTOR_BASE ()
virtual FATAL::FATAL_FAILURE_TYPE get_type ()
virtual void set (const int &_index, const int &_unit_number)
virtual bool get_state (const int &trial)
BE_FUNCTOR_BASE ()
BE_FUNCTOR_BASE (const FATAL::FATAL_FAILURE_TYPE &i_type)
template<class T >
boost::shared_ptr< T > upcast ()
double prob (const int &i_int)
Detailed Description
template<class Dist_Info1, class Dist_Info2>
class FATAL::Functor::non_repairable< Dist_Info1, Dist_Info2 >
a class which is a base class for basic event computation
Template Parameters
Dist_Info1 a template parameter of a distribution type
Dist_Info2 a template parameter of a distribution type
Definition at line 41 of file NonRepairable.hpp.
Constructor & Destructor Documentation
non_repairable() [1/2]
template<class Dist_Info1 , class Dist_Info2 > FATAL::Functor::non_repairable< Dist_Info1, Dist_Info2 >::non_repairable () delete
default constructor deleted
non_repairable() [2/2]
template<class Dist_Info1 , class Dist_Info2 > FATAL::Functor::non_repairable< Dist_Info1, Dist_Info2 >::non_repairable (const std::vector< double > & param1, const std::vector< double > & param2)
default constructor
Parameters
param1 parameters for template parameter 1
param2 parameters for template parameter 2
Definition at line 112 of file NonRepairable.hpp.
References FATAL::NON_REPAIRABLE.
~non_repairable()
template<class Dist_Info1 , class Dist_Info2 > virtual FATAL::Functor::non_repairable< Dist_Info1, Dist_Info2 >::~non_repairable () inline virtual
default destructor
Definition at line 82 of file NonRepairable.hpp.
Member Function Documentation
_5th() [1/2]
template<class Dist_Info1 , class Dist_Info2 > double FATAL::Functor::non_repairable< Dist_Info1, Dist_Info2 >::_5th () virtual
a function to obtain 5th percentile from distribution
Returns
a 5th percentile of failure
Implements FATAL::Functor::BE_FUNCTOR_BASE.
Definition at line 151 of file NonRepairable.hpp.
Referenced by FATAL::Functor::non_repairable< Dist_Info1, Dist_Info2 >::previous().
_5th() [2/2]
template<class Dist_Info1 , class Dist_Info2 > double FATAL::Functor::non_repairable< Dist_Info1, Dist_Info2 >::_5th (double time) virtual
a function to obtain 5th percentile from distribution at given time
Parameters
time time passed
Returns
a 5th percentile of failure
Implements FATAL::Functor::BE_FUNCTOR_BASE.
Definition at line 206 of file NonRepairable.hpp.
_95th() [1/2]
template<class Dist_Info1 , class Dist_Info2 > double FATAL::Functor::non_repairable< Dist_Info1, Dist_Info2 >::_95th () virtual
a function to obtain 95th percentile from distribution
Returns
a 95th percentile of failure
Implements FATAL::Functor::BE_FUNCTOR_BASE.
Definition at line 162 of file NonRepairable.hpp.
Referenced by FATAL::Functor::non_repairable< Dist_Info1, Dist_Info2 >::previous().
_95th() [2/2]
template<class Dist_Info1 , class Dist_Info2 > double FATAL::Functor::non_repairable< Dist_Info1, Dist_Info2 >::_95th (double time) virtual
a function to obtain random probability from distribution at given time
Parameters
time time passed
Returns
a 95th percentile of failure
Implements FATAL::Functor::BE_FUNCTOR_BASE.
Definition at line 217 of file NonRepairable.hpp.
mean() [1/2]
template<class Dist_Info1 , class Dist_Info2 > double FATAL::Functor::non_repairable< Dist_Info1, Dist_Info2 >::mean () virtual
a function to obtain mean value from distribution
Returns
a mean probability of failure
Implements FATAL::Functor::BE_FUNCTOR_BASE.
Definition at line 129 of file NonRepairable.hpp.
Referenced by FATAL::Functor::non_repairable< Dist_Info1, Dist_Info2 >::previous().
mean() [2/2]
template<class Dist_Info1 , class Dist_Info2 > double FATAL::Functor::non_repairable< Dist_Info1, Dist_Info2 >::mean (double time) virtual
a function to obtain mean probability from distribution at given time
Parameters
time time passed
Returns
mean probability at given time
Implements FATAL::Functor::BE_FUNCTOR_BASE.
Definition at line 184 of file NonRepairable.hpp.
median() [1/2]
template<class Dist_Info1 , class Dist_Info2 > double FATAL::Functor::non_repairable< Dist_Info1, Dist_Info2 >::median () virtual
a function to obtain median value from distribution
Returns
a median probability of failure
Implements FATAL::Functor::BE_FUNCTOR_BASE.
Definition at line 140 of file NonRepairable.hpp.
Referenced by FATAL::Functor::non_repairable< Dist_Info1, Dist_Info2 >::previous().
median() [2/2]
template<class Dist_Info1 , class Dist_Info2 > double FATAL::Functor::non_repairable< Dist_Info1, Dist_Info2 >::median (double time) virtual
a function to obtain median probability from distribution at given time
Parameters
time time passed
Returns
a median probability of failure
Implements FATAL::Functor::BE_FUNCTOR_BASE.
Definition at line 195 of file NonRepairable.hpp.
operator()() [1/2]
template<class Dist_Info1 , class Dist_Info2 > double FATAL::Functor::non_repairable< Dist_Info1, Dist_Info2 >::operator() () virtual
a function to obtain random value from distribution
Returns
a random probability of failure
Reimplemented from FATAL::Functor::BE_FUNCTOR_BASE.
Definition at line 118 of file NonRepairable.hpp.
Referenced by FATAL::Functor::non_repairable< Dist_Info1, Dist_Info2 >::previous().
operator()() [2/2]
template<class Dist_Info1 , class Dist_Info2 > double FATAL::Functor::non_repairable< Dist_Info1, Dist_Info2 >::operator() (double time) virtual
a function to obtain random probability from distribution at given time
Parameters
time time passed
Returns
a random probability from distribution at given time
Reimplemented from FATAL::Functor::BE_FUNCTOR_BASE.
Definition at line 173 of file NonRepairable.hpp.
previous()
template<class Dist_Info1 , class Dist_Info2 > double FATAL::Functor::non_repairable< Dist_Info1, Dist_Info2 >::previous () inline virtual
obtan a probability of previos calculation
Returns
a probability of previous state
Implements FATAL::Functor::BE_FUNCTOR_BASE.
Definition at line 86 of file NonRepairable.hpp.
References FATAL::Functor::non_repairable< Dist_Info1, Dist_Info2 >::_5th(), FATAL::Functor::non_repairable< Dist_Info1, Dist_Info2 >::_95th(), FATAL::Functor::non_repairable< Dist_Info1, Dist_Info2 >::mean(), FATAL::Functor::non_repairable< Dist_Info1, Dist_Info2 >::median(), and FATAL::Functor::non_repairable< Dist_Info1, Dist_Info2 >::operator()().
The documentation for this class was generated from the following file:
NonRepairable.hpp
[ FATALPRA Home Page(Not Ready Yet!) ] © 2014–2015, FATALPRA Developer Team.