FATALPRA: FATAL::MCS_MGR Class Reference
FATAL::MCS_MGR Class Reference
an implementation of minimal cut set manager
#include <MCS_MGR.hpp>
Public Member Functions
MCS_MGR ()=delete
std::pair< std::pair< boost::shared_ptr< FT::FT_BASE >, boost::shared_ptr< FT::FT_BASE > >, std::pair< boost::shared_ptr< FT::BE_DB >, boost::shared_ptr< FT::BE_DB > > > operator[] (const unsigned int i)
size_t size ()
MCS_MGR (const boost::shared_ptr< FT::FT_BASE > &i_FT)
MCS_MGR (const boost::shared_ptr< ET::ET > &i_ET, bool is_IE=true)
std::pair< std::unordered_set< MCS >, std::unordered_set< MCS > > solve (std::pair< std::pair< boost::shared_ptr< FT::FT_BASE >, boost::shared_ptr< FT::FT_BASE >>, std::pair< boost::shared_ptr< FT::BE_DB >, boost::shared_ptr< FT::BE_DB >>> input, double &i_cutpoint, int i_max_num)
Detailed Description
an implementation of minimal cut set manager
Definition at line 41 of file MCS_MGR.hpp.
Constructor & Destructor Documentation
MCS_MGR() [1/3]
FATAL::MCS_MGR::MCS_MGR () delete
default constructor is deleted
Referenced by size().
MCS_MGR() [2/3]
FATAL::MCS_MGR::MCS_MGR (const boost::shared_ptr< FT::FT_BASE > & i_FT)
a default constructor
Parameters
i_FT an input fault tree to analyze
Warning
i_FT is assumed to be regular
Definition at line 121 of file MCS_MGR.hpp.
MCS_MGR() [3/3]
FATAL::MCS_MGR::MCS_MGR (const boost::shared_ptr< ET::ET > & i_ET, bool is_IE = true)
a default constructor
Parameters
i_ET an input event tree to analyze
Definition at line 145 of file MCS_MGR.hpp.
References FATAL::AND, and FATAL::OR.
Member Function Documentation
operator[]()
std::pair< std::pair< boost::shared_ptr< FT::FT_BASE >, boost::shared_ptr< FT::FT_BASE > >, std::pair< boost::shared_ptr< FT::BE_DB >, boost::shared_ptr< FT::BE_DB > > > FATAL::MCS_MGR::operator[] (const unsigned int i)
Definition at line 107 of file MCS_MGR.hpp.
size()
size_t FATAL::MCS_MGR::size () inline
a number of independent sequences
Returns
size of FTs
Definition at line 75 of file MCS_MGR.hpp.
References MCS_MGR(), and solve().
solve()
std::pair< std::unordered_set< MCS >, std::unordered_set< MCS > > FATAL::MCS_MGR::solve (std::pair< std::pair< boost::shared_ptr< FT::FT_BASE >, boost::shared_ptr< FT::FT_BASE >>, std::pair< boost::shared_ptr< FT::BE_DB >, boost::shared_ptr< FT::BE_DB >>> input, double & i_cutpoint, int i_max_num)
Definition at line 187 of file MCS_MGR.hpp.
Referenced by size().
The documentation for this class was generated from the following file:
MCS_MGR.hpp
[ FATALPRA Home Page(Not Ready Yet!) ] © 2014–2015, FATALPRA Developer Team.