FATALPRA: FATAL::FT::CND Class Reference
FATAL::FT::CND Class Reference
conditonal house gate implementaiton
Note: conditonal gate does not have FT assigned.
#include <CND.hpp>
Public Member Functions
void validate (const boost::shared_ptr< FT_BASE > &i_FT)
template<class return_type >
return_type GateOp ()
template<class return_type , class mgr >
return_type GateOp (mgr &i_mgr)
template<class return_type , class class1 , class class2 >
return_type GateOp (class1 &i_class1, class2 &i_class2)
template<class return_type , class class1 , class class2 , class class3 >
return_type GateOp (class1 &i_class1, class2 &i_class2, class3 &i_class3)
virtual ~CND ()
CND ()
CND (const std::string &i_name)
CND (const boost::shared_ptr< Functor::CND_BASE > &i_cond)
CND (const std::string &i_name, boost::shared_ptr< Functor::CND_BASE > &i_cond)
CND (const boost::shared_ptr< FT_BASE > &i_FT)
bool is_cond () const
boost::shared_ptr< FATAL::FT::FT_BASE > get_internal ()
void set_internal (const boost::shared_ptr< FT_BASE > &i_internal_gate)
void override_internal (const boost::shared_ptr< FT_BASE > &i_internal_gate)
boost::shared_ptr< Functor::CND_BASE > get_cond_op ()
void assign_coditional_op (const boost::shared_ptr< Functor::CND_BASE > &i_conditional)
bool operator() ()
template<class T >
bool condition (T input)
boost::shared_ptr< FT_BASE > get_same_type () const
boost::shared_ptr< FT_BASE > transform ()
template<>
cacBDD::BDD GateOp (boost::shared_ptr< FATAL::DD::dd_mgr< cacBDD::XBDDManager, cacBDD::BDD >> &i_mgr)
template<>
BDD GateOp (boost::shared_ptr< FATAL::DD::dd_mgr< Cudd, BDD >> &i_mgr)
template<>
std::unordered_set< MCS > GateOp (boost::shared_ptr< BE_DB > &i_DB, double &i_cut_point, int &i_max_num)
Public Member Functions inherited from FATAL::FT::FT_BASE
template<class return_type >
return_type GateOp ()
template<class return_type , class mgr >
return_type GateOp (mgr &i_mgr)
template<class return_type , class class1 , class class2 >
return_type GateOp (class1 &i_class1, class2 &i_class2)
template<class return_type , class class1 , class class2 , class class3 >
return_type GateOp (class1 &i_class1, class2 &i_class2, class3 &i_class3)
virtual ~FT_BASE ()
FT_BASE ()
template<class T >
boost::shared_ptr< T > cast () const
boost::shared_ptr< FT_BASE > get (const int &i) const
FT_BASE (const std::string &i_name)
FT_BASE (const FT_TYPE &i_type)
FT_BASE (const std::string &i_name, const FT_TYPE &i_type)
const unsigned int size () const
std::vector< boost::shared_ptr< FT_BASE > > & getFTs ()
virtual void clear ()
std::vector< boost::shared_ptr< FT_BASE > >::iterator begin ()
std::vector< boost::shared_ptr< FT_BASE > >::iterator end ()
boost::shared_ptr< FT_BASE > & operator[] (const int &i)
bool put (const std::vector< boost::shared_ptr< FT_BASE >> &i_FTs)
bool put (const boost::shared_ptr< FT_BASE > &i_base)
template<typename... Args>
bool put (const boost::shared_ptr< FT_BASE > &i_base, Args... args)
boost::shared_ptr< FT_BASE > get_elem (const std::string &gate_name)
virtual boost::shared_ptr< FT_BASE > h_copy_cyclic (std::vector< boost::shared_ptr< FT_BASE >> paths)
virtual boost::shared_ptr< FT_BASE > h_copy_non_cyclic ()
virtual boost::shared_ptr< FT_BASE > h_copy ()
bool find (const std::string &i_string) const
virtual bool verify ()
virtual int depth (bool initial=true)
virtual boost::shared_ptr< FT_BASE > coalesce (bool second_call=false)
void swap (const boost::shared_ptr< FT_BASE > &from, const boost::shared_ptr< FT_BASE > &to)
bool is_cyclic ()
bool is_cyclic (const std::vector< boost::shared_ptr< FATAL::FT::FT_BASE > > &targets)
template<typename... Args>
bool put (const boost::shared_ptr< FATAL::FT::FT_BASE > &i_base, Args... args)
Public Member Functions inherited from FATAL::FT::BASE
virtual ~BASE ()
BASE ()
BASE (const std::string &i_name)
BASE (const FT_TYPE &i_type)
BASE (const std::string &i_name, const FT_TYPE &i_type)
virtual const FT_TYPE & identify () const
virtual const std::string & get_name () const
void set_name (const std::string &i_name)
Public Member Functions inherited from FATAL::FT::FT_PROPERTY
virtual bool is_coalescible () const
virtual bool isBE () const
virtual bool isNBE () const
virtual bool is_cyclic (const std::vector< boost::shared_ptr< FATAL::FT::FT_BASE >> &targets)
virtual bool is_negated () const
Additional Inherited Members
Protected Attributes inherited from FATAL::FT::FT_BASE
std::vector< boost::shared_ptr< FT_BASE > > FTs
boost::shared_ptr< FT_BASE > _equiv_ft
Protected Attributes inherited from FATAL::FT::BASE
std::string name
FT_TYPE my_type
Detailed Description
conditonal house gate implementaiton
Note: conditonal gate does not have FT assigned.
Definition at line 43 of file CND.hpp.
Constructor & Destructor Documentation
~CND()
virtual FATAL::FT::CND::~CND () inline virtual
default destructor
Definition at line 125 of file CND.hpp.
CND() [1/5]
FATAL::FT::CND::CND () inline
Definition at line 128 of file CND.hpp.
Referenced by CND().
CND() [2/5]
FATAL::FT::CND::CND (const std::string & i_name) inline
default constructor
Parameters
i_name name of a CND gate.
Definition at line 133 of file CND.hpp.
References CND().
CND() [3/5]
FATAL::FT::CND::CND (const boost::shared_ptr< Functor::CND_BASE > & i_cond)
a constructor of a CND_BASE
Parameters
i_cond a condition where a gate become failed.
Definition at line 232 of file CND.hpp.
References CHECKNULL.
CND() [4/5]
FATAL::FT::CND::CND (const std::string & i_name, boost::shared_ptr< Functor::CND_BASE > & i_cond)
a constructor with name and condition to fail
Parameters
i_name a name of a conditional gate
i_cond a condtion such that a conditional gate will fail
Definition at line 239 of file CND.hpp.
References CHECKNULL.
CND() [5/5]
FATAL::FT::CND::CND (const boost::shared_ptr< FT_BASE > & i_FT)
a constructor
Definition at line 246 of file CND.hpp.
References FATAL::FT::FT_BASE::FTs.
Member Function Documentation
assign_coditional_op()
void FATAL::FT::CND::assign_coditional_op (const boost::shared_ptr< Functor::CND_BASE > & i_conditional)
assign condition for a conditional gate
Parameters
i_conditional a condition where a gate will fail.
Definition at line 309 of file CND.hpp.
Referenced by is_cond().
condition()
template<class T > bool FATAL::FT::CND::condition (T input)
check if a condition is met.
Template Parameters
T template for an input value return true if a condition is met. otherwise, false.
Definition at line 331 of file CND.hpp.
References CHECKNULL.
Referenced by is_cond().
GateOp() [1/7]
template<class return_type > return_type FATAL::FT::CND::GateOp ()
Operation defined by gate type. This will be implemented using technique shown in http://d.hatena.ne.jp/kazuhooku/20090727/1248690940 To use this class, template specialization is required.
Template Parameters
return_type template parameter of return type
Returns
return value is specificied by template specialization
Definition at line 884 of file GATEOP.hpp.
GateOp() [2/7]
template<class return_type , class mgr > return_type FATAL::FT::CND::GateOp (mgr & i_mgr)
Operation defined by Gate Type. This will be implemented using technique shown in http://d.hatena.ne.jp/kazuhooku/20090727/1248690940 To use this class, template specialization is required.
Template Parameters
return_type template parameter of return type
mgr template paramter for input
Parameters
i_mgr input variable with template type mgr
Returns
return value is specificied by template specialization
Definition at line 892 of file GATEOP.hpp.
GateOp() [3/7]
template<class return_type , class class1 , class class2 > return_type FATAL::FT::CND::GateOp (class1 & i_class1, class2 & i_class2)
Operation defined by Gate Type. This will be implemented using technique shown in http://d.hatena.ne.jp/kazuhooku/20090727/1248690940 To use this class, template specialization is required.
Template Parameters
return_type template parameter of return type
class1 template parameter for input
class2 template parameter for input
Parameters
i_class1 input variable with template type class1
i_class2 input variable with template type class2
Returns
return value is specificied by template specialization
Definition at line 902 of file GATEOP.hpp.
GateOp() [4/7]
template<class return_type , class class1 , class class2 , class class3 > return_type FATAL::FT::CND::GateOp (class1 & i_class1, class2 & i_class2, class3 & i_class3)
Operation defined by Gate Type. This will be implemented using technique shown in http://d.hatena.ne.jp/kazuhooku/20090727/1248690940 To use this class, template specialization is required.
Parameters
return_type template parameter of return type
Template Parameters
class1 template parameter for input
class2 template parameter for input
class3 template parameter for input
Parameters
i_class1 input variable with template type class1
i_class2 input variable with template type class2
i_class3 input variable with template type class2
Returns
return value is specificied by template specialization
Definition at line 911 of file GATEOP.hpp.
GateOp() [5/7]
template<> cacBDD::BDD FATAL::FT::CND::GateOp (boost::shared_ptr< FATAL::DD::dd_mgr< cacBDD::XBDDManager, cacBDD::BDD >> & i_mgr)
Definition at line 408 of file CacBDD_GATEOP.hpp.
GateOp() [6/7]
template<> BDD FATAL::FT::CND::GateOp (boost::shared_ptr< FATAL::DD::dd_mgr< Cudd, BDD >> & i_mgr)
Definition at line 408 of file CUDD_GATEOP.hpp.
GateOp() [7/7]
template<> std::unordered_set<MCS> FATAL::FT::CND::GateOp (boost::shared_ptr< BE_DB > & i_DB, double & i_cut_point, int & i_max_num)
Definition at line 466 of file MCS_GATEOP.hpp.
get_cond_op()
boost::shared_ptr< Functor::CND_BASE > FATAL::FT::CND::get_cond_op ()
access to a conditional operator
Returns
a shared pointer to a condition
Definition at line 301 of file CND.hpp.
References CHECKNULL.
Referenced by is_cond().
get_internal()
boost::shared_ptr< FATAL::FT::FT_BASE > FATAL::FT::CND::get_internal ()
an return type of a shared pointer to FT_BASE
Returns
a shared pointer to an internal gate type.
Definition at line 252 of file CND.hpp.
References FATAL::FT::FT_BASE::FTs.
Referenced by is_cond().
get_same_type()
boost::shared_ptr< FT_BASE > FATAL::FT::CND::get_same_type () const virtual
get a gate of the same type
Returns
a shared pointer to a conditional gate.
Reimplemented from FATAL::FT::FT_BASE.
Definition at line 340 of file CND.hpp.
References FATAL::FT::BASE::name.
Referenced by is_cond().
is_cond()
bool FATAL::FT::CND::is_cond () const inline virtual
check if a gate is conditional or not
Returns
always true.
Reimplemented from FATAL::FT::FT_PROPERTY.
Definition at line 158 of file CND.hpp.
References assign_coditional_op(), condition(), get_cond_op(), get_internal(), get_same_type(), operator()(), override_internal(), set_internal(), and transform().
operator()()
bool FATAL::FT::CND::operator() ()
check if a condition is met
Returns
true if a condition is met. otherwise, false
Definition at line 321 of file CND.hpp.
References CHECKNULL.
Referenced by is_cond().
override_internal()
void FATAL::FT::CND::override_internal (const boost::shared_ptr< FT_BASE > & i_internal_gate)
override an internal gate with i_internal_gate
Parameters
i_internal_gate new internal gate
Definition at line 282 of file CND.hpp.
References FATAL::FT::FT_BASE::FTs.
Referenced by is_cond().
set_internal()
void FATAL::FT::CND::set_internal (const boost::shared_ptr< FT_BASE > & i_internal_gate)
set an internal gate
Parameters
i_internal_gate new internal gate
Definition at line 264 of file CND.hpp.
References FATAL::FT::FT_BASE::FTs, and FATAL::FT::FT_BASE::put().
Referenced by is_cond().
transform()
boost::shared_ptr< FT_BASE > FATAL::FT::CND::transform () virtual
a function to obtain equivalent gate structure.
Reimplemented from FATAL::FT::FT_BASE.
Definition at line 55 of file GATE/GATE.hpp.
References FATAL::FT::FT_BASE::_equiv_ft, FATAL::FT::FT_BASE::FTs, FATAL::FT::NOT::get_same_type(), and FATAL::FT::NOT::transform().
Referenced by is_cond().
validate()
void FATAL::FT::CND::validate (const boost::shared_ptr< FT_BASE > & i_FT) virtual
a function to validate a conditional gate has 1 element
Parameters
i_FT a shared pointer to FT_BASE which will be added to CND gate.
Reimplemented from FATAL::FT::FT_BASE.
Definition at line 225 of file CND.hpp.
References CHECKSUM, and FATAL::FT::FT_BASE::FTs.
The documentation for this class was generated from the following files:
CND.hpp
GATE/GATE.hpp
GATEOP.hpp
CacBDD_GATEOP.hpp
CUDD_GATEOP.hpp
MCS_GATEOP.hpp
[ FATALPRA Home Page(Not Ready Yet!) ] © 2014–2015, FATALPRA Developer Team.